### ISSUE TITLE
confusing/pointless handling of resolv.conf

### ISSUE THREAD

**Issue by amouat** [CiscoCloud/mantl#1013]
Hi,

I just spent the morning trying to figure out why google internal addresses don't resolve in mantl. You actually do a lot of work in https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/dnsmasq/tasks/main.yml to collect and retain any existing nameservers in resolv.conf. This means you end up with a list of nameservers with localhost at the top.

Unfortunately, this is pointless as it's not the way things work - what actually happens is the first address is used and the others only come into play if the first address is unreachable. It would actually be simpler and less confusing to users if you just overwrite resolv.conf.

To support internal addresses, you should add config for the "recursor" option in Consul.

**Comment by amouat** [comment]
Seems I missed the dnsmasq configuration, which is the right place to fix this. For the time being I just added the internal google nameserver to the template.

It took me a long time to figure out what was going on. I wonder if the whole thing could be simplified somehow, or at least documented better.

**Comment by siddharthist** [comment]
Our new mantl-dns package resolves first against the cloud providers' dns servers. This was fixed in https://github.com/CiscoCloud/mantl/pull/1232
