### ISSUE TITLE
Add copying instructions to sample playbooks

### ISSUE THREAD

**Issue by sehqlr** [CiscoCloud/mantl#1030]
This come up in conversation on the Gitter page: we should include copying instructions at the top of all of our sample files. This should include terraform and ansible samples.

**Comment by siddharthist** [comment]
What is meant here by the phrase "copying instructions"?

**Comment by sehqlr** [comment]
Something simple like "Copy this file into the root directory, then fill in credentials".

**Comment by sehqlr** [comment]
It seems that I linked to this issue from 1099 unintentionally. That PR doesn't have anything to do with this issue. I'm going to make the PR that does.

**Comment by siddharthist** [comment]
So, I'm not sure that this is necessary. Most of our playbooks can just be run as-is where they are. sample.yml has extensive instructions in the getting started guide. Are there any examples in particular you could point out so we can determine what needs to be done, @sehqlr?

**Comment by sehqlr** [comment]
The underlying problem with the sample files is that they are getting to be quite complex. Steve's proposal to have terraform modules hosted online will solve this issue, when it gets implemented. I'm going to close this.
