### ISSUE TITLE
lvm: provider not defined

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#1056]
When installing via bare metal (not terraform), the provider variable is not defined  for lvm tasks, causing an ansible error. 

https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/lvm/defaults/main.yml#L3

provider needs to be defined somewhere or we need to check if provider is defined in the template:

```
lvm_physical_device: "{% if provider == 'gce' %}/dev/disk/by-id/google-lvm{% elif provider == 'aws' %}/dev/xvdh{% elif provider == 'openstack' %}/dev/vdb{% endif %}"

```

**Comment by azimut** [comment]
There is workaround for this?

**Comment by stevendborrelli** [comment]
@azimut you can try setting  `provider=baremetal` in the ansible var file.
