### ISSUE TITLE
consul permissions need to be fixed

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#1061]
Update rules to make sure that permissions and ownership for consul are consistent. 

All files in `/etc/consul` need to be owned by `consul:consul`, and directory permissions should be 770 or 700. 

Any files that contain sensitive information should have unix filesystem permissions of  `700`. 

```
acl.json
agent_acl.json
consul.json
```

`/var/lib/consul` should have permissions of 770.

**Comment by siddharthist** [comment]
This should be changed in our [spec for building consul](https://github.com/asteris-llc/mantl-packaging/blob/master/consul/consul/spec.yml). I'll test today to see what errors we run into with a naive configuration.

**Comment by siddharthist** [comment]
This appears fixed in master, the raft directory doesn't contain any sensitive information that's not in `/etc/hosts`:
```
[centos@lb0-control-01 ~]$ ls -alh /var/lib/consul/
total 8.0K
drwxrwxr-x.  6 consul consul   83 Jul  8 08:14 .
drwxr-xr-x. 35 root   root   4.0K Jul  8 08:32 ..
-rw-r--r--.  1 consul consul  394 Jul  8 07:40 checkpoint-signature
drwx------.  2 consul consul   45 Jul  8 08:14 checks
drwxr-xr-x.  3 consul consul   53 Jul  8 07:40 raft
drwx------.  2 consul consul   90 Jul  8 07:40 serf
drwx------.  2 consul consul   45 Jul  8 08:14 services
```
```
[centos@lb0-control-01 ~]$ ls -alh /etc/consul
ls: cannot open directory /etc/consul: Permission denied
```
