### ISSUE TITLE
Traefik health check warning

### ISSUE THREAD

**Issue by mcapuccini** [CiscoCloud/mantl#1073]
I just tried to provision a new cluster using the playbook on the master branch. On the health checks I get this warning:

```
Status
Warning

Check ID
service:traefik-admin:2

Node
phnmnl-dev-edge-01

Service ID
traefik-admin

Service Name
traefik-admin

Output:
API contains no information. If this is not expected, try restarting traefik.
```

**Comment by ryane** [comment]
on your edge node, can you run `curl -k https://localhost:8081/api` and share the results?

Also, I'm curious what `curl -k https://localhost:8081/health` returns too.

**Comment by mcapuccini** [comment]
Sorry @ryane, I just destroyed the cluster and I am now rebuilding with 0.5.1, maybe some user that will have the same issue can share the results later on. I don't have enough credits on gce to keep many things up and running.

**Comment by ryane** [comment]
No problem, we'll keep an eye out for it. Thanks!

**Comment by ryane** [comment]
Ran into this today. The issue was that marathon was not ready when traefik started:

```
Feb 03 01:44:19 ip-10-0-138-51.ec2.internal traefik[17882]: time="2016-02-03T01:44:19Z" level=error msg="Failed to register for subscriptions, all the Marathon hosts are presently down"
Feb 03 01:44:19 ip-10-0-138-51.ec2.internal traefik[17882]: time="2016-02-03T01:44:19Z" level=error msg="Failed to create a client for marathon, error: all the Marathon hosts are presently down"
```

So, in this scenario, marathon is not successfully registered as a provider in traefik and `/api/providers` returns `{}`. As suggested, restarting traefik resolves the problem. This doesn't seem to happen often, ime, but perhaps we need to check that marathon is up before starting traefik

**Comment by mcapuccini** [comment]
same problem on 0.6.0-RC3. How do I restart Traefik?

**Comment by stevendborrelli** [comment]
You should just be able to run `systemctl restart traefik` on an edge node.

**Comment by mcapuccini** [comment]
Thanks @stevendborrelli it worked (with sudo in front). I have a small cluster now with just one edge node, with more edges do I have to do this on all of them? Or do they somehow restart together when one restarts?

**Comment by ryane** [comment]
@mcapuccini it won't automatically fix other instances of traefik if they are having the same problem. You can restart traefik on all edge nodes with an ansible command if you want:

`ansible 'role=edge' -s -m service -a 'name=traefik state=restarted'`

**Comment by mcapuccini** [comment]
@ryane thanks, this works too!

**Comment by siddharthist** [comment]
This is also a recurring issue in Travis builds, causing erronious failures.
