### ISSUE TITLE
Rename the sample Ansible playbook

### ISSUE THREAD

**Issue by philwinder** [CiscoCloud/mantl#1080]
Why does the sample Ansible config have the word terraform in the filename? To a new user, the use of terraform implies that this has something to do with Terraform, not Ansible. Rename to avoid confusion.

**Comment by stevendborrelli** [comment]
This is a good point. Thanks for bringing it up. 

What do folks think of `mantl.yml`?

**Comment by philwinder** [comment]
Yes. Or simply `example.yml` or `sample.yml`. Just not `terraform.xxx`.

**Comment by siddharthist** [comment]
It might be nice to contrast with `kubernetes.yml`, e.g. `mesos.yml`. But that might lead to the same confusion. I like `sample.yml`.

**Comment by sehqlr** [comment]
I was taking another look at this, and I propose that we make an additional change. In the docs, we have the users copy `terraform.sample.yml` to `terraform.yml`. I propose that we change `terraform.yml` to `mantl.yml`, so the docs would say something like:
> copy sample.yml to mantl.yml in the root directory to get started

We would need to change our CI stuff to match with this, but I think the name change justifies the work.

**Comment by siddharthist** [comment]
Closed in #1119
