### ISSUE TITLE
Clean up old / dead branches

### ISSUE THREAD

**Issue by benschumacher** [CiscoCloud/mantl#1104]

**Comment by siddharthist** [comment]
Let's all comment with candidates for deletion, and delete our own dead branches when they are correctly suggested or comment that they shouldn't be deleted. 
 - [ ] feature/frameworks (Y4Rv1K)
 - [ ] feature/disable-auth (tymofii-polekhin) 
 - [ ] feature/haproxy-ssl (BrianHicks) 
etc. Sound good to everyone?

**Comment by sehqlr** [comment]
Sounds okay to me. I don't have too many branches, so it should be easy to clean them up. 

Maybe the rule should be that a branch should be pruned if it has no PR associated with it, and it's older than X amount of weeks?

**Comment by benschumacher** [comment]
That'd be fine w/me Sam. I don't feel like we need to be too process oriented, but it has been commented on.

**Comment by sehqlr** [comment]
Alright, I've cleaned up my branches. The `drone-ci` branch should be kept, even though the PR for it #990 has been closed.

**Comment by benschumacher** [comment]
Thanks. We'll circle back on Drone, soon. There's work being done to facilitate what we're trying to accomplish. Beyond the issues raised by @siddharthist, there's also this discussion: https://github.com/drone/drone/issues/1476

**Comment by siddharthist** [comment]
This issue will always be a work in progress, but we've gone down from ~60 to ~30 branches, the vast majority of which are quite active. Closing for now, please reopen if this becomes a bigger issue again.
