### ISSUE TITLE
Marathon containers can't write into /mnt/container-volumes

### ISSUE THREAD

**Issue by mcapuccini** [CiscoCloud/mantl#1118]
Hi! I've just deployed GlusterFS. I am using this json to deploy a Jupyter container through Marathon, mounting the work directory over /mnt/container-volumes to persist the data.

```
{
	"cpus": 0.25, 
	"mem": 128,
	"id": "jupyter",
	"instances": 1,
	"labels": {"traefik.frontend.entryPoints":"http,https,ws"},
	"container": {
    		"type": "DOCKER",
    		"docker": {
      			"image": "jupyter/minimal-notebook",
      			"network": "BRIDGE",
			"privileged": true,
			"portMappings": [{
                    		"containerPort": 8888,
                    		"hostPort": 0,
                    		"protocol": "tcp"
                	}]
    		},
		"volumes": [{
                	"containerPath": "/home/jovyan/work",
                	"hostPath": "/mnt/container-volumes/jupyter",
                	"mode": "RW"
            	}]
	}
}
```

The container seems to don't have permission to write in /mnt/container-volumes/jupyter, is this a bug? Or am I missing some additional configuration?

Regards
Marco

**Comment by siddharthist** [comment]
Is SELinux set to enforcing mode? https://github.com/CiscoCloud/microservices-infrastructure/issues/867

**Comment by mcapuccini** [comment]
@siddharthist I am using 0.6.0-RC3 vanilla installation. However, it looks like the fix (https://github.com/CiscoCloud/microservices-infrastructure/commit/22f550b6860a23631acc59ee159b1a0d5cb4347f) that sets selinux to permissive mode is no longer there in version 0.6.0-RC3 (https://github.com/CiscoCloud/microservices-infrastructure/blob/0.6.0-RC3/roles/glusterfs/tasks/main.yml). Are you aware of that? Do you have any separate playbook to set permissive mode?

**Comment by siddharthist** [comment]
@mcapuccini Could you run `ansible all -a sestatus` on your hosts so we can see if that's the issue?

**Comment by mcapuccini** [comment]
@siddharthist both commands return the following error:

```
mantl060rc3-worker-02 | FAILED | rc=2 >>
[Errno 2] No such file or directory

mantl060rc3-control-01 | FAILED | rc=2 >>
[Errno 2] No such file or directory

mantl060rc3-worker-03 | FAILED | rc=2 >>
[Errno 2] No such file or directory

mantl060rc3-worker-01 | FAILED | rc=2 >>
[Errno 2] No such file or directory

mantl060rc3-edge-01 | FAILED | rc=2 >>
[Errno 2] No such file or directory
```

**Comment by siddharthist** [comment]
Hmm, I'm not sure SELinux is the problem here, but here's an article that explains how to install the appropriate packages and see if it's enforcing: https://www.digitalocean.com/community/tutorials/an-introduction-to-selinux-on-centos-7-part-1-basic-concepts

In the meantime, can you post more information about the problem? How can you tell containers don't have write access? Are there relevant logs? What are the permissions on the folder? Can you manually create anything on it? What commands did you run to deploy GlusterFS?

**Comment by mcapuccini** [comment]
@siddharthist the problem is that the host folder `/mnt/container-volumes/jupyter`, which is automatically created by Marathon, is owned by root. Changing the ownership to centos solves the problem. Not a big deal, but it is a bit annoying to change the ownership for each new microservice. Maybe you can somehow make this less cucumbersome in future releases. Thanks for the help!

**Comment by siddharthist** [comment]
@mcapuccini I'm glad you've got it sorted out! I'll open an issue for doumenting the owner of /mnt/container-volumes. What user did you change the ownership to to make it work?

Also: I think Jupyter/iPython would be an awesome example app if you want to make a PR :)

**Comment by mcapuccini** [comment]
@siddharthist I changed it to centos. Yes, I will make a PR as soon as I have time. Also, we are considering using Mantl to provide the e-infrastructure for the PhenoMeNal project ([http://phenomenal-h2020.eu/home/about/](http://phenomenal-h2020.eu/home/about/)).
