### ISSUE TITLE
Remove Logstash from default installation

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1130]
Logstash is a pretty heavy component, it runs a Docker container on every host. Now that we have an ELK stack addon, I don't think we need [this line](https://github.com/CiscoCloud/mantl/blob/master/terraform.sample.yml#L27). Logstash doesn't forward logs anywhere by default, so the useful part is when it's combined with the whole ELK stack. Thoughts?

**Comment by zoza1982** [comment]
Once we have Mesos-elasticsearch framework up we can send MANTL logs to it by setting logstash new output. But...the questions is in this new ELK stack....there is a logstash framework...right? So I assume Logstash framework will be used only to send application ( container ) logs to Mesos-ES...

On logstash vs Logstash-framework side....They kind of overlap....Logtstash Framework is better as its optional....and easily configurable...but we need something concrete logging solution by default for Mantl itself.....

Maybe logstashforwarder ( aka lumberjack ) for MANTL itself? ( its super light )...or even fluentd ? And then have Logstash-framework for general use.

**Comment by ryane** [comment]
At this time, we are not using the logstash framework (see discussion in #1117). The framework would not have been a complete solution for collecting logs on all Mantl node types.

The current ELK addon that we just merged is still dependent on the existing logstash role. It configures the logstash instances that are installed on all nodes by that role to output logs/metrics to the elasticsearch cluster when present. 

It should now be possible to support alternative, lighter-weight log shippers as long as they can be configured to output to automatically discovered elasticsearch instances.

**Comment by siddharthist** [comment]
@ryane Should Logstash be installed by default, or be a part of the ELK stack addon?

**Comment by ryane** [comment]
@siddharthist I'm thinking it should be kept separate from the ELK addon. We can replace it with a lighter weight shipper as long as it will work with the rest of the stack. But, the only reason we are shipping the elasticsearch cluster as an addon right now is because we don't yet have a good, safe way to dynamically size it during provisioning (our default cluster configurations don't provision enough resources).

**Comment by siddharthist** [comment]
@ryane Thanks for clarifying all that :)

**Comment by benschumacher** [comment]
A lighter weight shipper would make a lot of sense. The ultimate goal should be to have a Kafka sink as a "default" output of the log shipper to a bounded topic (max of 24 hours?), which will be able to ultimately send data to a long term storage backend -- Elastic or InfluxDB, depending on data type. This gives us more flexibility, and eliminates the need for "core" Mantl to manage long term storage, as that functionality is highly use case specific.
