### ISSUE TITLE
reboot hosts script doesn't work 

### ISSUE THREAD

**Issue by shali-mor** [CiscoCloud/mantl#1144]
HI , 
I'm running a setup on CCS , having 3 control machines , 2 worker machines and one edge. 
When using 'ansible-playback playbook/reboot-hosts.yml , marathon,chronos, and traefik-admin fail to come-up. 
the only way to solve this is by destroying the setup and re-run it again.  (the destroy script completed successfully) . 

this issue is always reproducible.

**Comment by siddharthist** [comment]
@shali-mor Can you please post logs from those services from immediately after reboot so we can take a look at what's going on?

**Comment by shali-mor** [comment]
As I have a working setup , I will not reproduce at the moment. 
once reproduced , I'll attach the files.

**Comment by siddharthist** [comment]
Closing as a duplicate of #1238
