### ISSUE TITLE
User's PC login password is stored in plain text after security setup

### ISSUE THREAD

**Issue by philwinder** [CiscoCloud/mantl#1148]
Mantl just took my OS password and converted it into plain text!

```
(venv)[phil-mac@Phils-MBP-2 microservices-infrastructure (6778c27 ✗)]$ cat security.yml 
---
chronos_http_credentials: admin:MY_PASSWORD!
...
```

To recreate:
```
git clone https://github.com/CiscoCloud/microservices-infrastructure.git
cd microservices-infrastructure
git checkout 0.5.1
./security-setup
cat security.yml
```
I've deleted security.yml and re-run ./security-setup and this time it prompted me for the password. It definitely did not prompt the first time. From my bash history:
```
(venv)[phil-mac@Phils-MBP-2 microservices-infrastructure (6778c27 ✗)]$ ./security-setup 
============= Certificates =============
----> certificate authority
serial already exists
index already exists
root CA already exists
================ Nginx =================
----> SSL certificate
nginx key already exists
nginx certificate already exists
nginx certificate is valid
----> admin password
nginx admin password already set
================ Consul ================
----> check security
....
```
Note the "password already set" message.

**Comment by ryane** [comment]
I cannot reproduce this. `security-setup` should always prompt for a password if it is not already set in security.yml or if if security.yml doesn't exist. Are you sure you didn't already have an existing security.yml file with your password in it?

**Comment by philwinder** [comment]
Hmm, you're right. I've just retried now, and it's not doing what it did before. This was a few weeks ago, and I'm sure I retried and it did the same thing. I'll close for now. Sorry!
