### ISSUE TITLE
Vagrant Deployment Broken?

### ISSUE THREAD

**Issue by HarryDePryor** [CiscoCloud/mantl#1152]
The 0.5 versions that worked on a single machine were fine, but later versions don't appear to work "out-of-the-box" with Vagrant.

The portal page doesn't show Mesos passing any health checks - and accessing that screen just fails to connect to port 443.

The marathon UI shows manta-api and mesas-consul in either "deploy" or "waiting" state ( appears to just alternate between the two when you refresh the page ).

( OSX, checkout, run security setup, then vagrant up )

**Comment by ryane** [comment]
sorry about that. we just merged PR #1138 that included the updated box in the Vagrantfile. I just ran a test from master and the Vagrant build was successful. Can you try on master or update your Vagrantfile to use:

```
  config.vm.box = "CiscoCloud/mantl"
```

and see if you have better luck?

**Comment by HarryDePryor** [comment]
Looks good to me. Thx.
