### ISSUE TITLE
File Referenced in Openstack deployment instructions missing

### ISSUE THREAD

**Issue by limited** [CiscoCloud/mantl#1157]
The installation instructions on this page https://microservices-infrastructure.readthedocs.org/en/latest/getting_started/openstack.html make reference to a file terraform/openstack-floating.sample.tf

This file is missing in the master branch (it appears since v 0.5.1) and it is not clear what file should be used in its place

**Comment by siddharthist** [comment]
@limited You'll want to use terraform/openstack-modules.sample.tf. Wanna put in a PR for the documentation? Thanks for noticing!
