### ISSUE TITLE
Terraform apply ssh failure

### ISSUE THREAD

**Issue by lowwalker** [CiscoCloud/mantl#1158]
Using terraform 0.6.11 I received this output 

```
* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain 
```

The nodes were provisioned, however the run did not successfully complete. After tinkering, the work around that moved me through was to adjust my terraform/gce/instance/main.tf file provisioner block to the below example.

```
  provisioner "remote-exec" {
    script = "./terraform/gce/disk.sh"

    connection {
      type = "ssh"
      user = "${var.ssh_user}"
      agent = false
      key_file = "${file("~/.ssh/id_rsa")}"
    }
  }
}
```

**Comment by lowwalker** [comment]
Additionally I executed the workaround here - https://github.com/CiscoCloud/mantl/issues/1149

However that did not clear my issue, the above change + 1149 did.

**Comment by siddharthist** [comment]
For posterity, this is what it is now:
```
  provisioner "remote-exec" {
    script = "./terraform/gce/disk.sh"

    connection {
      type = "ssh"
      user = "${var.ssh_user}"
    }
  }
}
```
Should this be integrated into #1149, @ryane?

**Comment by ryane** [comment]
Possibly. This is the first time (that I know of) that we've seen this - and I can't reproduce it (from two different machines). We could certainly add another variable (`ssh_private_key`, possibly) but it would be nice to know why it was necessary for @lowwalker. Anyone have any ideas?

**Comment by ryane** [comment]
also, perhaps another option would be to remove the `remote-exec` block entirely and move the disk setup to cloud-init. I am just not sure about the required reboot. As a reminder, the disk.sh script is necessary to increase the size of the root disk for the gce instances. Without it, the disk capacity is tied to the base image (around 9 GB currently).

**Comment by ryane** [comment]
actually, setting `key_file = "${file(var.ssh_private_key)}"` is not a great solution b/c it breaks for those of us who have password protected private keys. any other ideas how to solve this problem?

```
* Failed to read key "-----BEGIN RSA PRIVATE KEY-----\n.....\n-----END RSA PRIVATE KEY-----\n": password protected keys are
not supported. Please decrypt the key prior to use.
```

**Comment by lowwalker** [comment]
I've not tried with a passworded key file, but I did just update to 0.6.12 on terraform and still had to adjust the connection block. I'll try with cloud-init now to see if it's viable.

**Comment by RaunoVV** [comment]
First post seems to fix the issue, had this issue for a while already.

**Comment by siddharthist** [comment]
@lowwalker @RaunoVV Any ideas what's going on in your environment that might be different than ours and might cause this?

**Comment by siddharthist** [comment]
Closing as a duplicate of #1351
