### ISSUE TITLE
distributive rpm conflict

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#1182]
Getting bintray errors between: 

```
distributive-master-20150720git.master.el7.centos.x86_64
```
when trying to install 
```
ASK: [common | install distributive] ***************************************** 
failed: [shipped-int-control-01] => {"changed": false, "failed": true, "rc": 1}
msg: Package at https://bintray.com/artifact/download/ciscocloud/rpm/distributive-0.2.1-5.el7.centos.x86_64.rpm could not be installed
```

@siddharthist what is the version we need to be using? I don't know where distributive-master is coming from.

**Comment by siddharthist** [comment]
We should use the tagged version, I'm not sure why it's trying to download anything else. The URL is specified [here](https://github.com/CiscoCloud/mantl/blob/2ea7f819ce6bdbf0b0497fb83ba11d2d2158a6fd/roles/common/defaults/main.yml#L6).
