### ISSUE TITLE
Stop Travis builds with success if no secrets were injected

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1192]
Travis doesn't inject secrets for outside builds, but this can be confusing. Travis should exit with success for PRs that aren't from people with push access. See https://travis-ci.org/CiscoCloud/mantl/jobs/112976692

**Comment by siddharthist** [comment]
This will necessitate a move to a real `install` script, which @sehqlr is working on as part of a new Docker-based deploy process. Could this change be folded into that branch, Sam?

**Comment by sehqlr** [comment]
Yeah, I think that would be good. I would like to port the logic to something not bash. So, I'll close this branch, but I won't delete the branch.
