### ISSUE TITLE
ELK as Jar vs Container running mode.

### ISSUE THREAD

**Issue by zoza1982** [CiscoCloud/mantl#1205]
As a super-user for elasticsearch and a service owner/architect of giant Enteprise Elasticsearch cluster in Cisco-webex I wanted to point few things of why we should run ELK in container mode.

Running Elasticsearch on K8's or Elasticsearch on Mesos, it is imperative to allow users to customize executor for many things...like elasticsearch version and embed other very cool plugins for cluster management. That can be only done in container mode . 

Enterprise needs and paid ELK customer:

For example for Enterprises use case.... ES plugin is Shield , which allows us fine grained RBAC and LDAP auth for both Elasticsearch API and Kibana. It also gives you easy ability for Multi-tenancy so you don't have to run multiple ELK clusters for logging different applications and still have nice separation between the two.

Other cool  plugins  free and commercial:

Not running in container you loose ability to run other plugins such as Marvel ( metrics ) , Watcher (alerting) KOPF, Paramedic...etc.

Other reasons would be simplicity of upgrades and management.

If you run in jar mode, you can't have easily your own custom executor ...and you are facing all the limitations from above. Which is indeed significant limitation to move your production ELK systems to MANTL.

**Comment by siddharthist** [comment]
So if we enable `framework_use_docker` by default and it works, is this issue solved?

**Comment by zoza1982** [comment]
@siddharthist  maybe...if it works. I can test it ....We also need to support passing elasticsearch-mesos framework option of  :

``--elasticsearchDockerImage
       The elasticsearch docker image to use. E.g. 'elasticsearch:latest'
       [DOCKER MODE ONLY]
``

**Comment by siddharthist** [comment]
Testing those modifications now with `elasticsearch_docker_image: elasticsearch:2.2.0`

**Comment by zoza1982** [comment]
+1

**Comment by zoza1982** [comment]
Check the version afterward.... e.g    ``curl -XGET 'http://192.168.50.142:4000'`` against any node which runs ES on port 4000 ( check in consul )

**Comment by siddharthist** [comment]
@zoza1982 With the following diff from master
```
 framework_version: "0.7.1"
 framework_name: "elasticsearch"
 framework_ui_port: 31100
-framework_use_docker: false
+framework_use_docker: true
+elasticsearch_docker_image: elasticsearch:2.2.0
 framework_download_url: "https://github.com/mesos/elasticsearch/releases/download/{{ framework_version }}/scheduler-{{ framework_version }}.jar"
 
 kibana_image: kibana
diff --git a/roles/elk/templates/elasticsearch.json.j2 b/roles/elk/templates/elasticsearch.json.j2
index 52d0441..1a3d479 100644
--- a/roles/elk/templates/elasticsearch.json.j2
+++ b/roles/elk/templates/elasticsearch.json.j2
@@ -15,6 +15,7 @@
     "--elasticsearchExecutorCpu", "{{ elasticsearch_executor_cpu }}",
     "--elasticsearchDisk", "{{ elasticsearch_disk }}",
     "--frameworkUseDocker", "{{ framework_use_docker }}",
+    "--elasticsearchDockerImage", "{{ elasticsearch_docker_image }}",
     "--elasticsearchClusterName", "{{ elasticsearch_cluster_name }}",
     "--webUiPort", "{{ framework_ui_port }}",
     "--frameworkName", "{{ framework_name }}"{% if do_mesos_auth %},
```
I get this error from Mesos: 
```
Registered executor on lb-mi-worker-001.node.consul
Starting task elasticsearch.c2006e11-e0d2-11e5-9419-3a73a9b34c03
[java, java, -jar, scheduler-0.7.1.jar, --zookeeperMesosUrl, zk://mesos:yUy2c9GPBJQ7vnse@zookeeper.service.consul:2181/mesos, --elasticsearchNodes, 3, --elasticsearchCpu, 1.0, --elasticsearchRam, 1024, --elasticsearchExecutorRam, 1024, --elasticsearchExecutorCpu, 1.0, --elasticsearchDisk, 5120, --frameworkUseDocker, True, --elasticsearchDockerImage, elasticsearch:2.2.0, --elasticsearchClusterName, mantl, --webUiPort, 31100, --frameworkName, elasticsearch, --frameworkPrincipal, mantl-api, --frameworkSecretPath, /etc/sysconfig/mantl-api]
Forked command at 18899
com.beust.jcommander.ParameterException: Unknown option: --elasticsearchDockerImage
Usage: (Options preceded by an asterisk are required) [options]
  Options:
    --dataDir
       The host data directory used by Docker volumes in the executors. [DOCKER
       MODE ONLY]
       Default: /var/lib/mesos/slave/elasticsearch
    --elasticsearchClusterName
       Name of the elasticsearch cluster
       Default: mesos-ha
[...]
Command exited with status 1 (pid: 18899)
```
Are you sure that's a legal option?

**Comment by siddharthist** [comment]
Looks like `--executorImage` might be what we're looking for.

**Comment by siddharthist** [comment]
When I used a configuration with `--executorImage`, the ES dashboard showed "100% TASK_STAGING" continuously, and the Kibana dashboard showed "Unable to connect to Elasticsearch at http://localhost:9200." Both Kibana and ES framework health checks failed with:
```
Kibana is not healthy.
```
and 
```
curl: (7) Failed connect to 45.55.61.177:4000; Connection refused
The Elasticsearch cluster is not healthy.
```
I wonder if there's some kind of port forwarding issue with Marathon? I'll dig deeper.

**Comment by siddharthist** [comment]
Well, just adding ports 9200 and 4000 to the Marathon port list didn't resolve it.

**Comment by zoza1982** [comment]
@siddharthist  I guess this comes back to original question which even @ryane was not sure. If ``framework_use_docker`` actually works?

**Comment by zoza1982** [comment]
@siddharthist where did you get ``--executorImage `` from? I listed options from official docs http://mesos-elasticsearch.readthedocs.org/en/latest/  and I cannot find it.

**Comment by siddharthist** [comment]
@zoza1982 It was in the error message when I used `--elasticsearchDockerImage`. Must be different framework versions (or a documentation bug).

**Comment by zoza1982** [comment]
@siddharthist  I would just try with  ``framework_use_docker` only and not specify the image for a start and let it be driven by whatever default is...for purpose to check if Framework can work in hybrid mode...meaning  we are trying here to run scheduler in Jar mode  , but we are asking then to run executor in docker mode. That's the million dollar question to find out ....

**Comment by zoza1982** [comment]
@siddharthist  0.7.2 is newest version , probably -- options changed ...or as you say documentation error...

**Comment by zoza1982** [comment]
@siddharthist  I will repeat the process in the morning on my side.... And add newer framework version into picture.  0.7.2  

Thanks for testing this today

**Comment by ryane** [comment]
I spoke with the framework devs and the reason that it was recommended that we switch to running in Jar mode for this release was due to a potential docker bug: https://github.com/docker/docker/issues/10294

I don't know if that is what you're running into or just another potential problem to look out for.

The error you might see would be something like this:

```
Error response from daemon: mkdir /var/lib/docker/overlay/ab6e227fba059ffea80a5385d4fccf4cc42187fca8b2842e63ab222b981aa8e5-init/merged/dev/shm: invalid argument
```

**Comment by zoza1982** [comment]
@ryane thanks for info. This helps too. I doubted that reason switching to jar had some bigger benefits than container mode.
