### ISSUE TITLE
Maintain ansible playbooks to remove ELK stack

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1207]
Right now to remove the ELK stack, our documentation directs the user to copy/paste shell scripts, change their contents, and execute them. We should either maintain these scripts as Ansible playbooks (since they contain many Ansible commands already) or as separate `.sh` files. This way, they can be changed, linted, tested, and used without manual intervention. 

See: https://github.com/CiscoCloud/mantl/tree/d8b7e9d9e935c03b65b22ba4e1f3e2b641731738/roles/elk

**Comment by zoza1982** [comment]
I could not agree more with you....

**Comment by siddharthist** [comment]
Related/sub-issue: #1233
