### ISSUE TITLE
Remove Zookeeper, Logstash from Docker in control node image in README

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1212]
As of #1130 and #873, [this image is outdated](https://github.com/CiscoCloud/mantl/blob/ef42dfb42c60815a953832f005bc73eedcfbdd1a/docs/_static/control_node.png). Zookeeper should be outside of Docker, and logstash should be removed. We might also want to include mantlui and Vault.

**Comment by sehqlr** [comment]
Looking at the history of the image, it looks like maybe @ryane would be in charge of these images?

**Comment by ryane** [comment]
the originals are in a Keynote file in `docs/_static/diagrams.key`
