### ISSUE TITLE
Traefik disable forwarding by default option

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#1214]
See https://github.com/containous/traefik/issues/233. 

In some deployments there is a desire to not forward traffic unless it is explicitly enabled. Right now traefik will expose any container unless explicitly turned off. 

If this feature is added to upstream traefik, we can make it an option in our deployment.

**Comment by siddharthist** [comment]
This option can be set in master: https://github.com/CiscoCloud/mantl/blob/ad1892417ff25595dfb759de56873f7e76c82f97/roles/traefik/defaults/main.yml#L7
