### ISSUE TITLE
OpenVPN role on edge node.

### ISSUE THREAD

**Issue by zoza1982** [CiscoCloud/mantl#1226]
Did you think of OpenVPN role to piggy-back on edge-node?

Not everyone has public-facing IP's or bunch of floating IP's to spare..... I use ssh-tunnel for most of connections to Internal control-node to get into mantl ui/mesos/marathon...etc. on Cisco Cloud ( Openstack ). OpenVPN role can help a lot.

There are some good ansible openvpn roles on github we can borrow....

**Comment by siddharthist** [comment]
Could this be an addon?

**Comment by zoza1982** [comment]
@siddharthist  Yes as we agreed on MANTL chat with @stevendborrelli  ...that we should start with making it as add-on.
I am not sure about licensing of openvpn...let me check....I've been using it forever...never checked though...

**Comment by zoza1982** [comment]
@siddharthist its GNU GPL ...its that a problem?
![screen shot 2016-03-03 at 5 21 46 pm](https://cloud.githubusercontent.com/assets/11164593/13515225/91807802-e164-11e5-95b0-4d4540c15cbd.png)

**Comment by zoza1982** [comment]
I am not a licensing expert...but don't see whats wrong with this:

"The GNU General Public License (GNU GPL or GPL) is a widely used free software license, which guarantees end users (individuals, organizations, companies) the freedoms to run, study, share (copy), and modify the software."

**Comment by zoza1982** [comment]
http://stackoverflow.com/questions/2982364/how-does-apache-2-0-license-differ-from-gpl

**Comment by siddharthist** [comment]
@zoza1982 I just mean the Ansible role, not OpenVPN :) sorry if that was unclear!

**Comment by zoza1982** [comment]
Oh :+1:  ...that would not be a problem. We can write one ourselves in the worst case.

**Comment by siddharthist** [comment]
@zoza1982 Are you planning on working on this? We can assign it to you so nobody does concurrent work.

**Comment by zoza1982** [comment]
Assign this one to me...

**Comment by zoza1982** [comment]
I will submit PR once its ready.

**Comment by zoza1982** [comment]
@siddharthist   any preference GPLv2 license vs MIT license ?
I found two good candidates for ansible openvpn roles I can work from...

**Comment by siddharthist** [comment]
@zoza1982 MIT would be best, thanks!

**Comment by siddharthist** [comment]
@zoza1982 Have you gotten OpenVPN working?

**Comment by siddharthist** [comment]
Closing this due to lack of interest. Please reopen if anyone wants to implement this functionality!

**Comment by zoza1982** [comment]
@siddharthist  Sorry, I have been busy...horribly busy. Mostly what held me (when I had time to work on this) is using MIT licensed ansible code which I did not liked and involves a lot of changes to make it work. The GPLV2 based ansible code is a lot easier to work with...but this project does not likes it.

Not to  keep any hope high, let's keep this closed...and then I will re-open when I get time to get it done. I will give my best.
