### ISSUE TITLE
DNSMasq Configuration blocks metadata.google.internal

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/mantl#1230]
- Ansible version (`ansible --version`): 1.9.2
- Python version (`python --version`): 2.7.9
- Git commit hash or branch: feature/fewer-logs-please
- Cloud Environment: GCE
- Terraform version (`terraform version`): 0.6.12

Consul logs get a lot of these warnings on GCE:

```
Mar 04 15:23:03 asteroid-control-01 consul[7194]: 2016/03/04 15:23:03 [WARN] dns: QName invalid: metadata.google.internal.
```

(and I do mean a **lot**, periods of 30 seconds producing 11ish logs per second)

It looks like this is because we're modifying the default `resolv.conf` and overriding information:

```
search consul c.asteris-mi.internal. google.internal. c.asteris-mi.internal
nameserver 127.0.0.1
nameserver 169.254.169.254
nameserver 10.0.0.1
```

This means that while `metadata.google.internal` should be queried from `169.254.169.254` (it works with `dig @169.254.169.254 metadata.google.internal`), it's being queried from DNSMasq. DNSMasq asks Consul, which doesn't know about it, and then DNSMasq is configured to ask Google's public DNS (`8.8.8.8` and `8.8.4.4`).

We can probably avoid this error by moving the system `resolv.conf` to `resolv.cloud.conf` and configuring DNSMasq to use it as a fallback instead of public DNS. This work probably blocks completely internal deployments, as well.

**Comment by stevendborrelli** [comment]
Is there any reason to keep the google DNS addresses in dnsmasq?

**Comment by BrianHicks** [comment]
Not to my knowledge. #1232 removes them. My take: we should assume that whatever cloud Mantl is running on has valid DNS set up. If the user chooses to use Google DNS, they can put it in `/etc/resolv.conf.masq`.

**Comment by BrianHicks** [comment]
@stevendborrelli https://github.com/CiscoCloud/mantl/pull/1232/files#diff-ef07c9094709f0c6d8a39f7b0144f733R12
