### ISSUE TITLE
ELK role removal docs , steps missing.

### ISSUE THREAD

**Issue by zoza1982** [CiscoCloud/mantl#1233]
@ryane I figured out adding few more lines in ELK role removal process would be good. 
Otherwise logstash could consume even more resources and generating useless error logs that it cant post data to elasticsearch which is not there anymore.

On all nodes:

``ansible all -s -m shell -a  'rm -rf /etc/logstash/logstash.d/logstash-elasticsearch.conf'``
 
Then notify logstash to restart in order to reload config without  elasticsearch output.

**Comment by zoza1982** [comment]
I guess since removal is not yet ansible  code....we need also:

``ansible all -s -m shell -a 'systemctl restart logstash'``

**Comment by ryane** [comment]
thanks for this @zoza1982. I'd like to find out why you had to do this though. consul-template should have removed the elasticsearch output from logstash-elasticsearch.conf and restarted logstash. I tried to duplicate on my cluster. After removing ELK, everything seemed to clean itself up properly. logstash-elasticsearch.conf is empty, logstash restarted and is not logging any errors. Any idea how to repro?

**Comment by zoza1982** [comment]
@ryane  Good question....I don't know....it was left there for some reason in my case. Let me check again....it could be me...did something weird...let go trough my uninstall steps which are taken from documentation you made.

**Comment by zoza1982** [comment]
Ok I tested it cleanly.

Result for me are not good, sometimes it would remove some of them...sometimes none.

Do me a favor: 

Run this in one terminal windows and watching while you install , then wait for executor nodes to boot..and once cluster is green ....run your uninstall steps.

``watch "ansible all -s -m shell -a 'ls /etc/logstash.d/'"``

And tell me do you see all elasticsearch conf files going away?


I also have to mention I am running it with ``framework_use_docker: true`` as today on my freshly installed MANTL cluster addons/elk would not install in jar mode.

**Comment by ryane** [comment]
actually, the file should not go away. the output will just be removed from it. here is what it looks like with the framework running and healthy:

```
$ ansible all -s -m shell -a 'cat /etc/logstash.d/logstash-elasticsearch.conf'
resching-aws-worker-03 | success | rc=0 >>

output {
  elasticsearch {
    host => ["10.1.1.57:4000","10.1.1.57:4002","10.1.2.74:4000","10.1.3.247:4000","10.1.3.247:4002"]
    protocol => "http"
  }
}

resching-aws-worker-02 | success | rc=0 >>

output {
  elasticsearch {
    host => ["10.1.1.57:4000","10.1.1.57:4002","10.1.2.74:4000","10.1.3.247:4000","10.1.3.247:4002"]
    protocol => "http"
  }
}

resching-aws-worker-01 | success | rc=0 >>

output {
  elasticsearch {
    host => ["10.1.1.57:4000","10.1.1.57:4002","10.1.2.74:4000","10.1.3.247:4000","10.1.3.247:4002"]
    protocol => "http"
  }
}

resching-aws-control-02 | success | rc=0 >>

output {
  elasticsearch {
    host => ["10.1.1.57:4000","10.1.1.57:4002","10.1.2.74:4000","10.1.3.247:4000","10.1.3.247:4002"]
    protocol => "http"
  }
}

resching-aws-control-01 | success | rc=0 >>

output {
  elasticsearch {
    host => ["10.1.1.57:4000","10.1.1.57:4002","10.1.2.74:4000","10.1.3.247:4000","10.1.3.247:4002"]
    protocol => "http"
  }
}

resching-aws-edge-01 | success | rc=0 >>

output {
  elasticsearch {
    host => ["10.1.1.57:4000","10.1.1.57:4002","10.1.2.74:4000","10.1.3.247:4000","10.1.3.247:4002"]
    protocol => "http"
  }
}

resching-aws-control-03 | success | rc=0 >>

output {
  elasticsearch {
    host => ["10.1.1.57:4000","10.1.1.57:4002","10.1.2.74:4000","10.1.3.247:4000","10.1.3.247:4002"]
    protocol => "http"
  }
}
```

Then, I uninstall the framework. After a few moments, I get:

```
$ ansible all -s -m shell -a 'cat /etc/logstash.d/logstash-elasticsearch.conf'
resching-aws-worker-03 | success | rc=0 >>


resching-aws-worker-01 | success | rc=0 >>


resching-aws-worker-02 | success | rc=0 >>


resching-aws-edge-01 | success | rc=0 >>


resching-aws-control-03 | success | rc=0 >>


resching-aws-control-02 | success | rc=0 >>


resching-aws-control-01 | success | rc=0 >>
```

Logstash also was restarted on all nodes.

**Comment by zoza1982** [comment]
@ryane , got it . So...you leave the file....I was not paying attention of what's in the file after the fact. My apology....
We can close this then. Thank you sir.

**Comment by zoza1982** [comment]
This left me now wonder how did I see files going away?? You must be thinking ...I am cu-cu :-) Hah

**Comment by ryane** [comment]
hah hah, no I'm glad you're testing this stuff!
