### ISSUE TITLE
rebooting hosts script doesn't look at the security state while running

### ISSUE THREAD

**Issue by shali-mor** [CiscoCloud/mantl#1235]
Hi , 
when trying to run the reboot script : ansible-playbook playbooks/reboot-hosts.yml
it fails with : 
failed: [localhost] => {"failed": true}
msg: Security is not enabled. Please run `security-setup` in the root..... 

The security setup I run was : ./security-setup --enable=false

I'm running on CCS . 
some information on my setup : 

I'm using the following versions : 
Mantl 1.0.3-RC1
terraform : v0.6.11
Python 2.7.11
ansible 1.9.4

**Comment by siddharthist** [comment]
If you have security disabled, you'll want to remove [the line including check-requirements.yml](https://github.com/CiscoCloud/mantl/blob/7dcd3a7/playbooks/reboot-hosts.yml#L2) from any playbooks you run. We recommend enabling security, even on test/dev clusters.

**Comment by shali-mor** [comment]
HI ,
I would expect that the check-requiroentns will take into consideration the fact that security is set to false....
don't you think so ?

The reason we're not using security at the moment is to ease our work. we'll use it eventually...

Thanks
Shali.

**Comment by siddharthist** [comment]
@shali-mor That's a good point. Check out the PR that references this issue for a possible compromise. How does that look to you?

**Comment by shali-mor** [comment]
can you give me exact link ? I'm afraid I don't follow your suggestion

**Comment by ryane** [comment]
you should be able to run playbooks/reboot-hosts.yml even on a cluster that was built with `./security-setup --enable=false`. But, right now, you need to specify the security.yml file when you run it:

`ansible-playbook -e @security.yml playbooks/reboot-hosts.yml`

**Comment by shali-mor** [comment]
Ok great

Sent from my iPhone

On Mar 7, 2016, at 17:35, Ryan Eschinger <notifications@github.com<mailto:notifications@github.com>> wrote:


you should be able to run playbooks/reboot-hosts.yml even on a cluster that was built with ./security-setup --enable=false. But, right now, you need to specify the security.yml file when you run it:

ansible-playbook -e @security.yml playbooks/reboot-hosts.yml

-
