### ISSUE TITLE
Unlisted dependency on libselinux-python

### ISSUE THREAD

**Issue by bwsw** [CiscoCloud/mantl#1247]
After successfuly run:
ansible-playbook -u root -i inventory playbooks/upgrade-packages.yml

trying to run
ansible-playbook -i /root/inventory -e @security.yml mantl.yml

fails with error about absence of libselinux-python

command
ansible all -i /root/inventory -m yum -a "name=libselinux-python state=present"
solves it.

Suppose, that upgrade-packages.yml playbook should include this dependency.

**Comment by siddharthist** [comment]
What image were you using on your hosts? Can you post the error? If this package is required, we should add it to the common role.

**Comment by bwsw** [comment]
Hello, I use centos7-minimal self-installed VM in private Cloudstack. It uses selinux. The error is next:
"target uses selinux but python bindings (libselinux-python) aren't installed".

CentOS7 minimal: http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso

**Comment by siddharthist** [comment]
@bwsw Can you see if https://github.com/CiscoCloud/mantl/pull/1250 fixes your issue?
