### ISSUE TITLE
Hardcode consul_dns_domain as ".consul"

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/mantl#1252]
Per discussion on #1246, to simplify our configuration we're going to remove `consul_dns_domain`. This won't have a huge effect on users, as everyone should pretty much be using `.consul`. #1246 makes it possible to leave off the TLD, however, so even users who did customize should move to the new setting.

**Comment by siddharthist** [comment]
As @stevendborrelli said on #1273,
> I think with the new mantl-dns settings in dnsmasq, we don't even need to use .consul at all. Maybe the better plan is to remove it entirely.

We should be able to do lookups like:
hostname
hostname.node
hostname.node.dc

servicename.service
servicename.service.dc
