### ISSUE TITLE
Calico role

### ISSUE THREAD

**Issue by shethchintan7** [CiscoCloud/mantl#1266]
I have installed latest MANTL on bare-metal ( Centos 7.2), I added etcd and calico to their respective roles to install them. Even though the ansible script ran successfully, when I am passing a marathon job with CALICO_IP and CALICO_PROFILE none of them are actually getting applied to the docker container.

I am concerned about this in the calico role,
 "DOCKER_HOST": "localhost:2377" is passed as --executor-variables to mesos.

The executor_environment_variables file is copied to /etc/mesos-slave/executor_environment_variables and mesos-slave service is restarted, but there is no mesos-slave service running on workers it is renamed to mesos-agent and it is not fetching any arguments from /etc/mesos-slave

Secondly, even if DOCKER_HOST is passed as localhost:2377 how would that and "-H unix:///var/run/docker.sock" interact?

**Comment by lguminski** [comment]
"-H unix:///var/run/docker.sock" overrides DOCKER_HOST settings. There is a Mesos issue for that:
https://issues.apache.org/jira/browse/MESOS-3821

There is also a related problem with powerstrip (#1317)

**Comment by siddharthist** [comment]
@Zogg Is this relevant after #1133?

**Comment by Zogg** [comment]
Nope.
