### ISSUE TITLE
Dynamic inventory for ansible

### ISSUE THREAD

**Issue by heckdevice** [CiscoCloud/mantl#1274]
Env Details:

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.10
- Git commit hash or branch:  master
- Cloud Environment: OpenStack
- Terraform version (`terraform version`): 0.6.11

Is there a way to dump the terraform states as a ansible inventory file?

**Comment by lowwalker** [comment]
I found this - https://github.com/adammck/terraform-inventory

Is there a reason that you can't use plugins/inventroy/terraform.py --hostfile ?

**Comment by heckdevice** [comment]
I tried the above before i posted as that doesn't seem to work. 

Basically i am trying to deploy openshift via its' ansible playbook and it needs inventory file to be statically available and the above plugin didn't solve the problem.

I tried with terraform.py plugin and that also doesn't seem to work with https://github.com/openshift/openshift-ansible/playbook/byo  on branch openshift-ansible-3.0.35-1

Though if i could dump the ansible inventory file generated via terraform.py i could make it work with the above playbook

**Comment by lowwalker** [comment]
So I think you'd want to open an issue on that repo with guidance on how to use a dynamic inventory there. I don't advise trying to use your terraform from Mantl, things would likely be stomped on imo.

**Comment by stevendborrelli** [comment]
@heckdevice you probably want to take a look at the bare metal instructions for creating an inventory file https://github.com/CiscoCloud/mantl/tree/master/docs/bare-metal#creating-your-inventory

**Comment by heckdevice** [comment]
@stevendborrelli @lowwalker  Thanks for the input. I will live for now with manual inventory files, but it would be a nice feature to have as it gives a faster integration with more playbook
