### ISSUE TITLE
inconsistent names between /etc/hosts, Route53

### ISSUE THREAD

**Issue by darKoram** [CiscoCloud/mantl#1277]
In route 53, we have -00n-
k2b2-mantl-worker-001.node.insights.ai

In /etc/hosts
```
10.1.1.79  k2b2-mantl-worker-01
```

in terraform/aws/route53/main.tf
```
resource "aws_route53_record" "dns-worker" {
  count = "${var.worker_count}"
  zone_id = "${var.hosted_zone_id}"
  name = "${var.short_name}-worker-${format("%03d", count.index+1)}.node.${var.domain}"
  records = ["${element(split(",", var.worker_ips), count.index)}"]
  type = "A"
  ttl = 60
}
```

in terraform/aws/instance/main.tf
```
  tags {
    Name = "${var.short_name}-${var.role}-${format("%02d", count.index+1)}"
    sshUser = "${var.ssh_username}"
    role = "${var.role}"
    dc = "${var.datacenter}"
  }
```

This is confusing, for example, when I went to generate letsencrypt certs, it worked for control and edge nodes, but not workers.  Hard to notice that extra 0 injected into the route53 records.

- Ansible version ansible 1.9.4
- Python version Python 2.7.11 :: Anaconda 2.3.0 (x86_64)
- Git commit hash or branch: 9f48dc2876ddc3b5d2f6dd661f0be1a2f3d719fb
- Cloud Environment: aws
- Terraform version Terraform v0.6.3

I'd be happy to put together a PR if you can tell me which format you prefer.

**Comment by siddharthist** [comment]
@darKoram We prefer the `worker-001` format. Thanks for catching this! That's pretty nasty.
