### ISSUE TITLE
old version of /etc/dnsmasq.d/10-consul exists post upgrade of 1.0.3 -> 1.1

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/mantl#1292]
- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.6
- Git commit hash or branch: master
- Cloud Environment: gce
- Terraform version (`terraform version`): v0.6.11

Example of /etc/dnsmasq.d/10-consul on GCE after upgrade from 1.0.3 to 1.1 (master)

```
#Listen on all interfaces
interface=*

addn-hosts=/etc/hosts

# Never forward addresses in the non-routed address spaces.
bogus-priv

server=8.8.8.8
server=8.8.4.4

# configure DNS resolution to consul servers
server=/consul/127.0.0.1#8600

server=/consul/10.0.0.4#8600

server=/consul/10.0.0.6#8600

server=/consul/10.0.0.7#8600


server=/c.asteris-mi.internal/169.254.169.254
```

It should be the version installed by mantl-dns: https://github.com/asteris-llc/mantl-packaging/blob/master/mantl/mantl-dns/10-consul

**Comment by ryane** [comment]
@BrianHicks any thoughts on the best way to handle this? should we just move `10-consul` out of the way before updating mantl-dns as part an upgrade? Or is this something that could be handled in the package itself?

**Comment by BrianHicks** [comment]
The package could handle it, conceivably, but it would probably be better to handle it in the playbook for a smooth transition. Ansible used to control this, so Ansible should relinquish control.

For debugging purposes, if the file isn't removed yum will create `/etc/dnsmasq.d/10-consul.rpmnew`
