### ISSUE TITLE
Terraform vsphere support

### ISSUE THREAD

**Issue by nitgithub** [CiscoCloud/mantl#1295]
Hi there, 

I'm currently trying to deploy a mantl cluster on vsphere (ESXi 6.0) with terraform. There are two different terraform vsphere provider (default one shiped with terraform and mkuzmin/terraform-vsphere, which is also mentioned in docs/getting_started/vsphere.rst).
I'm unable to deploy the stock vsphere.sample.tf with any of them.

For example, terraform/vsphere/main.tf uses
`image = "${var.template}"`
which is only understood by mkuzmin/terraform-vsphere and 
`disk {
    size = "${var.control_volume_size}"
  }`
which is only understood by the default vsphere provider.
Also the mkuzmin/terraform-vsphere provider does not understand the 
`custom_configuration_parameters` settings.
With some modifications to terraform/vsphere/main.tf I was able to deploy a mantl cluster with the default vsphere provider. It seems that it first was developed against the mkuzmin/terraform-vsphere provider and later against the shipped terraform vsphere provider.
Could someone clarify on this please? Anyone else having troubles using mantl with vsphere terraform provider?

Errors with the mkuzmin/terraform-vsphere provider:
> invalid or unknown key: custom_configuration_parameters
> invalid or unknown key: disk

Errors with the shipped vsphere provider (after renaming `vcenter_server` to `vsphere_server`):
> "network_interface": required field is not set
> "vcpu": required field is not set
> invalid or unknown key: image
> invalid or unknown key: cpus
> invalid or unknown key: host

- Ansible version (`ansible --version`): ansible 1.9.4
- Python version (`python --version`): Python 2.7.10
- Git commit hash or branch: master
- Cloud Environment: vsphere
- Terraform version (`terraform version`): Terraform v0.6.12

**Comment by siddharthist** [comment]
@nitgithub If you've found a solution using the default vsphere provider, we'd appreciate a PR!

**Comment by nitgithub** [comment]
#1297

**Comment by siddharthist** [comment]
Clsed in #1297
