### ISSUE TITLE
K8s kubectl command setup after cluster installation

### ISSUE THREAD

**Issue by zoza1982** [CiscoCloud/mantl#1301]
@BrianHicks @Zogg 

I saw you guys are working on k8's a lot recently,
I was wondering if you need PR for getting kubectl command to work after fresh cluster install.

**I noticed  after fresh install kubectl command needs pointing to config file in order to get it working.**
And most users do not know this...

As we don't know whether you Centos username will be be "centos" or "cloud-user" or just "root" 

I have idea for PR which is ready and it would  have a script in /etc/profile.d/kubectl-setup.sh

Script would just do 

```
if [ ! -f ~/.kube/config ]; 
        then 
        mkdir -p ~/.kube && cp /etc/kubernetes/kubectl.kubeconfig ~/.kube/config
fi
```

Test and working !

Want me to open up PR on this?

**Comment by BrianHicks** [comment]
That path doesn't exist on my deployment. What else would it have to do? I did add something that will generate the kubectl on the control nodes (yet to be pushed as well)

**Comment by zoza1982** [comment]
Which path are you referring? ~/.kube ?

Yes that's the point.... It will be created by the code above and put necessary filename in place which kubectl looks by default.

**Comment by zoza1982** [comment]
Nothing else is needed. That's everything. Just that script in profile.d and problem solved.

**Comment by BrianHicks** [comment]
I should have been more specific: `/etc/kubernetes/kubectl.kubeconfig` doesn't exist. Where is that coming from?

**Comment by zoza1982** [comment]
That comes after you perform fresh install on current K8's code from the master.
specifically from https://github.com/CiscoCloud/mantl/blob/master/roles/k8s-master/templates/kubectl.kubeconfig.j2

**Comment by zoza1982** [comment]
@BrianHicks  Thats weird, file has alway been there....my recent fresh install was 2 hours ago. Not sure how you are not seeing it.

**Comment by BrianHicks** [comment]
I've cherry-picked a lot from other branches, that's probably it. I've got functionality that does the same thing in the PR that I'm about to open. Thanks for opening the issue. :D

**Comment by zoza1982** [comment]
Saw it...yup ...basically does the same thing, except setting custom context.
Cool you can close this one.

I am glad we are working on K8's again.

Cheers

Z

**Comment by BrianHicks** [comment]
I'm going to go ahead and close this. The code is now in #1330. Thanks again, @zoza1982!
