### ISSUE TITLE
DigitalOcean private networking

### ISSUE THREAD

**Issue by googoid** [CiscoCloud/mantl#1314]
Hi folks,

Just curious if the support for DigitalOcean private networking is coming in near releases?

I tried to do it on my own, just added `private-networking = true` in `terraform/digitalocean/hosts/main.yml` and set `ipv4_address_private` instead of `ipv4_address` in inventory plugin but unfortunately consul went crazy on the infrastructure, it was constantly loosing leadership and random nodes. I rechecked also iptables but no luck so far.

Deployment was ok though, that's why I'm not providing versions of software used

Thanks in advance!

**Comment by siddharthist** [comment]
@googoid We have discussed it, but not conclusively. See #758 for tracking.

**Comment by googoid** [comment]
@siddharthist thanks for the reply, I managed to set it up and it worked surprisingly well.
I used the same approach as I provided earlier. There must be a thing that I screwed up when trying that previously.

Cheers
