### ISSUE TITLE
unable to deploy mantl with dockerfile and gce.tf 

### ISSUE THREAD

**Issue by sravanikoilada** [CiscoCloud/mantl#1316]
when i run the container with the Dockerfile  with cmd: docker run -it -v ~/.ssh/:/ssh/ -v $PWD:/state mi
on ubuntu os and the  state file as gce.tf file

![screenshot from 2016-04-04 15 35 17](https://cloud.githubusercontent.com/assets/17757395/14244975/df8b391c-fa7b-11e5-8f89-7752ce785e03.png)

**Comment by siddharthist** [comment]
@sravanikoilada Can you please post the following info?
- Docker version
- Git commit hash or branch

**Comment by sravanikoilada** [comment]
@siddharthist 
The info of docker
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

**Comment by siddharthist** [comment]
@sravanikoilada I wonder if this is a terraform version issue, now that I'm looking at the Dockerfile. Can you try updating the `TERRAFORM_VERSION` variable in your Dockerfile? Try 0.6.12 and 0.6.14.

**Comment by sravanikoilada** [comment]
![screenshot from 2016-04-06 12 09 45](https://cloud.githubusercontent.com/assets/17757395/14308091/657c9838-fbf1-11e5-91a5-ef340562ec70.png)
@siddharthist yeah. I was already using latest version 0.6.14 and if I manually delete all the instances and disk spaces in gce, i was able to run it... but now i am getting another issue that is 
dial tcp 104.197.105.81:22: getsockopt: no route to host

**Comment by siddharthist** [comment]
@sravanikoilada The second error looks like a network connectivity issue, is that possible?

**Comment by stevendborrelli** [comment]
Isn't this a known GCE issue with terraform?

**Comment by siddharthist** [comment]
Could be https://github.com/hashicorp/terraform/issues/2850

**Comment by siddharthist** [comment]
@sravanikoilada Did you ever find out what was happening? Have you been able to get a sucessful deployment?

**Comment by sravanikoilada** [comment]
@siddharthist  i was able to deploy all the applications afterwards....but i was unsuccessful in launching the applications ui....must be some problem with dns...i can't exactly trace out..

**Comment by siddharthist** [comment]
Closing, please reopen (or open another issue, or find us on Gitter) if you're still having problems!
