### ISSUE TITLE
Failing at NOTIFIED: [handlers | reload consul]  during ansible run.

### ISSUE THREAD

**Issue by distributorofpain** [CiscoCloud/mantl#1320]
ansible 1.9.5
Python 2.7.5
Git: Master ( current )
Bare Metal ( technically vmware workstation, but will be going to bare metal )
Terraform v0.6.14
CentOS 7 1511
All VMs are brand new builds from the 1511 DVD with minimal.
Ran ansible-playbook -i hosts playbooks/upgrade-packages.yml prior to run ( i did have to adjust my ansible hosts file a few times due to the bare metal install.  Also added provider variable to mantl.yml file which was copied from the sample.yml ( per instructions ).

> NOTIFIED: [handlers | reload consul] ******************************************
> failed: [MASTER1] => {"changed": true, "cmd": ["systemctl", "reload", "consul"], "delta": "0:00:00.045212", "end": "2016-04-05 02:13:58.736355", "rc": 1, "start": "2016-04-05 02:13:58.691143", "warnings": []}
> stderr: Job for consul.service invalid.
> failed: [MASTER2] => {"changed": true, "cmd": ["systemctl", "reload", "consul"], "delta": "0:00:00.040084", "end": "2016-04-05 02:13:58.737157", "rc": 1, "start": "2016-04-05 02:13:58.697073", "warnings": []}
> stderr: Job for consul.service invalid.
> failed: [EDGE1] => {"changed": true, "cmd": ["systemctl", "reload", "consul"], "delta": "0:00:00.026002", "end": "2016-04-05 02:13:58.784835", "rc": 1, "start": "2016-04-05 02:13:58.758833", "warnings": []}
> stderr: Job for consul.service invalid.

Consul.Service
```
[Unit]
Description=Consul is a tool for service discovery and configuration.
Documentation=https://consul.io
After=network-online.target
Wants=network-online.target
After=rsyslog.service
Wants=rsyslog.service

[Service]
User=consul
Group=consul
EnvironmentFile=/etc/sysconfig/consul
ExecStart=/usr/bin/consul agent -config-dir=${CONFIG_DIR} -data-dir=${DATA_DIR} $EXTRA_OPTS
ExecReload=-/bin/kill -HUP $MAINPID
KillSignal=SIGINT
LimitNOFILE=65536
Restart=on-success
IgnoreSIGPIPE=yes

[Install]
WantedBy=multi-user.target
```
[errors_in_messages_log.txt]

Attached is the message log from server AGENT1
(https://github.com/CiscoCloud/mantl/files/203724/errors_in_messages_log.txt)

ansible hosts file
```
[role=control]
MASTER1 private_ipv4=192.168.1.51
MASTER2 private_ipv4=192.168.1.52
MASTER3 private_ipv4=192.168.1.53

[role=worker]
AGENT1 private_ipv4=192.168.1.61
AGENT2 private_ipv4=192.168.1.62
AGENT3 private_ipv4=192.168.1.63

[role=edge]
EDGE1 private_ipv4=192.168.1.56 public_ipv4=192.168.1.59

[dc=ORL]
MASTER1
MASTER2
MASTER3
AGENT1
AGENT2
AGENT3
EDGE1
```

**Comment by distributorofpain** [comment]
I restored the servers being installed back to clean state and stared the deployment again.  This time, this is where it stopped:

> fatal: [MASTER3] => {'msg': 'AnsibleError: Failed to template {% for host in groups[consul_servers_group] | intersect(groups[consul_dc_group]) %}"{{ hostvars[host].private_ipv4 }}"{% if not loop.last %}, {% endif %}{% endfor %}: Unable t
o look up a name or access an attribute in template string. Make sure your variable name does not contain invalid characters like \'-\'.', 'failed': True}
fatal: [MASTER3] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': 'AnsibleError: Failed to template {% for host in groups[consul_servers_group] | intersect(groups[consul_dc_group]) %}"{{ hostv
ars[host].private_ipv4 }}"{% if not loop.last %}, {% endif %}{% endfor %}: Unable to look up a name or access an attribute in template string. Make sure your variable name does not contain invalid characters like \'-\'.', 'failed': True}
]}

So i ran the deployment again after this set of error messages and wound up with the same error message originally posted above.  Message log looks the same as well.  So perhaps this other message that occurs before the one i originally posted can shed some light on what happened.

**Comment by lowstz** [comment]
@distributorofpain You can retry bare metal installation use this inventory example
 ```
[role=control]
MASTER1 private_ipv4=192.168.1.51 ansible_ssh_host=192.168.1.51
MASTER2 private_ipv4=192.168.1.52 ansible_ssh_host=192.168.1.52
MASTER3 private_ipv4=192.168.1.53 ansible_ssh_host=192.168.1.53

[role=control:vars]
role=control

[role=worker]
AGENT1 private_ipv4=192.168.1.61 ansible_ssh_host=192.168.1.61
AGENT2 private_ipv4=192.168.1.62 ansible_ssh_host=192.168.1.62
AGENT3 private_ipv4=192.168.1.63 ansible_ssh_host=192.168.1.63

[role=worker:vars]
role=worker

[role=edge]
EDGE1 private_ipv4=192.168.1.56 ansible_ssh_host=192.168.1.56

[role=edge:vars]
role=edge

[dc=ORL]
MASTER1
MASTER2
MASTER3
AGENT1
AGENT2
AGENT3
EDGE1
```

**Comment by kbroughton** [comment]
Is there a reason you are using a static hosts file for ansible rather than the dynamic inventory supplied in plugins/inventory/terraform.py
After `terraform apply` I run the following and it works fine:
ansible-playbook -e @security.yml mantl.yml

You are going to be missing some terraform generated variables I believe with your static file.

**Comment by distributorofpain** [comment]
@lowstz I tried adding those items to the manual hosts file and reran the software deployment, but got a the same result.

> NOTIFIED: [handlers | reload consul] ******************************************
failed: [MASTER1] => {"changed": true, "cmd": ["systemctl", "reload", "consul"], "delta": "0:00:00.036619", "end": "2016-04-05 16:27:30.394553", "rc": 1, "start": "2016-04-05 16:27:30.357934", "warnings": []}
stderr: Job for consul.service invalid.

i did not restore the VMs to prebuild(clean) state before running time, just tried to restart deployment.

**Comment by distributorofpain** [comment]
@kbroughton After reading the docs and looking for the bare metal terraform templates, then reading posts of folks who ran bare metal installs, i figured i didnt need terraform for what i was doing.  I am new to terraform, so i need to better understand how it works.

If i run the /plugins/inventory/terraform.py --hostfile /mantl/mantl-master/hosts (which is the ansible hosts file i created and used during install ) it just errors.  The documents dont say anything about bare metal requirements.  So in the end i was little lost as what direction i should go with it.  Since it seemed to only generate a file used, i figured the manual anisible host file would be enough...

**Comment by siddharthist** [comment]
@distributorofpain Just wanted to make sure you saw the [bare-metal docs](http://docs.mantl.io/en/latest/getting_started/bare-metal.html?highlight=bare%20metal).

**Comment by distributorofpain** [comment]
@siddharthist wow, i had saw mention of bare-metal docs, but i could only find the ones on a different github fork, but they didnt go to the level mentioned there!

I would like to use terraform to deploy to physical hosts(when i bring up my dev test with some old   rack).  This should be a good guide for that.

The question i have here:  at the bottom, it talks about LVM variables, are those needed for VMs as well?  What is that doing?

**Comment by siddharthist** [comment]
@distributorofpain You won't need to/can't use terraform with physical hosts. The LVM role adds logical volumes for managing data, especially that created by Docker. Please post back here if those docs don't work for you!

**Comment by distributorofpain** [comment]
So i ran the deployment again with these varibles:

ansible-playbook -i hosts \
        -e provider=bare-metal \
        -e consul_dc=ORL \
        -e docker-lvm-backed=true \
        -e docker_lvm_data_volume_size="80%FREE" \
        -e @security.yml sample.yml >& bare-metal.log

Same result...  ( i left it as sample.yml because the only thing i had modified in the mantl.yml file was adding the provider which is provided with the switches above.

I did not reset my test servers back to fresh OS installs..

**Comment by siddharthist** [comment]
@distributorofpain It's possible that you'll need to reset your servers, can you try that and then following along those docs from the start?

**Comment by distributorofpain** [comment]
yea, this is what snapshots are for :)

**Comment by distributorofpain** [comment]
Seems i didnt read that document all the way... LVM is explained lol , so my bad.  Running fresh deployment now, fingers crossed.

**Comment by distributorofpain** [comment]
Followed the bare metal docs and it made it further, but still died.

TASK: [consul | create secure acl] ********************************************
failed: [MASTER1] => {"changed": true, "cmd": ["consul-cli", "acl-update", "--token=0e2eaa89-d815-4526-ae7e-b4b1df885327", "--name=Mantl Secure Token", "--rule=key:secure:write", "--rule=service::write", "6e5f354d-4a1c-4b6f-b2db-6cdb468504ae"], "delta": "0:00:00.022014", "end": "2016-04-05 22:02:00.737365", "rc": 1, "start": "2016-04-05 22:02:00.715351", "warnings": []}
stderr: Unexpected response code: 500 (No path to datacenter)

FATAL: all hosts have already failed -- aborting

strange that it only failed on one host(at least thats the only server listed in the error message), but then says all have failed.

**Comment by distributorofpain** [comment]
#684 states that i should comment out the consul_acl_datacenter in the sample.yml, but its already commented out in the default sample.yml.

This is what i have in place and am running:

[role=control]
MASTER1 private_ipv4=192.168.1.51 ansible_ssh_host=192.168.1.51
MASTER2 private_ipv4=192.168.1.52 ansible_ssh_host=192.168.1.52
MASTER3 private_ipv4=192.168.1.53 ansible_ssh_host=192.168.1.53

[role=control:vars]
consul_is_server=true
lvm_physical_device=/dev/sdb1

[role=worker]
AGENT1 private_ipv4=192.168.1.61 ansible_ssh_host=192.168.1.61
AGENT2 private_ipv4=192.168.1.62 ansible_ssh_host=192.168.1.62
AGENT3 private_ipv4=192.168.1.63 ansible_ssh_host=192.168.1.63

[role=worker:vars]
consul_is_server=false
lvm_physical_device=/dev/sdb1

[role=edge]
EDGE1 private_ipv4=192.168.1.56 ansible_ssh_host=192.168.1.56

[role=edge:vars]
consul_is_server=false
lvm_physical_device=/dev/sdb1

[dc=ORL]
MASTER1
MASTER2
MASTER3
AGENT1
AGENT2
AGENT3
EDGE1

---------------------------------------------
Command:

ansible-playbook -i hosts \
        -e provider=bare-metal \
        -e consul_dc=ORL \
        -e docker-lvm-backed=true \
        -e docker_lvm_data_volume_size="80%FREE" \
        -e @security.yml sample.yml >& bare-metal.log

**Comment by distributorofpain** [comment]
So i went deep into the messages log and noticed that sometimes it would refer to the datacenter as "orl" and then other times "ORL".  Being that i have it setup as ORL, i thought well maybe its case sensitive in some areas?  ( i just had this issue with ceph buckets in their latest build )  So i modified the datacenter to be "orl" and updated the command as well.  I then re-ran the deployment( i didnt reset the environment though) and it finished, no errors.  I have the UI now and everything is green.

I do keep seeing this in the message log(but everything is working):
Apr  6 03:35:55 MASTER1 docker/8c65612f2e3b[8809]: 2016/04/06 03:35:55 [WARN] ("key(config/mantl/auth)") Consul returned no data (does the path exist?)
Apr  6 03:35:56 MASTER1 docker/8c65612f2e3b[8809]: 2016/04/06 03:35:56 [WARN] ("key(config/mantl/consul_ssl)") Consul returned no data (does the path exist?)
Apr  6 03:35:56 MASTER1 docker/8c65612f2e3b[8809]: 2016/04/06 03:35:56 [WARN] ("key(config/mantlui/ssl)") Consul returned no data (does the path exist?)
Apr  6 03:35:58 MASTER1 docker/8c65612f2e3b[8809]: 2016/04/06 03:35:58 [WARN] ("key(config/mantlui/ssl_ciphers)") Consul returned no data (does the path exist?)
Apr  6 03:36:55 MASTER1 docker/8c65612f2e3b[8809]: 2016/04/06 03:36:55 [WARN] ("key(config/mantl/auth)") Consul returned no data (does the path exist?)
Apr  6 03:36:58 MASTER1 docker/8c65612f2e3b[8809]: 2016/04/06 03:36:58 [WARN] ("key(config/mantl/consul_ssl)") Consul returned no data (does the path exist?)
Apr  6 03:36:59 MASTER1 docker/8c65612f2e3b[8809]: 2016/04/06 03:36:59 [WARN] ("key(config/mantlui/ssl)") Consul returned no data (does the path exist?)
Apr  6 03:37:01 MASTER1 docker/8c65612f2e3b[8809]: 2016/04/06 03:37:01 [WARN] ("key(config/mantlui/ssl_ciphers)") Consul returned no data (does the path exist?)
Apr  6 03:37:06 MASTER1 collectd[60385]: Unhandled python exception in read callback: TypeError: float() argument must be a string or a number

So i think in the interest of "testing", i am going to take a snapshot, then restore the older snapshot and rerun the software deployment with the lowercase "orl" as the datacenter name to see if thats what it was.

**Comment by siddharthist** [comment]
@distributorofpain Awesome. If it turns out to be a datacenter name case issue, please post an issue that outlines the problems that you see because of that, and we'll try to diagnose and fix that! Thanks for your debugging!

**Comment by distributorofpain** [comment]
@siddharthist Thanks for the assist and the docs!

Just a note, when i browse around using the main getting started page, i cant seem to see how to navigate to the bare-metal area.  If i go into the code pages, i can find it.  Not sure if this is by design(not wanting to push bare-metal installs) or an oversight during updates..  but i thought i would mention it.

**Comment by distributorofpain** [comment]
Environmental rebuild complete, no issues this time.  It was definitely the uppercase.  I will open an issue in a bit.

**Comment by siddharthist** [comment]
I'm going to close this, since it seems like your deployment worked! Please open two new issues about:
 1. The log warnings
 2. The datacenter case issue
Thanks again for the debugging @distributorofpain :grin:
