### ISSUE TITLE
Task common | enable EPEL repo fail on bare metal installation

### ISSUE THREAD

**Issue by veacks** [CiscoCloud/mantl#1321]
Hi,

Ansible is failing on the task : enable EPEL repo

Giving the same issue for each nodes:

    failed: [control-03] => {"changed": false, "failed": true, "rc": 1, "results": []}
    msg: 

     One of the configured repositories failed (Unknown),
     and yum doesn't have enough cached data to continue. At this point the only
     safe thing yum can do is fail. There are a few ways to work "fix" this:

         1. Contact the upstream for the repository and get them to fix the problem.

         2. Reconfigure the baseurl/etc. for the repository, to point to a working
            upstream. This is most often useful if you are using a newer
            distribution release than is supported by the repository (and the
            packages for the previous distribution release still work).

         3. Disable the repository, so yum won't use it by default. Yum will then
            just ignore the repository until you permanently enable it again or use
            --enablerepo for temporary usage:

                yum-config-manager --disable <repoid>

         4. Configure the failing repository to be skipped, if it is unavailable.
            Note that yum will try to contact the repo. when it runs most commands,
            so will have to try and fail each time (and thus. yum will be be much
            slower). If it is a very temporary problem though, this is often a nice
            compromise:

                yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

    Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try agai

I have tried to add the EPL repo, but it's already installed:

    ansible all -i hosts -u pwarnes -a "rpm -ivh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm" --sudo --ask-sudo-pass

    control-03 | FAILED | rc=1 >>
    Retrieving http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
    Preparing...                          ########################################warning: /var/tmp/rpm-tmp.6YWVe2: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
        package epel-release-7-5.noarch is already installed

I don't know if it is related but Ansible was failing previously on the task __increase timeouts in YUM__

    failed: [edge-02] => (item={'option': 'timeout', 'value': 60.0}) => {"changed": true, "cmd": "yum-config-manager --save --setopt timeout=60.0", "delta": "0:00:00.005637", "end": "2016-04-05 14:30:27.527741", "item": {"option": "timeout", "value": 60.0}, "rc": 127, "start": "2016-04-05 14:30:27.522104", "warnings": []}
stderr: /bin/sh: yum-config-manager: command not found

As work around, I have installed manually yum-utils `ansible all -i hosts -u pwarnes -m yum -a "name=yum-utils state=latest" --sudo --ask-sudo-pass` as described here: https://github.com/CiscoCloud/mantl/pull/1285

I'd love to know if you have any work around for that one.
Thanks.

- Ansible version (`ansible --version`): ansible 1.9.5
- Python version (`python --version`): Python 2.7.5
- Git commit hash or branch: release 1.0.3 (latest)
- Cloud Environment: VirtualBox 2xEdge, 3xControl and 3xWorker (not vagrant, i'm testing locally on my mac the installation before asking my ICT to provide me each servers)
- Terraform version (`terraform version`): v0.6.9 (but not used for bar-metal install)

I'm using the minimal Cenos7 image: CentOS-7-x86_64-Minimal-1511.iso (which is the same as the vagrant.json in the packer file).

**Comment by siddharthist** [comment]
@veacks This has been fixed since 1.0.3: https://github.com/CiscoCloud/mantl/commit/e0d1e5b15e1347f991c9288aebbd696ba9575000. Thanks for pointing it out!

**Comment by veacks** [comment]
Hi @siddharthist,

In fact, the VMs needed to be pre provisioned with Packer first with some components used in your Vagrant image.

In my packer I have run the `ansible.sh`, the `rolling-upgrade-packages.yml` playbook and the `cleanup.sh`.

Now the bare-metal provision works well... until "consul wait for leader".

Thanks for your time.

**Comment by drauschenbach** [comment]
This fix is in master but not the 1.0.3 tag.
