### ISSUE TITLE
Install yum-utils in common role

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1323]
See #1244 and #1321. We require yum-utils to increase timeouts, but it might not be installed on all hosts.

**Comment by ChrisAubuchon** [comment]
That's already in `roles/common/tasks/main.yml`:
https://github.com/CiscoCloud/mantl/blob/master/roles/common/tasks/main.yml#L21-L27

**Comment by siddharthist** [comment]
I wonder why it's not working for folks. Is it because it's missing `state: present` perhaps?

**Comment by ChrisAubuchon** [comment]
Not on the latest master? The commit that added it was merged 18 days ago. The PR that you're looking at https://github.com/CiscoCloud/mantl/pull/1244 is 28 days old.

**Comment by siddharthist** [comment]
Fixed in https://github.com/CiscoCloud/mantl/commit/e0d1e5b15e1347f991c9288aebbd696ba9575000
