### ISSUE TITLE
Error in getting started guide

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1324]
As @distributorofpain pointed out, the tables of contents are messed up!

I'm looking here:
![screenshot1](https://cloud.githubusercontent.com/assets/4294323/14305548/45bc7772-fb72-11e5-8934-65fcd48b49ed.jpg)

and

![screenshot](https://cloud.githubusercontent.com/assets/4294323/14305564/7c9f2488-fb72-11e5-8d8b-a6343b28fdfb.jpg)

**Comment by ryane** [comment]
Where are you seeing the malformed toc? 

It looks ok to me: http://docs.mantl.io/en/latest/getting_started/index.html#preparing-to-provision-cloud-hosts
