### ISSUE TITLE
Consul update to 0.6.4

### ISSUE THREAD

**Issue by AndriiOmelianenko** [CiscoCloud/mantl#1328]
Hi,
Is it planned to update consul from 0.6.3 to 0.6.4 ?
https://github.com/hashicorp/consul/releases/tag/v0.6.4

**Comment by siddharthist** [comment]
There's no reason not to! Looks like the only major difference is with prepared queries, which we don't use.

**Comment by siddharthist** [comment]
@AndriiOmelianenko package PR is in https://github.com/asteris-llc/mantl-packaging/pull/70. We'd love a hand reviewing/testing, either that package or when the PR is in on this repo!

**Comment by stevendborrelli** [comment]
Consul has been updated on bintray. https://bintray.com/asteris/mantl-rpm/consul/0.6.4-1/view#files

**Comment by siddharthist** [comment]
It still isn't default in Mantl: https://github.com/CiscoCloud/mantl/blob/master/roles/consul/defaults/main.yml#L2

**Comment by stevendborrelli** [comment]
See PR #1384

**Comment by ryane** [comment]
fixed by #1384
