### ISSUE TITLE
Required variable kube_worker_ips is not set

### ISSUE THREAD

**Issue by joe1chen** [CiscoCloud/mantl#1329]
- Ansible version (`ansible --version`): 1.9.5
- Python version (`python --version`): 2.7.10
- Git commit hash or branch: 6185f119b95c4984dcf5fbd8fb41ea95823041de
- Cloud Environment: AWS and Cloudflare for DNS
- Terraform version (`terraform version`): 0.6.14

I had mantl up and running on master with the revision just before the kubernetes changes were merged in.  Now, when trying to run ```terraform apply```I'm getting the error:
```
* module root: module dns: required variable kube_worker_ips not set
```

It looks like the ```terraform/cloudflare/main.tf``` now requires a ```kube_worker_ips``` to be passed in even if I don't have any kubernetes workers.  Also, it will try to create cloudflare records for ```dns-kube-worker``` if I pass in something for ```kube_worker_ips```.

Maybe this needs to be refactored out of the general Cloudflare DNS terraform.  There should be a ```k8-main.tf``` or something that you could include if you want DNS settings for kubernetes.

**Comment by siddharthist** [comment]
cc @BrianHicks @Zogg

**Comment by siddharthist** [comment]
@joe1chen We're turning on Kubernetes by default soon, so that's why those are in the default Terraform configs. That variable shouldn't be required if you have an K8S workers, though, this is probably a bug.

**Comment by joe1chen** [comment]
I guess currently it is a bug then since the ```kube_worker_ips``` does not have a default value defined.  However, even if I added a ```{ default = "" }``` to get around the error, terraform is going to try to create a ```dns-kube-worker``` record with a blank value then. Not sure how ```cloudflare_record``` would handle the blank string.

**Comment by BrianHicks** [comment]
Sorry you've been bitten by this @joe1chen, we try to keep backwards compatibility but looks like we haven't this time. @siddharthist is right that it's a bug. You should be able to set the variable to an empty string to avoid creating records. We'll try and set this (or something else reasonable) by default in 1.1.

**Comment by BrianHicks** [comment]
ah ha, we were commenting at the same time. If `kube_worker_count` is set to 0, it shouldn't create any records.

**Comment by joe1chen** [comment]
Thanks for the quick responses.  BTW, we're looking forward to testing out the Kubernetes integration so keep up the good work.

**Comment by BrianHicks** [comment]
Well your timing is just right, I could sure use someone to test out PR #1330 if you're interested. There be dragons there, though, and you may want to wait if you're wanting a production K8s cluster from that branch.
