### ISSUE TITLE
Changing CA Certificate after installation

### ISSUE THREAD

**Issue by veacks** [CiscoCloud/mantl#1352]
Hi,

I'd like to know if there is an easy way to change the Self Signed certificate provided by the security script  to CA Certificate on Mantl after provisioning of the servers?

We would like tu put in place the infrastructure but we are not sure yet of the domain and subdomain names.

I have found a part of my answer in the Documentation:
http://docs.mantl.io/en/latest/security/security_setup.html

    In the event that you need to regenerate a certificate, rename or delete the appropriate CSR and certificate from the certs folder and the private component in private and re-run security-setup.

But after that, Is it safe to re-run my main playbook (let say sample.yml) to install this new certificate on my servers? Or should I update them with a custom playbook ?

Thanks

**Comment by siddharthist** [comment]
You can definitely generate new certificates after installing, distribute them to your nodes with Ansible, and restart Consul. You'll want to use a rolling restart on Consul, so there's not a quorum issue. 

If you replace the certificates in `ssl/` and rerun `sample.yml`, it should work. If it doesn't, that's a bug.

The relevant code is here: https://github.com/CiscoCloud/mantl/blob/7265de1037fad0bacde01233c32406e14be18e3d/roles/common/tasks/ssl.yml

**Comment by veacks** [comment]
Hi @siddharthist,

We have made our choice for the domain name and get our certificates, so I won't need to try it anymore.

Thank you for your answer, I'll keep it in mind if need to change the certificate.
I'm closing the issue.
