### ISSUE TITLE
unable to view the web page of application on marathon in mantl

### ISSUE THREAD

**Issue by sravanikoilada** [CiscoCloud/mantl#1353]
hi all,

- Ansible version (`ansible --version`): 1.9.5
- Python version (`python --version`): 2.7.6
- Cloud Environment: gce
- Terraform version (`terraform version`):v0.6.14
-using centos

  I am able to launch the applications on marathon over mesos...but i am not able to access the web page of application
![screenshot from 2016-04-15 18 57 22](https://cloud.githubusercontent.com/assets/17757395/14562903/ecafed1c-033c-11e6-85f7-1c009b90da6d.png)
![screenshot from 2016-04-15 18 57 36](https://cloud.githubusercontent.com/assets/17757395/14562918/f74f9a10-033c-11e6-85a9-728d12f638cc.png)
![screenshot from 2016-04-15 18 57 45](https://cloud.githubusercontent.com/assets/17757395/14562926/fcfcd586-033c-11e6-9795-3c0f221aca68.png)

**Comment by ryane** [comment]
What version of Marathon are you running? Right now, we are on version 0.13.0; we haven't done any testing of the UI of newer versions yet...

**Comment by ryane** [comment]
I'm going to close this for now. Please re-open if you are still having issues.
