### ISSUE TITLE
traefik upgrade

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/mantl#1354]
Update to a more recent release of traefik with better support for 

* frontend rules
* let's encrypt
* ability to set ExposedByDefault for marathon apps
* versioned package (1.0.0-beta.xxxx, for example)
* etc.

**Comment by rastaman** [comment]
Yes please, i didn't even know what is the version of traefik shipped with mantl, is it the one mentionned here https://github.com/asteris-llc/mantl-packaging/blob/master/packages/traefik/spec.yml ? I would like to know to find the relevant documentation,
Best regards

**Comment by stevendborrelli** [comment]
@rastaman as soon as this PR goes in, we'll merge the newer version of traefik in mantl-packaging and get it pushed to the repos. Right now the default behavior has changed, which means that if you do a `yum upgrade` traefik will turn off all traffic unless you have a label to enable it.

**Comment by stevendborrelli** [comment]
Traefik is updated to 1.0.0-beta.475. Let's close this ticket and if we need to add more features (Like LetsEncrypt) we can have separate issues.
