### ISSUE TITLE
Constrain one Elasticsearch task per worker node

### ISSUE THREAD

**Issue by metalseargolid** [CiscoCloud/mantl#1356]
Is there a way to configure Elasticsearch as installed via the ELK addon to enforce one ES instance per worker node when scaling up? For example, when I scale the ES instances from 3 to 5, I want the ES instances to be spun up on workers 4 and 5 rather than workers 1, 2, or 3, which already have ES tasks running on them.

**Comment by ryane** [comment]
good question. On my cluster, I'm actually seeing the tasks get spread across hosts and if I try to run more ES instances than I have worker nodes, I see declined offers in the scheduler logs with a reason like `Host already running task`. I am not seeing two ES executor instances running on any single worker. That doesn't mean there is not a scenario where it can't happen, though. But I think this might be a better question for the framework developers - they should have a better answer for you.

Do you mind asking this over here: https://github.com/mesos/elasticsearch? And, if it does turn out there is something we need to add to facilitate this, let us know.

**Comment by metalseargolid** [comment]
No problem, I'll ask this over there and ping back if i get a favorable response

**Comment by metalseargolid** [comment]
Opened the issue here: https://github.com/mesos/elasticsearch/issues/556
