### ISSUE TITLE
Mantl Kubernetes - kube workers  - help is appreciated

### ISSUE THREAD

**Issue by andreijs** [CiscoCloud/mantl#1362]
Hey guys,

I am trying to spin up a vagrant cluster with kubernetes and kube worker I added the kube worker to the vagrant file.

I have a few questions.

How do I call the kubernetes api from my host 

I tried curl -k -u 'user:pass' https://192.168.100.101:6443/api/v1/nodes
I get Unauthorized

if I ssh into the control box and run: 

 curl http://127.0.0.1:8085/api/v1/nodes
{
  "kind": "NodeList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/nodes",
    "resourceVersion": "630"
  },
  "items": []

It's not seeing my worker ...

Any help would be appreciate it. I am trying to wrap my head around this. Also is kube-ui available ? Where ?
```
➜  mantl (master) ✗ vagrant hosts list
No vagrant-config.yml found, using defaults
192.168.100.101 control-01
192.168.100.151 kubeworker-001
192.168.100.201 worker-001
```

- Ansible version (`ansible --version`): ansible 1.9.2
- Python version (`python --version`): 2.7.9
- Git commit hash or branch: cf6835bc301567e89893b10ceabc5bcc6b9a7950
- Cloud Environment:  Vagrant DC
- Terraform version (`terraform version`): Terraform v0.6.14

**Comment by siddharthist** [comment]
@andreijs Can you post your modified Vagrantfile? If you get one working with K8S workers, we'd love to see it! And as of today, the K8S dashboard should be visible in Mantl UI.

**Comment by andreijs** [comment]
@siddharthist I will do a PR I just wanted to get it going also I have a quick question, kube_worker_* vs kubeworker_* I found some discrepancies with the code there I think there should be consensus on one.

**Comment by andreijs** [comment]
@siddharthist here is the PR https://github.com/CiscoCloud/mantl/pull/1365

**Comment by siddharthist** [comment]
Closing as duplicated in #1366. @BrianHicks @Zogg any opinions on the convention of `kube_worker` vs `kubeworker`? Maybe we can create another issue to iron out that inconsistency.
