### ISSUE TITLE
Offering a VM appliance for evaluation

### ISSUE THREAD

**Issue by moretea** [CiscoCloud/mantl#1375]
Hi there,

For the purpose of getting mantl in the hands of people who would like to evaluate it, it would make sense to offer something like a VirtualBox appliance. I believe that when a potential user looks at mantl, (s)he should not be exposed to 'details' like running ansible to provision the machines.

(S)he should be able to just import the applicance, start the VM's and have mantl working within seconds.

I've managed to set mantl up within Vagrant/virtualbox, but it took more effort than a quick look should require. Just importing a working VM appliance would ensure that people have a positive first impression of mantle.

Finally, I suggest that you would package this appliance on during CI, you could perform some tests to make sure that everything works before releasing the applicance as an artifact somewhere. This is probably a bit tricky, since AFAIK, VirtualBox cannot be run on Travis workers.

**Comment by siddharthist** [comment]
@moretea The fundamental issue is that Vagrant dynamically configures your Mantl setup. We can't know in advance which IP addresses will be available for use by VMs, for instance. We build images with all Ansible steps that don't depend on some custom configuration. 

Was there any additional work other than just running `vagrant up`? If so, that's a bug!

**Comment by siddharthist** [comment]
Closing this, please let us know if you can think of a better way to provide images that would work around the problem of dynamic configuration.

**Comment by moretea** [comment]
Ah, yes. I meant that you'd have a preconfigured pre-determined mantl cluster as an appliance.
The pain point is that running ansible in vagrant takes ages, whereas importing an applicance takes less than one minute.
