### ISSUE TITLE
dnsmasq search configuration

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/mantl#1377]
- Ansible version (`ansible --version`): n/a
- Python version (`python --version`): n/a
- Git commit hash or branch: master
- Cloud Environment: aws
- Terraform version (`terraform version`): n/a

The dnsmasq configuration needs to be updated so that search paths are properly respected. See #1367 for a detailed discussion.

**Comment by stevendborrelli** [comment]
With #1367 closed, what needs to be done for this issue?

**Comment by ryane** [comment]
we need a new mantl-dns package that fixes the search config. The manual fix @BrianHicks figured out was to use the --domain='#'` option and consolidate /etc/resolv.conf.masq and /etc/resolv.conf.mantl-dns into a single file. I realized we don't have an issue open in the packing repo so I just created https://github.com/asteris-llc/mantl-packaging/issues/84

**Comment by ryane** [comment]
pending https://github.com/asteris-llc/mantl-packaging/pull/89

**Comment by ryane** [comment]
https://github.com/asteris-llc/mantl-packaging/pull/89 is merged and seems to fix the problem:

gce

```
$ cat /etc/resolv.conf
# this config installed by mantl-dns

# search is added here so that the system can address nodes by their simplest
# name (x.node.consul becomes x.node or simply x.) This will work for service
# addressing as well, so you can use y.service instead of y.service.consul
options ndots:2
search node.consul consul c.asteris-mi.internal. google.internal. c.asteris-mi.internal
```

aws

```
$ cat /etc/resolv.conf
# this config installed by mantl-dns

# search is added here so that the system can address nodes by their simplest
# name (x.node.consul becomes x.node or simply x.) This will work for service
# addressing as well, so you can use y.service instead of y.service.consul
options ndots:2
search node.consul consul ec2.internal
```
