### ISSUE TITLE
Ansible playbook fails with undefined variable error:  zookeeper_server_group on worker nodes

### ISSUE THREAD

**Issue by kernel528** [CiscoCloud/mantl#1387]
Attempting to deploy a fresh Mantl cluster into an Openstack environment.  Getting this error for each of the worker nodes.  This worked previously as of 3/10/16 deployment against v1.0.3.

Ansible Version:  1.9.6
Python Version:  2.7.10
Terraform Version:  0.6.13
Git commit hash:  ad761e6782b5ce46e6a4fc92afd0d966cfe2eab9
Cloud Environment:  Openstack

Error:
TASK: [mesos | enable nginx-mesos-leader] *************************************
skipping: [mantl-cluster-worker-001]
skipping: [mantl-cluster-worker-002]
skipping: [mantl-cluster-worker-003]
skipping: [mantl-cluster-worker-004]
skipping: [mantl-cluster-worker-005]

TASK: [mesos | install follower configuration] ********************************
ok: [mantl-cluster-worker-004]
ok: [mantl-cluster-worker-001]
ok: [mantl-cluster-worker-003]
ok: [mantl-cluster-worker-005]
ok: [mantl-cluster-worker-002]

TASK: [mesos | configure mesos-agent] *****************************************
fatal: [mantl-cluster-worker-001] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_server_group' is undefined", 'failed': True}
fatal: [mantl-cluster-worker-001] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_server_group' is undefined", 'failed': True}

fatal: [mantl-cluster-worker-003] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_server_group' is undefined", 'failed': True}
fatal: [mantl-cluster-worker-003] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_server_group' is undefined", 'failed': True}
fatal: [mantl-cluster-worker-004] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_server_group' is undefined", 'failed': True}
fatal: [mantl-cluster-worker-004] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_server_group' is undefined", 'failed': True}
fatal: [mantl-cluster-worker-002] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_server_group' is undefined", 'failed': True}
fatal: [mantl-cluster-worker-002] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_server_group' is undefined", 'failed': True}
fatal: [mantl-cluster-worker-005] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_server_group' is undefined", 'failed': True}
fatal: [mantl-cluster-worker-005] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'zookeeper_server_group' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting

**Comment by stevendborrelli** [comment]
Could you please add the `zookeeper_server_group`  var to your `role=worker` stanza in your main .yml file? :

```
- hosts: role=worker
  # role=worker hosts are a subset of "all". Since we already gathered facts on
  # all servers, we can skip it here to speed up the deployment.
  gather_facts: no
  vars:
    mesos_mode: follower
    zookeeper_server_group: role=control
  roles:
    - mesos
```

**Comment by kernel528** [comment]
My apologies for delayed reply.  Had issues with client system and was delayed in retrying.  Thanks for the assistance.  Added the above and worked fine.
