### ISSUE TITLE
Failed  : AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'role'

### ISSUE THREAD

**Issue by angry-tony** [CiscoCloud/mantl#1389]
trying to install Mantl with Calico on bare-metal environment.
 
    Instruction URL : 
    [](https://github.com/CiscoCloud/mantl/tree/master/roles/calico)
    [](https://github.com/CiscoCloud/mantl/blob/master/docs/getting_started/bare-metal.rst)

But getting this error for the worker node.

- Ansible version (`ansible --version`): 1.9.1
- Python version (`python --version`): 2.7.5
- Git commit hash or branch: master
- Cloud Environment: bare-metal
- Terraform version (`terraform version`):

Error
```
TASK: [calico | set calico environment] *************************************** 
fatal: [worker-01] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'role'", 'failed': True}

msg:
AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'role'
fatal: [worker-01] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'role'", 'failed': True}

msg:
AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'role'

FATAL: all hosts have already failed -- aborting
```

**Comment by angry-tony** [comment]
solution : change your inventory file. add 'role' like below
..
[role=worker]
worker-01 private_ipv4=172.16.0.31 ansible_ssh_host=172.16.0.31 role=worker
..
[role=kubeworker]
kubernetesworker-01 private_ipv4=172.16.0.41 ansible_ssh_host=172.16.0.41 role=kubeworker
..

**Comment by siddharthist** [comment]
@angry-tony Glad it worked out for you! Let us know if you run into anything else. Does that line need to be added in the bare metal docs?

**Comment by angry-tony** [comment]
Hi. there

the error is solved but i am getting another error that the state of calico
and zookeepr is failed.



## error log


2016-05-03 10:02:53,151 p=25709 u=root |  TASK: [calico | enable and start
calico] **************************************
2016-05-03 10:02:59,266 p=25709 u=root |  failed: [worker-01] => {"failed":
true}
2016-05-03 10:02:59,266 p=25709 u=root |  msg: Job for calico.service
failed because the control process exited with error code. See "systemctl
status calico.service" and "journalctl -xe" for details.

2016-05-03 10:02:59,266 p=25709 u=root |  FATAL: all hosts have already
failed -- aborting



[root@worker-01 ~]# vi /var/log/messages
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.782604 10219
slave.cpp:190] Slave started on 1)@172.16.0.31:5051
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.782611 10219
slave.cpp:191] Flags at startup: --appc_store_dir="/tmp/mesos/store/appc"
--authenticatee="crammd5" --cgroups_cpu_enable_pids_and_tids_count="false"
--cgroups_enable_cfs="false" --cgroups_hierarchy="/sys/fs/cgroup"
--cgroups_limit_swap="false" --cgroups_root="mesos"
--container_disk_watch_interval="15secs" --containerizers="mesos"
--default_role="*" --disk_watch_interval="1mins" --docker="docker"
--docker_kill_orphans="true" --docker_remove_delay="6hrs"
--docker_socket="/var/run/docker.sock" --docker_stop_timeout="0ns"
--enforce_container_disk_quota="false"
--executor_registration_timeout="1mins"
--executor_shutdown_grace_period="5secs"
--fetcher_cache_dir="/tmp/mesos/fetch" --fetcher_cache_size="2GB"
--firewall_rules="" --frameworks_home="" --gc_delay="1weeks"
--gc_disk_headroom="0.1" --hadoop_home="" --help="false"
--hostname_lookup="true" --image_provisioner_backend="copy"
--initialize_driver_logging="true" --isolation="posix/cpu,posix/mem"
--launcher_dir="/usr/libexec/mesos" --logbufsecs="0" --logging_level="INFO"
--master="zk://localhost:2181/mesos"
--oversubscribed_resources_interval="15secs" --perf_duration="10secs"
--perf_interval="1mins" --port="5051" --qos_correction_interval_min="0ns"
--quiet="false" --recover="reconnect" --recovery_timeout="15mins"
--registration_backoff_factor="1secs"
--resource_monitoring_interval="1secs" --revocable_cpu_low_priority="true"
--sandbox_directory="/mnt/mesos/sandbox" --strict="true"
--switch_user="true" --systemd_runtime_directory="/run/systemd/system"
--version="false" --work_dir="/var/lib/mesos"
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.783929 10219
slave.cpp:354] Slave resources: cpus(*):1; mem(*):748; disk(*):46054;
ports(*):[31000-32000]
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.783996 10219
slave.cpp:390] Slave hostname: worker-01
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.784003 10219
slave.cpp:395] Slave checkpoint: true
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.784728 10220
state.cpp:54] Recovering state from '/var/lib/mesos/meta'
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,784:10219(0x7fd92758c700):ZOO_INFO@log_env@712: Client
environment:zookeeper.version=zookeeper C client 3.4.5
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,784:10219(0x7fd92758c700):ZOO_INFO@log_env@716: Client environment:
host.name=worker-01
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,784:10219(0x7fd92758c700):ZOO_INFO@log_env@723: Client environment:
os.name=Linux
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,784:10219(0x7fd92758c700):ZOO_INFO@log_env@724: Client
environment:os.arch=3.10.0-327.13.1.el7.x86_64
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,784:10219(0x7fd92758c700):ZOO_INFO@log_env@725: Client
environment:os.version=#1 SMP Thu Mar 31 16:04:38 UTC 2016
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,784:10219(0x7fd92758c700):ZOO_INFO@log_env@733: Client environment:
user.name=(null)
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,784:10219(0x7fd92758c700):ZOO_INFO@log_env@741: Client
environment:user.home=/root
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,784:10219(0x7fd92758c700):ZOO_INFO@log_env@753: Client
environment:user.dir=/
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,784:10219(0x7fd92758c700):ZOO_INFO@zookeeper_init@786: Initiating
client connection, host=localhost:2181 sessionTimeout=10000
watcher=0x7fd92ea28160 sessionId=0 sessionPasswd=<null>
context=0x7fd91c003c20 flags=0
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.785173 10221
status_update_manager.cpp:202] Recovering status update manager
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.785203 10221
containerizer.cpp:386] Recovering containerizer
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.785979 10221
slave.cpp:4110] Finished recovery
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,786:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(Connection refused):
server refused to accept the client
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03
01:01:34,786:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(Connection refused):
server refused to accept the client


[root@worker-01 ~]# echo "stat" | nc zookeeper.service 2181
Ncat: Could not resolve hostname "zookeeper.service": Name or service not
known. QUITTING.


[root@worker-01 ~]# systemctl status calico.service
● calico.service - calico
   Loaded: loaded (/usr/lib/systemd/system/calico.service; enabled; vendor
preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue
2016-05-03 01:41:28 UTC; 11s ago
  Process: 32319 ExecStart=/usr/bin/calicoctl node --ip=172.16.0.31
--node-image=calico/node:v0.9.0 (code=exited, status=1/FAILURE)
  Process: 32312 ExecStartPre=/usr/bin/docker rm -f calico-node
(code=exited, status=1/FAILURE)

May 03 01:41:28 worker-01 systemd[1]: calico.service: control process
exited, code=exited status=1
May 03 01:41:28 worker-01 systemd[1]: Failed to start calico.
May 03 01:41:28 worker-01 systemd[1]: Unit calico.service entered failed
state.
May 03 01:41:28 worker-01 systemd[1]: calico.service failed.

[root@worker-01 ~]# journalctl -xe
May 03 01:41:23 worker-01 mesos-slave[10219]: 2016-05-03
01:41:23,673:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:23 worker-01 mesos-slave[10219]: 2016-05-03
01:41:23,673:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:27 worker-01 mesos-slave[10219]: 2016-05-03
01:41:27,010:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:27 worker-01 mesos-slave[10219]: 2016-05-03
01:41:27,010:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:28 worker-01 systemd[1]: calico.service holdoff time over,
scheduling restart.
May 03 01:41:28 worker-01 systemd[1]: Starting calico...
-- Subject: Unit calico.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit calico.service has begun starting up.
May 03 01:41:28 worker-01 docker[4493]:
time="2016-05-03T01:41:28.664115211Z" level=error msg="Handler for DELETE
/v1.23/containers/calico-node returned error: No such container: ca
May 03 01:41:28 worker-01 docker[32312]: Error response from daemon: No
such container: calico-node
May 03 01:41:28 worker-01 calicoctl[32319]: ERROR: Could not enable ipv4
forwarding.
May 03 01:41:28 worker-01 systemd[1]: calico.service: control process
exited, code=exited status=1
May 03 01:41:28 worker-01 systemd[1]: Failed to start calico.
-- Subject: Unit calico.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit calico.service has failed.
-- 
-- The result is failed.
May 03 01:41:28 worker-01 systemd[1]: Unit calico.service entered failed
state.
May 03 01:41:28 worker-01 systemd[1]: calico.service failed.
May 03 01:41:30 worker-01 mesos-slave[10219]: 2016-05-03
01:41:30,347:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:30 worker-01 mesos-slave[10219]: 2016-05-03
01:41:30,347:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:33 worker-01 mesos-slave[10219]: 2016-05-03
01:41:33,684:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:33 worker-01 mesos-slave[10219]: 2016-05-03
01:41:33,684:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:35 worker-01 mesos-slave[10219]: I0503 01:41:35.157562 10221
slave.cpp:3926] Current disk usage 3.69%. Max allowed age:
6.041984322026297days
May 03 01:41:37 worker-01 mesos-slave[10219]: 2016-05-03
01:41:37,021:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:37 worker-01 mesos-slave[10219]: 2016-05-03
01:41:37,021:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:40 worker-01 mesos-slave[10219]: 2016-05-03
01:41:40,357:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:40 worker-01 mesos-slave[10219]: 2016-05-03
01:41:40,358:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:43 worker-01 mesos-slave[10219]: 2016-05-03
01:41:43,695:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:43 worker-01 mesos-slave[10219]: 2016-05-03
01:41:43,695:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:47 worker-01 mesos-slave[10219]: 2016-05-03
01:41:47,031:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:47 worker-01 mesos-slave[10219]: 2016-05-03
01:41:47,031:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697:
Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
lines 1504-1541/1541 (END)


[root@control-01 ~]# echo "stat" | nc zookeeper.service 2181
Ncat: Could not resolve hostname "zookeeper.service": Name or service not
known. QUITTING.

[root@control-01 ~]# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
    PID/Program name
tcp        0      0 0.0.0.0:2379            0.0.0.0:*               LISTEN
     9103/etcd
tcp        0      0 0.0.0.0:2380            0.0.0.0:*               LISTEN
     9103/etcd
tcp        0      0 0.0.0.0:8300            0.0.0.0:*               LISTEN
     7447/consul
tcp        0      0 0.0.0.0:8301            0.0.0.0:*               LISTEN
     7447/consul
tcp        0      0 0.0.0.0:8302            0.0.0.0:*               LISTEN
     7447/consul
tcp        0      0 127.0.0.1:8400          0.0.0.0:*               LISTEN
     7447/consul
tcp        0      0 172.16.0.21:8500        0.0.0.0:*               LISTEN
     9050/nginx: master
tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN
     7447/consul
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN
     10168/dnsmasq
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
     466/sshd
tcp        0      0 127.0.0.1:8600          0.0.0.0:*               LISTEN
     7447/consul
tcp        0      0 0.0.0.0:153             0.0.0.0:*               LISTEN
     9340/docker-proxy
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN
     740/master

2016-05-03 9:03 GMT+09:00 Langston Barrett <notifications@github.com>:

**Comment by siddharthist** [comment]
I'm going to close this, let's continue the conversation on #1402
