### ISSUE TITLE
Kubernetes examples

### ISSUE THREAD

**Issue by andreimc** [CiscoCloud/mantl#1400]
Hey guys,

I am just wondering if it's worth adding k8s example to the example folder ?

Regards
Andrei

**Comment by siddharthist** [comment]
@andreimc That's a good idea! What kind of examples would you like to see?

**Comment by andreimc** [comment]
@siddharthist I am thinking the examples that are currently there for Marathon ? I think they cover things quite well in most scenarios.

**Comment by siddharthist** [comment]
This is currently blocked by #1429

**Comment by siddharthist** [comment]
Unblocked!
