### ISSUE TITLE
msg: Job for calico.service failed in worker-01

### ISSUE THREAD

**Issue by angry-tony** [CiscoCloud/mantl#1402]
- Ansible version (`ansible --version`): 1.9.6
- Python version (`python --version`): 2.7.5
- Git commit hash or branch: master
- Cloud Environment: **bare-metal with calico**
- Terraform version (`terraform version`):

Hi. there

i am getting another error that the state of calico is failed and zookeepr does not start.

## error log
```
2016-05-03 10:02:53,151 p=25709 u=root |  TASK: [calico | enable and start calico] ************************************** 
2016-05-03 10:02:59,266 p=25709 u=root |  failed: [worker-01] => {"failed": true}
2016-05-03 10:02:59,266 p=25709 u=root |  msg: Job for calico.service failed because the control process exited with error code. See "systemctl status calico.service" and "journalctl -xe" for details.

2016-05-03 10:02:59,266 p=25709 u=root |  FATAL: all hosts have already failed -- aborting
```

```
**[root@worker-01 ~]# vi /var/log/messages**
status_update_manager.cpp:202] Recovering status update manager
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.785203 10221 containerizer.cpp:386] Recovering containerizer
May  3 01:01:34 worker-01 mesos-slave: I0503 01:01:34.785979 10221 slave.cpp:4110] Finished recovery
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03 01:01:34,786:10219(0x7fd922b70700):**ZOO_ERROR@handle_socket_error_msg@1697: Socket [127.0.0.1:2181] zk retcode=-4, errno=111(Connection refused): server refused to accept the client**
May  3 01:01:34 worker-01 mesos-slave: 2016-05-03 01:01:34,786:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697: Socket [127.0.0.1:2181] zk retcode=-4, errno=111(Connection refused): server refused to accept the client
```

```
**[root@worker-01 ~]# echo "stat" | nc zookeeper.service 2181**
Ncat: Could not resolve hostname "zookeeper.service": Name or service not known. QUITTING.
```

```
**[root@worker-01 ~]# systemctl status calico.service**
● calico.service - calico
   Loaded: loaded (/usr/lib/systemd/system/calico.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2016-05-03 01:41:28 UTC; 11s ago
  Process: 32319 ExecStart=/usr/bin/calicoctl node --ip=172.16.0.31 --node-image=calico/node:v0.9.0 (code=exited, status=1/FAILURE)
  Process: 32312 ExecStartPre=/usr/bin/docker rm -f calico-node (code=exited, status=1/FAILURE)

May 03 01:41:28 worker-01 systemd[1]: calico.service: control process exited, code=exited status=1
May 03 01:41:28 worker-01 systemd[1]: Failed to start calico.
May 03 01:41:28 worker-01 systemd[1]: Unit calico.service entered failed state.
May 03 01:41:28 worker-01 systemd[1]: calico.service failed.
```
```
**[root@worker-01 ~]# journalctl -xe**
May 03 01:41:23 worker-01 mesos-slave[10219]: 2016-05-03 01:41:23,673:10219(0x7fd922b70700):**ZOO_ERROR@handle_socket_error_msg@1697: Socket [127.0.0.1:2181] zk retcode=-4, errno=111(**
May 03 01:41:23 worker-01 mesos-slave[10219]: 2016-05-03 01:41:23,673:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697: Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:27 worker-01 mesos-slave[10219]: 2016-05-03 01:41:27,010:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697: Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:27 worker-01 mesos-slave[10219]: 2016-05-03 01:41:27,010:10219(0x7fd922b70700):ZOO_ERROR@handle_socket_error_msg@1697: Socket [127.0.0.1:2181] zk retcode=-4, errno=111(
May 03 01:41:28 worker-01 systemd[1]: calico.service holdoff time over, scheduling restart.
May 03 01:41:28 worker-01 systemd[1]: Starting calico...
May 03 01:41:28 worker-01 docker[4493]: time="2016-05-03T01:41:28.664115211Z" level=error msg="Handler for DELETE /v1.23/containers/calico-node returned error: No such container: ca
May 03 01:41:28 worker-01 docker[32312]: Error response from daemon: No such container: calico-node
May 03 01:41:28 worker-01 calicoctl[32319]: ERROR: Could not enable ipv4 forwarding.
May 03 01:41:28 worker-01 systemd[1]: calico.service: control process exited, code=exited status=1
May 03 01:41:28 worker-01 systemd[1]: Failed to start calico.
-- The result is failed.
```

```
**[root@control-01 ~]# echo "stat" | nc zookeeper.service 2181**
Ncat: Could not resolve hostname "zookeeper.service": Name or service not known. QUITTING.
```
```
**[root@control-01 ~]# netstat -ntlp**
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:2379            0.0.0.0:*               LISTEN      9103/etcd           
tcp        0      0 0.0.0.0:2380            0.0.0.0:*               LISTEN      9103/etcd           
tcp        0      0 0.0.0.0:8300            0.0.0.0:*               LISTEN      7447/consul         
tcp        0      0 0.0.0.0:8301            0.0.0.0:*               LISTEN      7447/consul         
tcp        0      0 0.0.0.0:8302            0.0.0.0:*               LISTEN      7447/consul         
tcp        0      0 127.0.0.1:8400          0.0.0.0:*               LISTEN      7447/consul         
tcp        0      0 172.16.0.21:8500        0.0.0.0:*               LISTEN      9050/nginx: master  
tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN      7447/consul         
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      10168/dnsmasq       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      466/sshd            
tcp        0      0 127.0.0.1:8600          0.0.0.0:*               LISTEN      7447/consul         
tcp        0      0 0.0.0.0:153             0.0.0.0:*               LISTEN      9340/docker-proxy   
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      740/master
```

**Comment by siddharthist** [comment]
@angry-tony Please remember to fill in the Ansible version, Python version, and git commit at the top of your post!

**Comment by stevendborrelli** [comment]
@angry-tony it seems there is a lot broken here. Can you run a `systemctl status -l zookeeper`?

**Comment by angry-tony** [comment]
Yes here is the response

- [ [root@worker-01 ~]# systemctl status -l zookeeper
● zookeeper.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead) ] 


ansible-playbook -u hoho -i inventory \
-e provider=bare-metal \
-e consul_dc=dc1 \
**-e docker_lvm_backed=true \  <-- to avoid "docker-lvm failure", I changed**
-e docker_lvm_data_volume_size="80%FREE" \
-e @security.yml sample.yml >& bare-metal.log

**- my inventory file -**
[root@localhost]~/mantl# cat inventory 
[role=control]
control-01 private_ipv4=172.16.0.21 ansible_ssh_host=172.16.0.21 role=control provider=bare-metal
control-02 private_ipv4=172.16.0.22 ansible_ssh_host=172.16.0.22 role=control provider=bare-metal
control-03 private_ipv4=172.16.0.23 ansible_ssh_host=172.16.0.23 role=control provider=bare-metal

[role=control:vars]
consul_is_server=true
lvm_physical_device=/dev/sdb

[role=worker]
worker-01 private_ipv4=172.16.0.31 ansible_ssh_host=172.16.0.31 role=worker provider=bare-metal

[role=worker:vars]
consul_is_server=false
lvm_physical_device=/dev/sdb

[role=kubeworker]
kubernetesworker-01 private_ipv4=172.16.0.41 ansible_ssh_host=172.16.0.41 role=kubeworker provider=bare-metal

[role=kubeworker:vars]
consul_is_server=false
lvm_physical_device=/dev/sdb

[role=edge]
edge-01 private_ipv4=172.16.0.51 ansible_ssh_host=172.16.0.51 role=edge provider=bare-metal
edge-02 private_ipv4=172.16.0.52 ansible_ssh_host=172.16.0.52 role=edge provider=bare-metal

[role=edge:vars]
consul_is_server=false
lvm_physical_device=/dev/sdb

[dc=dc1]
control-01
control-02
control-03
worker-01
kubernetesworker-01
edge-01
edge-02

**- my sample.yml -** # followed this [Tutorial](https://github.com/CiscoCloud/mantl/blob/master/docs/getting_started/bare-metal.rst)
[root@localhost]~/mantl# cat sample.yml 
---
- include: "{{ playbook_dir }}/playbooks/check-requirements.yml"

- hosts: all
  vars:
    consul_servers_group: role=control
  roles:
    - common
    - lvm
    - docker
    - logrotate
    - consul-template
    - nginx
    - consul
    - etcd
    - dnsmasq

- hosts: role=worker
  gather_facts: no
  vars:
    mesos_mode: follower
    zookeeper_server_group: role=control
  roles:
    - mesos
**    - calico**

- hosts: role=control
  gather_facts: yes
  vars:
    consul_servers_group: role=control
    mesos_leaders_group: role=control
    mesos_mode: leader
    zookeeper_server_group: role=control
  roles:
    - vault
    - zookeeper
    - mesos
    - marathon
    - mantlui
    - kubernetes
    - kubernetes-master
    - kubernetes-addons

- hosts: role=kubeworker
  gather_facts: yes
  vars:
    consul_dns_domain: consul
  roles:
    #- flannel
**    - calico**
    - kubernetes
    - kubernetes-node

- hosts: role=edge
  gather_facts: yes
  vars:
    traefik_marathon_domain: marathon.localhost
  roles:
    - traefik

**Comment by siddharthist** [comment]
@angry-tony Zookeeper isn't installed on worker nodes. Can you post the output of the same command from one of your control nodes?

**Comment by angry-tony** [comment]
here.. Same for 3 control nodes.

[root@control-01 ~]# systemctl status -l zookeeper
● zookeeper.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

**Comment by angry-tony** [comment]
**## - my sample.yml file -**  followed this [Tutorial](https://github.com/CiscoCloud/mantl/tree/master/roles/calico)
[root@localhost] mantl# cat sample.yml
---
# CHECK SECURITY - when customizing you should leave this in. If you
# take it out and forget to specify security.yml, security could be turned off
# on components in your cluster!
- include: "{{ playbook_dir }}/playbooks/check-requirements.yml"

# BASICS - we need every node in the cluster to have common software running to
# increase stability and enable service discovery. You can look at the
# documentation for each of these components in their README file in the
# `roles/` directory, or by checking the online documentation at
# docs.mantl.io.
- hosts: all
  vars:
    # consul_acl_datacenter should be set to the datacenter you want to control
    # Consul ACLs. If you only have one datacenter, set it to that or remove
    # this variable.
    # consul_acl_datacenter: your_primary_datacenter

    consul_servers_group: role=control
  roles:
    - common
    - lvm
    - docker
    - logrotate
    - consul-template
    - nginx
    - consul
    - etcd
    - dnsmasq

# ROLES - after provisioning the software that's common to all hosts, we do
# specialized hosts. This configuration has two major groups: control nodes and
# worker nodes. We provision the worker nodes first so that we don't create any
# race conditions. This could happen in the Mesos components - if there are no
# worker nodes when trying to schedule control software, the deployment process
# would hang.
#
# The worker role itself has a minimal configuration, as it's designed mainly to
# run software that the Mesos leader shedules. It also forwards traffic to
# globally known ports configured through Marathon.
- hosts: role=worker
  # role=worker hosts are a subset of "all". Since we already gathered facts on
  # all servers, we can skip it here to speed up the deployment.
  gather_facts: no
  vars:
    mesos_mode: follower
    zookeeper_server_group: role=control
  roles:
    - mesos
    - calico # <-- add

# the control nodes are necessarily more complex than the worker nodes, and have
# ZooKeeper, Mesos, and Marathon leaders. In addition, they control Vault to
# manage secrets in the cluster. These servers do not run applications by
# themselves, they only schedule work. That said, there should be at least 3 of
# them (and always an odd number) so that ZooKeeper can get and keep a quorum.
- hosts: role=control
  gather_facts: yes
  vars:
    consul_servers_group: role=control
    mesos_leaders_group: role=control
    mesos_mode: leader
    zookeeper_server_group: role=control
  roles:
    - vault
    - zookeeper
    - mesos
    - marathon
    - mantlui
    - kubernetes
    - kubernetes-master
    - kubernetes-addons

- hosts: role=kubeworker
  # role=worker hosts are a subset of "all". Since we already gathered facts on
  # all servers, we can skip it here to speed up the deployment.
  gather_facts: yes
  vars:
    consul_dns_domain: consul
  roles:
    #- flannel	# <-- comment
    - calico	# <-- add
    - kubernetes
    - kubernetes-node

# The edge role exists solely for routing traffic into the cluster. Firewall
# settings should be such that web traffic (ports 80 and 443) is exposed to the
# world.
- hosts: role=edge
  gather_facts: yes
  vars:
    # this is the domain that traefik will match on to do host-based HTTP
    # routing. Set it to a domain you control and add a star domain to route
    # traffic. (EG *.marathon.localhost)
    #
    # For those migrating from haproxy, this variable serves the same purpose
    # and format as `haproxy_domain`.
    traefik_marathon_domain: marathon.localhost
  roles:
    - traefik

**Comment by siddharthist** [comment]
@angry-tony There was probably a failure in the zookeeper task during installation. Can you check higher up in the log for errors, where the zookeeper tasks were run?

**Comment by angry-tony** [comment]
I didnt find out failure log in bare-metal.log.
i guess "Install zookeeper" task did not run..
strange.. this occurred only with calico installation..

'''
TASK: [logrotate | copy component logrotate configurations] ******************* 
ok: [control-03] => (item=['mesos', True])
ok: [control-03] => (item=['docker', True])
ok: [control-03] => (item=['zookeeper', "role == 'control'"])
ok: [control-02] => (item=['mesos', True])
ok: [control-02] => (item=['docker', True])
ok: [control-02] => (item=['zookeeper', "role == 'control'"])
ok: [worker-01] => (item=['mesos', True])
ok: [worker-01] => (item=['docker', True])
ok: [worker-01] => (item=['zookeeper', "role == 'control'"])
ok: [edge-02] => (item=['mesos', True])
ok: [edge-02] => (item=['docker', True])
ok: [edge-02] => (item=['zookeeper', "role == 'control'"])
ok: [kubernetesworker-01] => (item=['mesos', True])
ok: [kubernetesworker-01] => (item=['docker', True])
ok: [kubernetesworker-01] => (item=['zookeeper', "role == 'control'"])
ok: [edge-01] => (item=['mesos', True])
ok: [edge-01] => (item=['docker', True])
ok: [edge-01] => (item=['zookeeper', "role == 'control'"])
ok: [control-01] => (item=['mesos', True])
ok: [control-01] => (item=['docker', True])
ok: [control-01] => (item=['zookeeper', "role == 'control'"])

TASK: [logrotate | create component archives] ********************************* 
ok: [control-03] => (item=['docker', True])
ok: [control-03] => (item=['zookeeper', "role == 'control'"])
ok: [kubernetesworker-01] => (item=['docker', True])
ok: [kubernetesworker-01] => (item=['zookeeper', "role == 'control'"])
ok: [edge-02] => (item=['docker', True])
ok: [edge-02] => (item=['zookeeper', "role == 'control'"])
ok: [edge-01] => (item=['docker', True])
ok: [edge-01] => (item=['zookeeper', "role == 'control'"])
ok: [control-01] => (item=['docker', True])
ok: [control-01] => (item=['zookeeper', "role == 'control'"])
ok: [worker-01] => (item=['docker', True])
ok: [worker-01] => (item=['zookeeper', "role == 'control'"])
ok: [control-02] => (item=['docker', True])
ok: [control-02] => (item=['zookeeper', "role == 'control'"])


TASK: [mesos | wait for zookeeper service to be registered] ******************* 
skipping: [worker-01]

TASK: [mesos | wait for zookeeper to listen] ********************************** 
skipping: [worker-01]

TASK: [mesos | create zookeeper acl] ****************************************** 
skipping: [worker-01]
'''

**Comment by angry-tony** [comment]
solved : enable ipv6
