### ISSUE TITLE
Docker Swarm on top of Mantl

### ISSUE THREAD

**Issue by moretea** [CiscoCloud/mantl#1406]
## Why
I propose that support for Docker Swarm should be added to Mantl.
By having Swarm on Mantl, all the (available) resources on a cluster are exposed via the Docker API directly. Developers are already used to this API / model of working.

Swarm is ideal to run one-time-jobs in production easily. Think about database migrations (which could be run detached), or running some interactive script to generate a report (in which the attached input/output is really usefull).

Finally, Swarm could allow for easy development of microservices on top of Mantl. A developer could write the code for microservices on his local MackBook Air, and use Docker Compose to start a set of microservices via Swarm on top of Mantl, which would use way more memory and CPU than his MacBook Air could provide.

## How
Swarm registers itself as a Mesos framework, uses it to allocate resources and uses the Docker Executor to start containers. So far, so good! However, it also requires access to the Docker API on each worker node to provide services like pulling/pushing of images and showing the logs. At the moment, only the `/var/run/sock` unix domain socket is enabled in Mantl. To expose the Docker API in a secure way, I propose to add a proxy container (just like is done with Consul), to avoid some issues in Swarm [1].
Furthermore, Mesos Framework authentication should be implemented in Swarm [2]. After some investigation, It appears that adding this will take about 100 lines of Go code.
To make sure that a crash of a single Swarm daemon does not take down all containers started via Swarm, Swarm’s high availability option should be used [3]. I suggest that Swarm should run on each Mesos master node, to provide the same level of availability as Mesos itself.

[1] https://github.com/docker/swarm/issues/1089
[2] https://github.com/docker/swarm/issues/1944
[3] https://docs.docker.com/swarm/multi-manager-setup/

**Comment by kbroughton** [comment]
Our contract with developers is a docker-compose file.  This would help a lot in crossing between development (compose) and production (marathon).

**Comment by stevendborrelli** [comment]
I'd love to see swarm running on mantl. Our preference is to be an addon installed locally instead of a framework on top of mesos.

**Comment by moretea** [comment]
@stevendborrelli what do you mean exactly? Swarm on mesos *is* registering itself as a mesos framework. If it would be added to Mantl as a addon, I imagine it would be in a HA setup, with swarm daemons running on the same nodes as the mesos masters.

**Comment by siddharthist** [comment]
After some research, I can't really find any information on integrating Swarm with Mesos's scheduling. Swarm will run jobs separately from Mesos/Marathon (which is fine, just something to be noted). I'll look into setting it up as an addon.

**Comment by siddharthist** [comment]
Here's a crazy thought: Swarm is basically installed by running a Docker container on each control and worker node. Maybe we can start these jobs via Marathon?

**Comment by siddharthist** [comment]
I have done some work on this, but haven't gotten swarm to elect a leader. It seems that it's having trouble connecting to Consul, though when I try the API interactions from the console using curl, they work just fine. 

Branch here: https://github.com/CiscoCloud/mantl/tree/feature/docker-swarm
Error log here: http://pastebin.com/raw/yAisqgfR

**Comment by distributorofpain** [comment]
+1 for THE SWARM

**Comment by lguminski** [comment]
+1

**Comment by siddharthist** [comment]
@distributorofpain @lguminski If either of you has more experience with Swarm and would like to help debug my branch, that'd be greatly apprciated!

**Comment by distributorofpain** [comment]
Would love to help... i am a bit of a newb though, so i cant say i would know where to begin helping...

Being a linux sysops guy, i would think i could help though :)

Top of my head looking at the log file output( this is where my lack of understanding of mantl core setup could get annoying):
1. Does mantl run consul on 8500?  Does it require a certificate to talk to?  I only ask because i see environmental variables like this:  CONSUL_SSL=true   CONSUL_SSL_VERIFY=false
2. I see thats running on 127.0.0.1:8500  If thats in docker, wouldnt you stipulate an outside port?
3. Is that container setup to run on the bridge network?
4. I am assuming you went with the docker container solution mentioned above.....

**Comment by siddharthist** [comment]
@distributorofpain You were dead on with 2 :smile: It's always obvious afterwards, huh? I'm making more progress now. Also, more details on Swarm on Mesos: the help text for swarm has this option:
```
   --cluster-driver, -c "swarm"						cluster driver to use [swarm, mesos-experimental]
```
So I think if Mesos support indeed exists, we don't want to use it (because it's experimental).

**Comment by distributorofpain** [comment]
Second set of eyes thing :)  

I just started playing with docker last week.  I had to setup a registry and client to test it.  I really like docker, i can see why people are running with it.  Heck even mantl brought in kubernetes now :)

 I saw the demo on youtube of docker swarm running on messoshpere, very impressive.  Everyone is really charging forward with this stuff.

**Comment by siddharthist** [comment]
@moretea @distributorofpain @lguminski I put in a PR and would love some feedback!
