### ISSUE TITLE
Duplicated ExecStart= in Docker role

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1426]
It looks like there's a duplicate line in [the Docker role's systemd drop-in](https://github.com/CiscoCloud/mantl/blob/e19688b3c4963116dbf19a4d94b9aca0b4e7bd9b/roles/docker/files/20-ExecStart.conf.j2#L2-3). Is that intentional?

- Ansible version (`ansible --version`): n/a
- Python version (`python --version`): n/a
- Git commit hash or branch: master
- Cloud Environment: n/a
- Terraform version (`terraform version`): n/a

**Comment by ChrisAubuchon** [comment]
The `ExecStart=` line is required to replace the ExecStart directive. 

https://wiki.archlinux.org/index.php/systemd#Drop-in_snippets
https://bugzilla.redhat.com/show_bug.cgi?id=756787#c9

**Comment by stevendborrelli** [comment]
I'm pretty sure that is the pattern we need to follow to override ExecStart.

**Comment by ChrisAubuchon** [comment]
It is

**Comment by siddharthist** [comment]
Sorry, I think I was unclear. Please take a look at the link I posted, there are two copies of ExecStart= in that single file we drop in.

**Comment by ChrisAubuchon** [comment]
I did. It is necessary. Check the links I posted.

**Comment by siddharthist** [comment]
Ah, thanks @ChrisAubuchon!
