### ISSUE TITLE
Exposing kubernetes services is broken

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1429]
I'm trying to follow along with the Kubernetes tutorial (and make us a K8s hello-world example). I've started and exposed a `NodePort` service:
```
[centos@lb0-control-01 ~]$ kubectl get services          
NAME                    CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
[...]
example                 10.254.204.216   nodes         8000/TCP            48s
[...]
```
But I can't access it at either the `CLUSTER-IP` or at the IP addresses of any of my kubeworkers, either inside or outside the cluster. 

Here are the commands I used to create and expose it:
```
kubectl run example --image=nginx
kubectl expose deployment example --type=NodePort --port=8000 --target-port=80
```
There are no logs printed by `kubectl logs`.

Is there something I'm missing? 

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: AWS
- Terraform version (`terraform version`): v0.6.14

**Comment by siddharthist** [comment]
I still cannot get this working. Are we entirely sure that our documented process works? Or maybe it's not specific enough? I still can't connect to any of my NodePort services on any of my kubeworkers.

**Comment by siddharthist** [comment]
From @Zogg's excellent debugging:
> So the problem is in the flannel0-->docker0 network link on the machine that has the pod/container running.
2:39
The SYN from another kubeworker never reaches docker0 interface on the pod host. The pod host's eth0 receives the encapsulated flannel packet, the flannel0 interface receives the properly extracted packet, but after that it does not get into docker0, and it should.

**Comment by siddharthist** [comment]
Brian says that the services _should_ be available at `nodeport.service.consul:publishedPort`.

**Comment by siddharthist** [comment]
After attempting again on a new cluster with all of the above addresses, even after rebooting the hosts, the service still can't be reached.

**Comment by ryane** [comment]
unable to repro this:

```shell
$ kubectl run example --image=nginx
deployment "example" created

$ kubectl expose deployment example --type=NodePort --port=8000 --target-port=80
service "example" exposed

$ kubectl describe svc example
Name:                   example
Namespace:              default
Labels:                 run=example
Selector:               run=example
Type:                   NodePort
IP:                     10.254.65.6
Port:                   <unset> 8000/TCP
NodePort:               <unset> 32685/TCP
Endpoints:              192.168.1.67:80
Session Affinity:       None
No events.
```

from within the cluster:

```shell
$ curl -sI 10.254.65.6:8000 | head -n 1
HTTP/1.1 200 OK

$ curl -sI 192.168.1.67:80 | head -n 1
HTTP/1.1 200 OK

$ curl -sI $HOSTNAME:32685 | head -n 1
HTTP/1.1 200 OK
```

This should work on control and kubeworker nodes but won't work on other node types (see #1728)

Perhaps this was fixed by subsequent k8s changes (i'm testing on the `feature/k8s-aws-cloud-provider` branch)... Or are you still seeing the problem?

**Comment by siddharthist** [comment]
@ryane So there are basically three problems 
 1. Accessing the service at the IP of a k8s node (seems to be fixed)
 2. Accessing the service by a service-discoverable name (still broken?)
 3. Accessing the service from outside the cluster (???)

I'll test today on another cluster and see if this is fixed.

**Comment by siddharthist** [comment]
@ryane I can reproduce what you have above, namely that the service can be reached on its assigned port and IP address inside the cluster. In fact, I can even ping the service from outside the cluster:
```
[root@lb-control-01 ~]# kubectl describe svc example
Name:			example
Namespace:		kube-system
Labels:			run=example
Selector:		run=example
Type:			NodePort
IP:			10.254.60.112
Port:			<unset>	8000/TCP
NodePort:		<unset>	30103/TCP
Endpoints:		192.168.0.130:80
Session Affinity:	None

mantl > ./plugins/inventory/terraform.py --hostfile
## begin hosts generated by terraform.py ##
139.59.137.56   	lb-control-01
139.59.146.173  	lb-control-02
139.59.137.247  	lb-control-03
139.59.153.226  	lb-edge-01
139.59.145.20   	lb-kubeworker-002
139.59.145.247  	lb-kubeworker-001
139.59.145.205  	lb-worker-001
139.59.145.41   	lb-worker-002
## end hosts generated by terraform.py ##

mantl > curl -sI 139.59.145.20:30103
HTTP/1.1 200 OK

mantl > curl -sI 139.59.145.247:30103
HTTP/1.1 200 OK
```
We must have changed something that fixed this. I'm going to close this and create a new issue focusing on service discovery.

**Comment by siddharthist** [comment]
In fact, even using the `NodePort` service now works! :fireworks:
