### ISSUE TITLE
Mantl Questions

### ISSUE THREAD

**Issue by distributorofpain** [CiscoCloud/mantl#1434]
First, thanks to everyone who has helped me so far!!  I have two environments running mantl( one is bare metal and one is DO ).  Both are of course testing environments.  I have some questions, so if you have a moment and can answer just one, that would be greatly appreciated.  Feel free to post links to any previous answers or resources( i dont mind reading up, i just havent found the answer in my searches ).  Feel free to call me out as well :)

1. Where are all the variables(IE Traefik has one)?  Can i use the ones from the component itself during the deployment? Or are the available ones listed in a file somewhere?
2. How can i test traefik with an application ( ie what do i need to do when running the process/service to tell traefik to send traffic to the service?)
3. How do i get other instances of an application already being serviced by traefik to tell traefik to add them to the list of available hosts.
4. Most LBs have health checks to verify an application is functioning properly and redirect traffic to the next host if not, is there a special method of telling traefik this or do i just use the instructions from traefik?
5. Being that consul is everywhere in mantl, is there anything i need to do when building a docker container to ensure that consul sees the new service and lists it in the service directory? ( in mantl )
6. Is there anything else i should be including in docker builds to ensure they are monitored correctly, run correctly, get logged correctly(ie send logs), are made available to other services? ( in mantl )
7. can i add addons to the sample/mantl.yml file so they are deployed during deployment and therefore deployed each time i add an agent server?
8. Do i need to include all machines in the ansible hosts file each time i run a deployment when i am adding another agent server?
9. Are their any tags and/or commands that i should ensure are in applications at launch when dealing with mantl?  IE: Chronos has several, but marathon has one.
10. I noticed mantl isnt supporting auto-scaling by default right now, is there a way to test this using the auto-scale from github?
11. How do i change/update mantl admin password?  Is it possible to add another user( even if this is done via manual scripting ).

**Comment by siddharthist** [comment]
@distributorofpain 

 1. If you're talking about the different variables you can use to customize your installation, each component has a README.rst that says what they all do, which you can find in the ["components" section of the docs](http://docs.mantl.io/en/latest/components/index.html)
 5. If you run your container via Marathon, Consul will automatically register it as a service. This is done with [mesos-consul](https://github.com/CiscoCloud/mesos-consul).
 6. For logging, check out our ELK stack addon
 7. Sure, you can just use an Ansible `include: ` to include them in your mantl.yml
 10. Can you post a link of what you're referencing in this question?
 11. We don't have a solution for this yet, AFAIK.

**Comment by distributorofpain** [comment]
Thanks!  Not sure if your number list is supposed to correspond or the system mangled it?

1. Some of these seem to be lacking in detail or non-existent.  This leads me to question if there are actually any variables at all or if i need to look at the configuration files to see if there is something in them as an example.  For the variables that are stated, i am left wondering where to put those variables( i am assuming the mantl/sample.yml file at this point, which is what i believe i was told when i asked in the glitter chat ).
2. thats awesome...  i had read up on this piece earlier but didnt quite understand the under the hood setup.  What i am unsure of here is that i have a few services running, but they do not appear in the traefik web interface.  Although for kibana, it has a tag for traefik set to false.  So it seems if thats set to false, then they wont appear in traefik?  ( Hence why i dont see them? ).  Is this meant to answer 2-4 ?
3.  Which answer was this applying to?
4.  Was this meant to answer 8?
5.  Which question?
6.  which question?

**Comment by siddharthist** [comment]
@distributorofpain Yeah, it tried to automatically renumber them. I've updated accordingly. 

 One: For most of the variables, you want to set them as "role variables". You may want to read up on Ansible's variable hierarchy on [the Ansible docs page about variables](http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable).

**Comment by distributorofpain** [comment]
updated my responses above, i put them in a code block so it wouldnt change them, but i suppose that didnt work out for the links :(

**Comment by distributorofpain** [comment]
I wasnt able to use include for the elk stack addon, there is already an include in the elk addon, so when you use the include line, it sees it as a second entry and gives an error stating it cant find the checks file ( the error shows that the directory is wrong, it goes up one folder in the main path )

so /mantl/mantl-master/playbooks/check-requirements.yml becomes /mantl/playbooks/check-requirements.yml instead and thus an error is thrown.  

If i remove the include line, it starts no problem.  I just copied the anisble part of the elk.yml role setup into the sample file and ran it instead.

**Comment by siddharthist** [comment]
@distributorofpain Have you been able to find answers to these questions? Do you have any that are still outstanding that you'd like for me to answer?

**Comment by distributorofpain** [comment]
Question 4:  How to setup health checks for apps.  Found their document:  https://mesosphere.github.io/marathon/docs/health-checks.html  Though i wish they would also show interface examples as the json isnt always one to one.  It also seems mantl is behind version wise as their is a forcepullimage checkbox now.  

Question 8:  ?

Question 10:  seems there is another issue/PR working on autoscaling :smile: 

Question 11:  I thought i saw people talking about the autoscale program somewhere...  

Question 12(new):  Is there a way to put a mesos node in maintenance?  When i looked at the reboot script, all it does is set consul in maintenance mode.  Unfortunately, this still allows apps to spin up on nodes as mesos doesnt seem to care what consul is doing.  I tried to run the api call, but mesos wouldnt respond ( i think this is due to the way mantl is secured interface wise as i was getting a reply from nginx ).  Someone suggested stopping it via systemd?

**Comment by siddharthist** [comment]
@distributorofpain 

Four: Yes, Marathon is the way to go. I'll make an issue about upgrading Marathon.

Eight: I don't think so, would you mind trying without including all servers and letting us know how it goes?

Eleven: We don't really have a way to do this right now. 

Twelve: Yes, you should stop the systemd service.

**Comment by distributorofpain** [comment]
**Four:** awesome thanks!

**Eight:** ack! sure....  right now i am playing in DO, so my vm workstation setup is shutdown.  I do have a followup though.  In DO, i am using terraform to deploy.  With terraform, i can simply increase the agent node number and run terraform apply.  Then run the mantl install again.  would there be a way to only target the new node with the script?  ( i have a feeling someone already told me this, but i cant find it in my notes ).

**Eleven:**  Seems its just an app that runs in marathon or a task in chronos, so we could probably implement it in mantl without issues.  Though reading the latest comments/issues, its not ready for primetime :frowning: 

**Twelve:** Duely noted!

**Comment by siddharthist** [comment]
Eight: Ansible has the ability to limit which hosts are affected: http://docs.ansible.com/ansible/intro_patterns.html

**Comment by distributorofpain** [comment]
ok, so it looks like i could --limit the installs to only new machines i add via terraform.  Thats excellent news.  Thanks
