### ISSUE TITLE
Consul error: Unexpected response code: 401 (ACL support disabled)

### ISSUE THREAD

**Issue by erjosito** [CiscoCloud/mantl#1437]
Hi there,

my Ansible playbook is stopping at the Consul ACL configuration with a 401 error.

Here some info of my environment:

- Ansible version (`ansible --version`): 1.9.6
- Python version (`python --version`): 2.7.5
- Git commit hash or branch: 
[root@mantl-buildserver mantl]# more .git/logs/HEAD 
0000000000000000000000000000000000000000 9964707c4e2cf094ca46633c8a5ce5527fb3a7c2 root <root@mantl-buildserver.(none)> 1462810763 -0400	clone: from https://github.com/CiscoCloud/mantl.git
- Cloud Environment: vSphere
- Terraform version (`terraform version`): v0.6.16
- OS:
[root@mantl-worker-003 ~]# rpm --query centos-release
centos-release-7-2.1511.el7.centos.2.10.x86_64

And here the error I am getting:
```
TASK: [consul | create secure acl] ******************************************** 
failed: [mantl-worker-003] => {"changed": true, "cmd": ["consul-cli", "acl-update", "--token=faf47a4e-f50d-485c-960c-ec80d4e1c4fe", "--name=Mantl Secure Token", "--rule=key:secure:write", "--rule=service::write", "a9a1723a-07af-4aac-b2fe-37e44ce048d9"], "delta": "0:00:00.005343", "end": "2016-05-10 22:10:24.942652", "rc": 1, "start": "2016-05-10 22:10:24.937309", "warnings": []}
stderr: Unexpected response code: 401 (ACL support disabled)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
common | install system utilities -------------------------------------- 21.40s
consul | restart consul ------------------------------------------------ 16.38s
docker | install docker-gc ---------------------------------------------- 8.85s
common | enable EPEL repo ----------------------------------------------- 8.21s
docker | install latest device-mapper-libs ------------------------------ 5.73s
handlers | wait for consul to listen ------------------------------------ 5.59s
common | install fail2ban ----------------------------------------------- 5.47s
common | install pip ---------------------------------------------------- 5.42s
common | install cloud-init --------------------------------------------- 5.09s
common | deploy root ca ------------------------------------------------- 2.87s
           to retry, use: --limit @/root/mantl.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=0   
mantl-control-01           : ok=73   changed=13   unreachable=0    failed=1   
mantl-control-02           : ok=73   changed=13   unreachable=0    failed=1   
mantl-control-03           : ok=73   changed=13   unreachable=0    failed=1   
mantl-edge-01              : ok=73   changed=13   unreachable=0    failed=1   
mantl-edge-02              : ok=73   changed=13   unreachable=0    failed=1   
mantl-worker-001           : ok=73   changed=13   unreachable=0    failed=1   
mantl-worker-002           : ok=73   changed=13   unreachable=0    failed=1   
mantl-worker-003           : ok=73   changed=13   unreachable=0    failed=1   
```
Any hint?

Thanks in advance!
Jose

**Comment by siddharthist** [comment]
@erjosito Are you running with security enabled?

**Comment by erjosito** [comment]
@siddharthist Yes, security enabled. But we can close this one, the problem was that I had not set the consul_acl_datacenter variable to dc1 in mantl.yml. RTFM!

Thanks for your answer!

**Comment by davidfic** [comment]
I'm getting this same error. I've tried with cosule_acl_datacenter set to dc1 and I've tried with this variable commented out. The result is 1 of my control nodes fails.

    TASK [consul : create secure acl] **********************************************
    fatal: [mantl-control-03]: FAILED! => {"changed": true, "cmd": ["consul-cli", "acl-update", "--  token=5f8cb12a-81ee-4781-b7ac-4e67b664d2df", "--name=Mantl Secure Token", "-- rule=key:secure:write", "--rule=service::write", "6bc5d212-2d6e-451e-bc61-913d5bb51522"], "delta":  "0:00:00.005203", "end": "2016-06-03 21:42:46.582987", "failed": true, "rc": 1, "start": "2016-06-03  21:42:46.577784", "stderr": "Unexpected response code: 401 (ACL support disabled)", "stdout": "",  "stdout_lines": [], "warnings": []}

    NO MORE HOSTS LEFT *************************************************************

    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=0
    mantl-control-01           : ok=80   changed=10   unreachable=0    failed=0
    mantl-control-02           : ok=80   changed=10   unreachable=0    failed=0
    mantl-control-03           : ok=80   changed=10   unreachable=0    failed=1
    mantl-edge-01              : ok=80   changed=10   unreachable=0    failed=0
    mantl-edge-02              : ok=80   changed=10   unreachable=0    failed=0
    mantl-kubeworker-001       : ok=80   changed=10   unreachable=0    failed=0
    mantl-kubeworker-002       : ok=80   changed=10   unreachable=0    failed=0
    mantl-worker-001           : ok=80   changed=10   unreachable=0    failed=0
    mantl-worker-002           : ok=80   changed=10   unreachable=0    failed=0
    mantl-worker-003           : ok=80   changed=10   unreachable=0    failed=0
    mantl-worker-004           : ok=80   changed=10   unreachable=0    failed=0

    TASK: common : deploy root ca ------------------------------------------ 12.74s
    TASK: common : install system utilities -------------------------------- 10.44s
    TASK: common : enable EPEL repo ----------------------------------------- 9.49s
    TASK: docker : install latest device-mapper-libs ------------------------ 8.63s
    TASK: docker : install docker-gc ---------------------------------------- 8.35s
    TASK: consul : install scripts ------------------------------------------ 6.74s
    TASK: consul : wait for leader ------------------------------------------ 6.10s
    TASK: lvm : install LVM tools ------------------------------------------- 5.79s
    TASK: logrotate : copy component logrotate configurations --------------- 5.76s
    TASK: common : update setuptools and pip -------------------------------- 5.76s

**Comment by davidfic** [comment]
I figured out my error. I needed to keep terraform and ansible variable for datacenter in sync. 

It wasn't clear from the documentation that this was necessary. In the docs it even says you can remove the datacenter line from the playbook, but this results in failures later.
