### ISSUE TITLE
Consul RPC/DNS warning: "RPC request for DC 'consul', no path found"

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1447]
On a healthy build from master, my Consul logs look like this: 
```
May 13 23:53:07 lb0-control-01 consul[18708]: 2016/05/13 23:53:07 [ERR] dns: rpc error: No path to datacenter
May 13 23:53:10 lb0-control-01 consul[18708]: 2016/05/13 23:53:10 [WARN] consul.rpc: RPC request for DC 'consul', no path found
May 13 23:53:10 lb0-control-01 consul[18708]: 2016/05/13 23:53:10 [ERR] dns: rpc error: No path to datacenter
May 13 23:53:10 lb0-control-01 consul[18708]: 2016/05/13 23:53:10 [WARN] consul.rpc: RPC request for DC 'consul', no path found
May 13 23:53:10 lb0-control-01 consul[18708]: 2016/05/13 23:53:10 [ERR] dns: rpc error: No path to datacenter
```
Maybe this is because services are now reachable via `<service-name>.service` and so when we ping `<service-name>.service.consul`, Consul thinks we're asking for the Consul datacenter? If so, this will be resolved by #1252. 

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: aws
- Terraform version (`terraform version`): Terraform v0.6.14

**Comment by ChrisAubuchon** [comment]
What does your `/etc/resolv.conf` look like? I'm wondering if it's trying to look up something like `<service-name>.service.consul.consul` in which case Consul sees the first `consul` as the datacenter.

#1252 only removes the ability to change the consul dns domain. `.consul` will still be there. After that PR you won't be able to change it to something like `<service-name>.service.<dns-name>`.

**Comment by siddharthist** [comment]
```
[centos@lb0-control-01 ~]$ cat /etc/resolv.conf
# this config installed by mantl-dns

# search is added here so that the system can address nodes by their simplest
# name (x.node.consul becomes x.node or simply x.) This will work for service
# addressing as well, so you can use y.service instead of y.service.consul
options ndots:2
search node.consul consul us-west-2.compute.internal
```

**Comment by ChrisAubuchon** [comment]
Can you restart consul with log level DEBUG to see what DNS query is causing the message? I'm building a new cluster to see if I can replicate it.

**Comment by siddharthist** [comment]
Confirmed:
 > Consul is getting `consul.service.consul.consul` and interpreting the first `consul` as the datacenter

**Comment by distributorofpain** [comment]
I see this in my DO setup as well:

```
May 14 05:15:16 mantl-do-nyc2-mcontrol-02 consul: 2016/05/14 05:15:16 [WARN] consul.rpc: RPC request for DC 'consul', no path found
May 14 05:15:16 mantl-do-nyc2-mcontrol-02 consul: 2016/05/14 05:15:16 [ERR] dns: rpc error: No path to datacenter
May 14 05:15:16 mantl-do-nyc2-mcontrol-02 consul: 2016/05/14 05:15:16 [WARN] consul.rpc: RPC request for DC 'consul', no path found
May 14 05:15:16 mantl-do-nyc2-mcontrol-02 consul: 2016/05/14 05:15:16 [ERR] dns: rpc error: No path to datacenter
May 14 05:15:16 mantl-do-nyc2-mcontrol-02 consul: 2016/05/14 05:15:16 [WARN] consul.rpc: RPC request for DC 'consul', no path found
May 14 05:15:16 mantl-do-nyc2-mcontrol-02 consul: 2016/05/14 05:15:16 [ERR] dns: rpc error: No path to datacenter
May 14 05:15:16 mantl-do-nyc2-mcontrol-02 consul: 2016/05/14 05:15:16 [WARN] consul.rpc: RPC request for DC 'consul', no path found
May 14 05:15:16 mantl-do-nyc2-mcontrol-02 consul: 2016/05/14 05:15:16 [ERR] dns: rpc error: No path to datacenter

```

Fresh setup, Centos 7.2 in DO built last week with latest.

**Comment by distributorofpain** [comment]
Not sure if this is related, but i added some worker nodes to my setup in DO.  I just increased the worker count in the terraform tf file, ran terraform plan, then terraform apply.  The additional worker nodes came up, then i ran the  deploy command ( ansible-playbook -e @security.yml sample.yml ) and after that finished with all green, all the new worker nodes wouldnt come into mesos.  There was only one error on all of them, a consul check error:  "service:etcd:2" failing.  "service:etcd1" was fine though.

So i just ran the ansible reboot script and now the control nodes are showing an error in consul: "Service 'marathon' check service:marathon"   This is in the journalctl -u consul log on all of them.

```
May 15 12:12:19 mantl-do-nyc2-mcontrol-01 consul[884]: 2016/05/15 12:12:19 [WARN] agent: http request failed 'http://localhost:8085/healthz': Get http://localhost:8085/healthz: dial tcp [::1]:8085: getsockopt: connection refused
May 15 12:12:19 mantl-do-nyc2-mcontrol-01 consul[884]: 2016/05/15 12:12:19 [WARN] agent: Check 'service:marathon' is now critical
May 15 12:12:29 mantl-do-nyc2-mcontrol-01 consul[884]: 2016/05/15 12:12:29 [WARN] agent: http request failed 'http://localhost:8085/healthz': Get http://localhost:8085/healthz: dial tcp [::1]:8085: getsockopt: connection refused
```

Service check error on worker nodes:
![image](https://cloud.githubusercontent.com/assets/18275482/15273968/1770c6c0-1a76-11e6-8a81-846bb2f7f09c.png)

Service check error on control nodes:
![image](https://cloud.githubusercontent.com/assets/18275482/15273974/44272bbe-1a76-11e6-9b3f-d914feafaa45.png)

I have a service check error on the edge nodes as well ( after reboot ):
![image](https://cloud.githubusercontent.com/assets/18275482/15273977/6a7e0d8c-1a76-11e6-8679-6de5236617ed.png)

**Comment by distributorofpain** [comment]
oh, after reboot, it seems the whole setup collapsed:
![image](https://cloud.githubusercontent.com/assets/18275482/15273985/ac6c0438-1a76-11e6-848d-bf109e4e4bfd.png)

I cant access marathon any more, though mesos is up but there are no slaves/workers listed.

Guess i am going to rebuild it as the devs need it monday...

**Comment by distributorofpain** [comment]
Rebuilt from scratch, same RPC error exists:

```
May 15 16:13:42 mantl-do-nyc2-mcontrol-03 consul[13737]: 2016/05/15 16:13:42 [WARN] consul.rpc: RPC request for DC 'consul', no path found
May 15 16:13:42 mantl-do-nyc2-mcontrol-03 consul[13737]: 2016/05/15 16:13:42 [ERR] dns: rpc error: No path to datacenter

```

**Comment by siddharthist** [comment]
@distributorofpain I don't think increasing your worker count is related to this issue, since it happens on fresh installs.

**Comment by ChrisAubuchon** [comment]
It's not going to go away as long as we have `consul node.consul` in the `/etc/resolv.conf` search order. We might have to consider removing it from resolv.conf...

**Comment by distributorofpain** [comment]
@siddharthist oh of course not, i was just stating what i had been doing.  :)

**Comment by ryane** [comment]
what should the `search` line look like? or should it be removed entirely?

**Comment by ryane** [comment]
I did a quick test on GCE and AWS with `consul node.consul` removed from `/etc/resolv.conf`. This is what the search lines looked like:

GCE:

```
search c.asteris-mi.internal. google.internal.
```

AWS:

```
search ec2.internal
```

Both clusters are healthy with no obvious problems. And, I am not seeing these errors and warnings in the consul logs. Do we have anything that depends on having `consul node.consul` in the search list? Should we build a new version of mantl-dns that does not include `consul node.consul` in the search list?

**Comment by ryane** [comment]
this should be fixed for new clusters with the latest mantl-dns package. upgrades from 1.0.3 should also be ok. but, if you have a cluster that was built from 1.1 RC1, the package upgrade won't fully clean things up. if you are in this situation, you can try a playbook  like https://gist.github.com/ryane/c2fcf308782ea590620bed4635b707d5.
