### ISSUE TITLE
[Mantl 1.1] Kubernetes-dashboard.yml is not being loaded into the /etc/kubernetes/manifests folder for control nodes

### ISSUE THREAD

**Issue by Dacode45** [CiscoCloud/mantl#1455]
The above is why there is no webui for kubernetes. 
None of the .yml files in roles/kubernetes-addons are being loaded into the manifest for control nodes.

- Ansible version (`ansible --version`): 1.9.6
- Python version (`python --version`): 2.7.1
- Git commit hash or branch: master
- Cloud Environment: gce
- Terraform version (`terraform version`): 0.6.16

**Comment by st33v** [comment]
hrm... running into this. is there a workaround?

**Comment by siddharthist** [comment]
This has been changed in #1667. Please reopen if you're still seeing it on latest master.
