### ISSUE TITLE
Traefik Tag

### ISSUE THREAD

**Issue by distributorofpain** [CiscoCloud/mantl#1458]
They dont seem to be working ( according to the traefik site, these should work ):

traefik.backend=foo: assign the application to foo backend
traefik.portIndex=1: register port by index in the application's ports array. Useful when the application exposes multiple ports.
traefik.port=80: register the explicit application port value. Cannot be used alongside traefik.portIndex.
traefik.protocol=https: override the default http protocol
traefik.weight=10: assign this weight to the application
traefik.enable=false: disable this application in Træfɪk
traefik.frontend.rule=Host:test.traefik.io: override the default frontend rule (Default: Host:{containerName}.{domain}).
traefik.frontend.passHostHeader=true: forward client Host header to the backend.
traefik.frontend.entryPoints=http,https: assign this frontend to entry points http and https. Overrides defaultEntryPoints.
traefik.domain=traefik.localhost: override the default domain

I tried traefik.domain with no luck...

- Ansible version (`ansible --version`): 1.9.6
- Python version (`python --version`): 2.7.5
- Git commit hash or branch:  master
- Cloud Environment: Digital Ocean
- Terraform version (`terraform version`): 0.6.14

**Comment by kbroughton** [comment]
Your marathon file should look something like this, with labels a top-level key.

    "labels": {
        "traefik.frontend.rule": "Host",
        "traefik.frontend.value": "test.traefik.io"
    },

To debug add this to /etc/traefik/traefik.toml on both edge nodes
logLevel = "DEBUG"
traefikLogsFile = "/var/log/traefik/traefik.log"
then
sudo systemctl stop traefik (can take a minute)
sudo systemctl start traefik
tail -f /var/log/traefik/traefik.log
watch for errors as you test hitting frontend entrypoints

Can you post your marathon file?

**Comment by distributorofpain** [comment]
Seems i misunderstood what those were for, i applied those labels you mentioned and it works now!

Thanks!
