### ISSUE TITLE
distributive check failing after upgrade to 1.1 (resolv.conf)

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1461]
We have an outdated distributive check that fails when upgrading a 1.0 cluster to 1.1. See https://github.com/asteris-llc/mantl-packaging/pull/95

- Ansible version (`ansible --version`): n/a
- Python version (`python --version`): n/a
- Git commit hash or branch: 1.0 -> 1.1
- Cloud Environment: n/a
- Terraform version (`terraform version`): n/a

**Comment by ryane** [comment]
hm, I cannot reproduce this problem. Can you confirm that you are upgrading a 1.0.3 cluster (built with a 1.0.3 security|mantl.yml) and following all of the steps in https://github.com/CiscoCloud/mantl/blob/master/docs/upgrading/index.rst#upgrading-from-103-to-11?

**Comment by siddharthist** [comment]
Couldn't reproduce it myself!
