### ISSUE TITLE
Should services bind to 0.0.0.0?

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1462]
We have a bunch of services that bind to all interfaces, when it's likely that they are only needed internally (in particular, Docker with TCP enabled, Vault, and etcd). Should any of these be migrated to listening only on an instance's private ip?

**Comment by ChrisAubuchon** [comment]
The vault instances need to be able to connect to each other so "no" for vault.

If we ever move to a multiple-network implementation then vault can be moved to the private network...

**Comment by siddharthist** [comment]
Could they not connect to each other using their private IPs? b/c we don't use a two-network implementation?

**Comment by ChrisAubuchon** [comment]
The only two IPs on the hosts are the public IP and 127.0.0.1. They can't communicate via 127.0.0.1 so it has to be the public IP.
