### ISSUE TITLE
Questions: K8s in production with nginx-consul template and traefik

### ISSUE THREAD

**Issue by andreimc** [CiscoCloud/mantl#1487]
I have a cluster works fine I can spin up containers on k8s.

My questions are:

How do I see the running application via traefik ? Does in register it automatically or I need to do something?

How do I inject a geo redicretion container into the mix, I want my app to redirect to like this:

if you come from New Zealand redirect to nz.example.com, currently doing it via nginx + maxmind.

Would you run this nginx container in k8s ?

Can I disable Marathon mesos and zookeeper from installation?

Does gluster FS work with k8s? I ran it seems to only do stuff on marathon workers.

Regards,
Andrei

**Comment by siddharthist** [comment]
We don't recommend using K8s on Mantl in production yet. We included it [as a "technical preview"](https://github.com/CiscoCloud/mantl/releases/tag/1.1.0) in the 1.1 release. We haven't integrated it with all of the other components, such as Traefik, GlusterFS, and Consul. 

We currently require Mesos as part of the default installation. 

Better integration is in the works for upcoming releases!

**Comment by andreimc** [comment]
@siddharthist thanks for the answer :)
