### ISSUE TITLE
Any updates on Azure deployment.

### ISSUE THREAD

**Issue by andreimc** [CiscoCloud/mantl#1500]
I am looking at an azure deployment at the end of June, I am just wondering if any progress has been made on this #1269.

I know terraform is lacking support for Azure loadbalancer is a deployment possible without similar to bare metal?

**Comment by siddharthist** [comment]
I think @stevendborrelli would be the one to ask

**Comment by siddharthist** [comment]
Closing as a duplicate of #1269. We'll keep you updated @andreimc!
