### ISSUE TITLE
Spark config parameters not passed to the driver

### ISSUE THREAD

**Issue by sophiecollard** [CiscoCloud/mantl#1515]
Hi,

I'm having problems launching Spark jobs in Mantl (1.0.3, running in Vagrant). It all works fine when using this particular Spark build: http://pele.farmbio.uu.se/spark-mantl/spark-mantl-1.6.0.tgz. However, I'd like to run some code that uses a `HiveContext` instead of a `SQLContext`, which is not supported by the build mentioned above. So I downloaded the Spark (1.6.0) source code and made my own build with:
```
./make-distribution.sh --name hadoop-2.4-hive --tgz -Phadoop-2.4 -Dhadoop.version=2.4.0 -Phive -Phive-thriftserver
```
I started the cluster dispatcher with Mantl API, using the following command:
```
curl https://192.168.100.101/api/1/install -u admin:password -X POST -d "{\"name\": \"spark\"}" -k
```
Then, I tried to launch the job from within one of my worker nodes using the `spark-submit` command, but it seems that whatever parameters I set in `$SPARK_HOME/conf/spark-defaults.conf` are being dropped before reaching my Spark driver. In particular, my `spark.mesos.principal` and `spark.mesos.secret` parameters are not passed to my driver, resulting in the following error:
```
...
I0607 19:06:05.863528 19562 sched.cpp:272] No credentials provided. Attempting to register without authentication
I0607 19:06:05.876974 19562 sched.cpp:1024] Got error 'Framework at scheduler-dad6521d-694e-458e-9362-900da93e463d@192.168.100.201:46062 is not authenticated'
I0607 19:06:05.877010 19562 sched.cpp:1805] Asked to abort the driver
16/06/07 19:06:05 ERROR CoarseMesosSchedulerBackend: Mesos error: Framework at scheduler-dad6521d-694e-458e-9362-900da93e463d@192.168.100.201:46062 is not authenticated
Exception in thread "Thread-26" org.apache.spark.SparkException: Exiting due to error from cluster scheduler: Framework at scheduler-dad6521d-694e-458e-9362-900da93e463d@192.168.100.201:46062 is not authenticated
	at org.apache.spark.scheduler.TaskSchedulerImpl.error(TaskSchedulerImpl.scala:438)
	at org.apache.spark.scheduler.cluster.mesos.CoarseMesosSchedulerBackend.error(CoarseMesosSchedulerBackend.scala:363)
I0607 19:06:05.891727 19562 sched.cpp:1805] Asked to abort the driver
I0607 19:06:05.891882 19562 sched.cpp:1070] Aborting framework ''
16/06/07 19:06:05 INFO CoarseMesosSchedulerBackend: driver.run() returned with code DRIVER_ABORTED
...
```
Note that if I disable Mesos framework authentication, other parameters set in `$SPARK_HOME/conf/spark-defaults.conf` are still not visible to my Spark driver.

This is the command I'm using to launch the job (in this case, the SparkPi example):
```
$SPARK_HOME/bin/spark-submit \
--name SparkPiTestApp \
--class org.apache.spark.examples.SparkPi \
--master mesos://$MASTER:$HOST \
--deploy-mode cluster \
--properties-file $SPARK_HOME/conf/spark-defaults.conf \
--driver-cores 1 \
--driver-memory 512M \
--total-executor-cores 1 \
--executor-memory 512M \
--verbose \
$PATH_TO_JAR \
100
```
Has anyone else encountered this issue before?

**Comment by sophiecollard** [comment]
After some more research I found this: https://issues.apache.org/jira/browse/SPARK-13258

As suggested, I passed my Mesos credentials and other config parameters via a `SPARK_JAVA_OPTS` environment variable set in `$SPARK_HOME/conf/spark-env.sh` and was able to run the SparkPi example successfully using my own Spark build.
```
SPARK_JAVA_OPTS="-Dspark.mesos.principal=mantl-api -Dspark.mesos.secret=<insert-secret-here>"
```

**Comment by siddharthist** [comment]
@sophiecollard I'm glad you got it working! Is there something we could improve in Mantl, or should we close this as an upstream bug?

**Comment by sophiecollard** [comment]
@siddharthist This seems to be an issue with Spark rather than Mantl. I think this can be closed.
