### ISSUE TITLE
addon: Mesos UI 

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1516]
The default Mesos UI isn't very pretty. Capgemini has a custom one that looks pretty nice, and can be used concurrently with the default. It should be very easy to add this to Mantl/MantlUI!

- Ansible version (`ansible --version`): n/a
- Python version (`python --version`): n/a
- Git commit hash or branch: n/a
- Cloud Environment: n/a
- Terraform version (`terraform version`): n/a

**Comment by kbroughton** [comment]
It would be really nice if we could add custom plugins to the ui.
Something as simple as being able to add links to our custom monitoring
pages so that we can have a single dashboard to access everything.  A
little guidance on how to do this would be appreciated.

On Wed, Jun 8, 2016 at 7:03 AM, Langston Barrett <notifications@github.com>
wrote:

> The default Mesos UI isn't very pretty. Capgemini has a custom one that
> looks pretty nice, and can be used concurrently with the default. It should
> be very easy to add this to Mantl/MantlUI!
>
>    - Ansible version (ansible --version): n/a
>    - Python version (python --version): n/a
>    - Git commit hash or branch: n/a
>    - Cloud Environment: n/a
>    - Terraform version (terraform version): n/a
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CiscoCloud/mantl/issues/1516>, or mute the thread
> <https://github.com/notifications/unsubscribe/AKErsoErO7RMHripjbs3wvZ8rAKW7QGHks5qJq98gaJpZM4Iw4rm>
> .
>



-- 
kesten broughton
devops @ cognitivescale

**Comment by siddharthist** [comment]
@kbroughton Please create another issue!

**Comment by siddharthist** [comment]
@kbroughton I've created #1518 to track that idea.

**Comment by distributorofpain** [comment]
Would also be nice if the UI launched webui's in different tabs when clicked...

**Comment by siddharthist** [comment]
@distributorofpain Please put UI-related ideas in issues at the [mantl-ui-frontend](https://github.com/CiscoCloud/mantl-ui-frontend) repo.

**Comment by distributorofpain** [comment]
Done :+1:

**Comment by siddharthist** [comment]
Closing this since it isn't really on our roadmap.
