### ISSUE TITLE
Can't seem to connect to k8s using local kubectl

### ISSUE THREAD

**Issue by andreimc** [CiscoCloud/mantl#1562]
Did anyone else get this ?

I did upgrade k8s to 1.2.4 on the cluster have tried on 1.2.0 as well but with 1.2.4 client.

```
kubectl --server=https://mantl.example.com/kubernetes/ --username=admin --password=passowrd --namespace=kube-system --insecure-skip-tls-verify get rc
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4+3eed1e3", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"not a git tree"}
error: failed to negotiate an api version; server supports: map[], client supports: map[metrics/v1alpha1:{} v1:{} authorization.k8s.io/v1beta1:{} autoscaling/v1:{} batch/v1:{} componentconfig/v1alpha1:{} extensions/v1beta1:{}]
```

- Ansible version (1.9.4): 
- Python version (2.7.11):
- Git commit hash or branch: Master
- Cloud Environment:  AWS
- Terraform version (0.6.16):

**Comment by siddharthist** [comment]
@andreimc I'm going to close this since it seems like you upgraded manually to a different version of k8s. We can't always support the newest version as fast as we like :-) Please reopen if you see this on an unmodified cluster!
