### ISSUE TITLE
Run kafka through consul

### ISSUE THREAD

**Issue by fire** [CiscoCloud/mantl#1570]
Trying to learn mantl: Can you describe the steps to run a kafka node using https://github.com/glerchundi/parkeeper and avoiding zookeeper?

**Comment by siddharthist** [comment]
I don't recommend using parkeeper. The ZK API is quite complex, and parkeeper hasn't been updated in more than a year. Zookeeper is already part of our default installation, so it's no loss to use it. 

You can install Kafka as an addon: http://docs.mantl.io/en/latest/components/kafka.html. Please reopen if you have any further questions!
