### ISSUE TITLE
Support fluentd as an alternative logger

### ISSUE THREAD

**Issue by fire** [CiscoCloud/mantl#1571]
Can you describe steps needed to add fluentd as an alternative to collectd?

Usecase: fluentd to ship json messages to a kafka 0.9+ (with tls) cluster.

**Comment by siddharthist** [comment]
Since we've never used fluentd as part of mantl, I'm not sure this is the best place to ask this question. Try taking a look at [fluentd's documentation](http://docs.fluentd.org/articles/quickstart).
