### ISSUE TITLE
Application 302 redirect goes to http://mantl-worker-001.node.consul:7994

### ISSUE THREAD

**Issue by andreimc** [CiscoCloud/mantl#1573]
Hey guys,

I have a container deployed that does a 302 redirect and this goes to the mantl-worker instead of the address is it something to do with traefik config?

Regards,
Andrei

- Ansible version (`ansible --version`):  1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: f377be1
- Cloud Environment:  AWS
- Terraform version (`terraform version`): 0.6.6

**Comment by ygoodmn** [comment]
What is your DCOS to deploy this container.

**Comment by andreimc** [comment]
Hey this is it:

```
{
  "cpus": 1.0,
  "mem": 1024,
  "id": "westeros",
  "instances": 1,
  "labels": {"traefik.frontend.entryPoints":"http"},
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "image",
      "network": "BRIDGE",
      "portMappings": [{
        "containerPort": 0,
        "hostPort": 0,
        "protocol": "tcp"
      }]
    }
  },
  "env": {
    "DB_PORT": "25432",
  },
  "healthChecks": [{
    "protocol": "TCP",
    "portIndex": 0
  }],
  "uris":  [
    "file:///etc/docker.tar.gz"
      ]
}
```

**Comment by andreimc** [comment]
cool I figured it out.

Had to use

"traefik.frontend.passHostHeader": "true"

this way it redirects correctly :)
