### ISSUE TITLE
The chronos add-on doesn't start.

### ISSUE THREAD

**Issue by st33v** [CiscoCloud/mantl#1576]
It's just 'waiting'. The docs indicate that it might take a bit to start but it's been three days now. I'm new to marathon and chronos... does anyone have a place for me to start diagnosing the problem?

- Ansible version: ansible 1.9.6
- Python version: Python 2.7.10
- Git commit hash or branch: master
- Cloud Environment: gce
- Terraform version: Terraform v0.6.16

**Comment by stevendborrelli** [comment]
Usually waiting means that there aren't enough resources (cpu, memory, open ports) on any of the nodes to be able to allocate the job. What is your worker configuration like?

**Comment by siddharthist** [comment]
@st33v You should be able to see how many resources are being offered in Mesos UI, on the left side.

**Comment by siddharthist** [comment]
@st33v Any updates?

**Comment by st33v** [comment]
Sorry.  Got side tracked. I'll probably pick this up again in a few weeks.
It's probably not worth fussing about. Likely user error.

**Comment by siddharthist** [comment]
Closing for now, please reopen if you're still running into this.
