### ISSUE TITLE
Calico installation

### ISSUE THREAD

**Issue by Arttii** [CiscoCloud/mantl#1577]
Hi,

So after running the playbook for Calico and getting everything installed the container networking does not seem to work. Is the documentation for Calico on Mantl still valid? 

- Ansible version : 2.0.2
- Python version :  2.7
- Git commit : master
- Cloud Environment: Bare Metal

**Comment by siddharthist** [comment]
@Zogg Does the documentation need to be updated with recent changes?

@Arttii What issues are you seeing?

**Comment by Arttii** [comment]
Hi,

Well following [this](http://docs.mantl.io/en/latest/components/calico.html) it seems the powerstrip is not running on any node. Calico itself seems to running and configured normally:

sudo calicoctl  status
calico-node container is running. Status: Up 43 hours
Running felix version 1.4.0rc1

IPv4 BGP status
IP: 10.7.93.30    AS Number: 64511 (inherited)
+--------------+-------------------+-------+------------+------------------------------------------+
| Peer address |     Peer type     | State |   Since    |                   Info                   |
+--------------+-------------------+-------+------------+------------------------------------------+
|  10.7.93.21  | node-to-node mesh | start | 2016-06-20 | Active        Socket: Connection refused |
|  10.7.93.22  | node-to-node mesh | start | 2016-06-20 | Active        Socket: Connection refused |
|  10.7.93.23  | node-to-node mesh | start | 2016-06-20 | Active        Socket: Connection refused |
|  10.7.93.24  | node-to-node mesh |   up  | 2016-06-20 |               Established                |
|  10.7.93.25  | node-to-node mesh |   up  | 2016-06-20 |               Established                |
|  10.7.93.26  | node-to-node mesh |   up  | 2016-06-20 |               Established                |
|  10.7.93.27  | node-to-node mesh |   up  | 2016-06-20 |               Established                |
|  10.7.93.28  | node-to-node mesh |   up  | 2016-06-20 |               Established                |
|  10.7.93.29  | node-to-node mesh |   up  | 2016-06-20 |               Established                |
+--------------+-------------------+-------+------------+------------------------------------------+

IPv6 BGP status
No IPv6 address configured.


calicoctl pool show
+----------------+-------------------+
|   IPv4 CIDR    |      Options      |
+----------------+-------------------+
| 192.168.0.0/16 | ipip,nat-outgoing |
+----------------+-------------------+
+--------------------------+---------+
|        IPv6 CIDR         | Options |
+--------------------------+---------+
| fd80:24e2:f998:72d6::/64 |         |
+--------------------------+---------+

So if i launch the test-app and described and try to resolve the testapp-direct no answer is coming back. 

I just might be missing something or misunderstanding the way it works. Some advice would be great.

Thanks.

**Comment by Zogg** [comment]
@Arttii The docs for Calico are a bit outdated. The best example is written here: http://aster.is/blog/2016/02/24/using-calico-to-connect-mesos-and-kubernetes .

In general, when launching tasks through Marathon, you need to pass calico group to which the task will be assigned. All apps in the same network group can communicate with each other. Like that:

```
{
    "id":"/calico-apps",
    "apps": [
        {
            "id": "hello-world-1",
            "cmd": "ip addr && sleep 30000",
            "cpus": 0.1,
            "mem": 64.0,
            "ipAddress": {
                "groups": ["calico-k8s-network"]
            }
        }
    ]
}
```

In order to reach this app I'd need to do `ping hello-world-1.service.consul`. If that does not work, open Consul's UI and see if the name that you are trying to resolve is really such (Marathon mangles app names when they are put into the group).

**Comment by Arttii** [comment]
So do I need to roll Kubernetes as well? I skipped the steps for opens tack and kubernetes in the calico role or is at least one of them required?

Thanks for the help

**Comment by Arttii** [comment]
Or I guess I can just pas the dev pool as the network?

**Comment by Zogg** [comment]
You dont need kubernetes to have calico.
You may pass whatever group name you need.

**Comment by Arttii** [comment]
Wouldn't just pinging through consul dns just resolve to the static ip of the node? It seems to do so, even though it does get a calico ip, and say if I go to the same node where the task is running I can ping it. I think I am misunderstanding something.

**Comment by siddharthist** [comment]
Ping @Zogg

**Comment by siddharthist** [comment]
Pinging @Zogg again

**Comment by Arttii** [comment]
I think we can close this. There was a problem with configuring the docker overlay net. The new addon/docker-overlay net fixes the issue.
