### ISSUE TITLE
update default gce centos image

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/mantl#1589]
GCE has released an updated centos7 image: centos-7-v20160606

We should test and update our default.

**Comment by stevendborrelli** [comment]
We'll get this error: 
```
:0.27-20.el7.centos will be installed\n--> Processing Conflict: gce-disk-expand-1.0.1-1461117609.el7.x86_64 conflicts cloud-util s-growpart\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n 
```

**Comment by ryane** [comment]
the new image includes a package (gce-disk-expand - https://cloud.google.com/compute/docs/images#os-details) that automatically resizes the root disk. We no longer need to install the dracut-modules-growroot and cloud-utils-growpart packages via terraform remote-exec in order to resize the root disk.

however, it looks like we will still hit the cloud-utils-growpart conflict in the docker lvm playbook: https://github.com/CiscoCloud/mantl/blob/master/roles/docker/tasks/lvm.yml#L4

any ideas @avnik?

**Comment by ryane** [comment]
the new image does not include cloud-init

**Comment by siddharthist** [comment]
If the new image doesn't include cloud-init, we should remove it from [our list of cloud-init providers](https://github.com/CiscoCloud/mantl/blob/47af543cea026d1cbc5df4c68776c80635001795/group_vars/all/main.yml#L4)

**Comment by ryane** [comment]
the existing image doesn't either. we install it via terraform remote-exec. I was just indicating that we still need to do that. there was some hope that this new image would include it.

**Comment by avnik** [comment]
On Thu, Jun 23, 2016 at 06:10:11AM -0700, Ryan Eschinger wrote:
> the new image includes a package (gce-disk-expand - https://cloud.google.com/compute/docs/images#os-details) that automatically resizes the root disk. We no longer need to install the dracut-modules-growroot and cloud-utils-growpart packages via terraform remote-exec in order to resize the root disk.
> 
> however, it looks like we will still hit the cloud-utils-growpart conflict in the docker lvm playbook: https://github.com/CiscoCloud/mantl/blob/master/roles/docker/tasks/lvm.yml#L4
> 
> any ideas @avnik?
> 

Is a remains from old `docker-storage-setup` 
(was undocumented transitive dependency)

I believe it can be removed safely
(current  mantl-storage-setup haven't this functionality inside)
