### ISSUE TITLE
Question : Mantl Networking ??

### ISSUE THREAD

**Issue by angry-tony** [CiscoCloud/mantl#1603]
I am wondering if Mantl can offer resources from multiple network interfaces?
I would like to attach multiple Network Interfaces (public eth0, private eth1) on Worker nodes and would like to bind specific applications that I run on Mantl's Worker nodes (mesos & K8s) on specific interfaces?
does not mantl need distinct physical networks like OpenStack has four distinct physical networks??

is there any reference guide or doc?

**Comment by siddharthist** [comment]
Mantl uses a single-network stack. We don't currently support binding some services to private interfaces. We're tracking that feature with #757. 

You might have some luck changing the configuration for your individual components, but we haven't really experimented with that. Sorry!
