### ISSUE TITLE
Bugs with Terraform

### ISSUE THREAD

**Issue by edshea4** [CiscoCloud/mantl#1604]
- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.5
- Git commit hash or branch:  I do not know.
- Cloud Environment: Openstack 8
- Terraform version (`terraform version`):v0.6.16

Hello, I am very new to all this openstack stuff. I have been trying to deploy Mantl however in the process, Terraform has been giving me lots of issues.

Upon deploying Terraform with 'terraform apply' it goes all the way until it hits this error: 
```
Error applying plan:

10 error(s) occurred:

* openstack_compute_floatingip_v2.floating-ip.1: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST http://172.29.86.52:8774/v2/3ca1ba55610c4dc0b320e076f000a5df/os-floating-ips], but got 404 instead
{"itemNotFound": {"message": "Floating ip pool not found.", "code": 404}}
* openstack_compute_floatingip_v2.floating-ip.0: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST http://172.29.86.52:8774/v2/3ca1ba55610c4dc0b320e076f000a5df/os-floating-ips], but got 404 instead
{"itemNotFound": {"message": "Floating ip pool not found.", "code": 404}}
* openstack_compute_floatingip_v2.floating-ip.2: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST http://172.29.86.52:8774/v2/3ca1ba55610c4dc0b320e076f000a5df/os-floating-ips], but got 404 instead
{"itemNotFound": {"message": "Floating ip pool not found.", "code": 404}}
* openstack_compute_floatingip_v2.floating-ip.1: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST http://172.29.86.52:8774/v2/3ca1ba55610c4dc0b320e076f000a5df/os-floating-ips], but got 404 instead
{"itemNotFound": {"message": "Floating ip pool not found.", "code": 404}}
* openstack_compute_floatingip_v2.floating-ip.0: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST http://172.29.86.52:8774/v2/3ca1ba55610c4dc0b320e076f000a5df/os-floating-ips], but got 404 instead
{"itemNotFound": {"message": "Floating ip pool not found.", "code": 404}}
* openstack_compute_floatingip_v2.floating-ip.1: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST http://172.29.86.52:8774/v2/3ca1ba55610c4dc0b320e076f000a5df/os-floating-ips], but got 404 instead
{"itemNotFound": {"message": "Floating ip pool not found.", "code": 404}}
* openstack_compute_floatingip_v2.floating-ip.0: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST http://172.29.86.52:8774/v2/3ca1ba55610c4dc0b320e076f000a5df/os-floating-ips], but got 404 instead
{"itemNotFound": {"message": "Floating ip pool not found.", "code": 404}}
* openstack_compute_floatingip_v2.floating-ip.1: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST http://172.29.86.52:8774/v2/3ca1ba55610c4dc0b320e076f000a5df/os-floating-ips], but got 404 instead
{"itemNotFound": {"message": "Floating ip pool not found.", "code": 404}}
* openstack_compute_floatingip_v2.floating-ip.0: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST http://172.29.86.52:8774/v2/3ca1ba55610c4dc0b320e076f000a5df/os-floating-ips], but got 404 instead
{"itemNotFound": {"message": "Floating ip pool not found.", "code": 404}}
* openstack_compute_floatingip_v2.floating-ip.2: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST http://172.29.86.52:8774/v2/3ca1ba55610c4dc0b320e076f000a5df/os-floating-ips], but got 404 instead
{"itemNotFound": {"message": "Floating ip pool not found.", "code": 404}}
```
Now with that I have tried to edit the file in /root/mantl/terraform/openstack/floating-ip/main.tf to change out the 'compute' portions with 'network' portions due to a suggestion that Neutron is what is needed. 

However I get the 'not supported' messages over and over.
``` 
Errors:

  * openstack_network_floatingip_v2.floating-ip #0: Provider doesn't support resource: openstack_network_floatingip_v2
  * openstack_network_floatingip_v2.floating-ip #0: Provider doesn't support resource: openstack_network_floatingip_v2
  * openstack_network_floatingip_v2.floating-ip #1: Provider doesn't support resource: openstack_network_floatingip_v2
  * openstack_network_floatingip_v2.floating-ip #2: Provider doesn't support resource: openstack_network_floatingip_v2
  * openstack_network_floatingip_v2.floating-ip #0: Provider doesn't support resource: openstack_network_floatingip_v2
  * openstack_network_floatingip_v2.floating-ip #0: Provider doesn't support resource: openstack_network_floatingip_v2
  * openstack_network_floatingip_v2.floating-ip #1: Provider doesn't support resource: openstack_network_floatingip_v2
  * openstack_network_floatingip_v2.floating-ip #1: Provider doesn't support resource: openstack_network_floatingip_v2
  * openstack_network_floatingip_v2.floating-ip #1: Provider doesn't support resource: openstack_network_floatingip_v2
  * openstack_network_floatingip_v2.floating-ip #2: Provider doesn't support resource: openstack_network_floatingip_v2
```

I will paste my openstack-modules-sample.tf: http://pastebin.com/UYxEHM1u

I think that nova is messing up the entire thing because it seems that there are no floating IP pools created when running terraform apply. 

Please help, I have no idea what I am doing wrong. Thank you!

**Comment by edshea4** [comment]
Ok so I have a fix that allowed everything to work and fix this bug... I need someone to verify this is a fix so I can push it upstream...


So the first thing I did was change the modules-sample.tf variable floating_ip_pool { default = "subnet-external" } to variable floating_ip_pool { default = "external" } because it wasnt able to use the subnet.

Next I changed the file in terraform/openstack/hosts-floating/main.tf so that instead of "openstack_compute_floatingip_v2, it was...

resource "openstack_networking_floatingip_v2" "ms-control-floatip" {
  pool       = "${ var.floating_pool }"
  count      = "${ var.control_count }"
  depends_on = [ "openstack_networking_router_v2.ms-router",
                 "openstack_networking_network_v2.ms-network",
                 "openstack_networking_router_interface_v2.ms-router-interface" ]
}

resource "openstack_networking_floatingip_v2" "ms-worker-floatip" {
  pool       = "${ var.floating_pool }"
  count      = "${ var.worker_count }"
  depends_on = [ "openstack_networking_router_v2.ms-router",
                 "openstack_networking_network_v2.ms-network",
                 "openstack_networking_router_interface_v2.ms-router-interface" ]
}

resource "openstack_networking_floatingip_v2" "ms-kubeworker-floatip" {
  pool       = "${ var.floating_pool }"
  count      = "${ var.kubeworker_count }"
  depends_on = [ "openstack_networking_router_v2.ms-router",
                 "openstack_networking_network_v2.ms-network",
                 "openstack_networking_router_interface_v2.ms-router-interface" ]
}

resource "openstack_networking_floatingip_v2" "ms-edge-floatip" {
  pool       = "${var.floating_pool}"
  count      = "${var.edge_count}"
  depends_on = [ "openstack_networking_router_v2.ms-router",
                 "openstack_networking_network_v2.ms-network",
                 "openstack_networking_router_interface_v2.ms-router-interface" ]
}


Lastly because of hardware constraints I switched the amount of control, kubeworker, worker, and edge count to all 1. 

I also went onto horizion>admin>defaults and adjusted my resources from there so that all this would fit.

**Comment by bingoarunprasath** [comment]
Hi @edshea4 ,  Terraform doesn't create the floating-ip pool. The normal use case is that the openstack administrator will create the floating IP pool and the end user just consume it. 

In this case you are installing Mantl on Openstack as end user. So you can just do "# nova floating-ip-pool-list " and use any of the available pool name in "variable floating_ip_pool".  

If you don't have any pool , Admin (or any user with admin role) need to create the floating IP pool for you. Still Terraform won't / shouldn't create floating IP pool.

**Comment by siddharthist** [comment]
@edshea4 Glad you got it working! We don't recommend running a single control node, it is highly unstable. Looks like your configuration changes are environment dependent, so there's not a big need to make a pull request (unless I'm missing something).

**Comment by rohitagarwalla** [comment]
thanks @bingoarunprasath. The suggestion here is that there should be an option for floating-ip's to be  handled by Neutron in OpenStack as part of Mantl. 

@siddharthist i agree, let's keep aside the environment changes as they as they are not related to the core of the discussion. The main issue that I understand is as follows - 

The Mantl Floating IP module [1] is using Nova Compute Floating IP [2] resource for instances. This assumes that Nova-Network is running as part of the OpenStack deployment and the floating IP requests are hence sent to the Nova service. Nova-Network is legacy networking and Neutron (OpenStack Networking service), which is a core OpenStack service handles network resources including Floating IP's. So, IMO Mantl Floating IP module should be using Networking Floating IP resource [3] from Terraform.
[1] https://github.com/CiscoCloud/mantl/blob/master/terraform/openstack/floating-ip/main.tf
[2] https://www.terraform.io/docs/providers/openstack/r/compute_floatingip_v2.html
[3] https://www.terraform.io/docs/providers/openstack/r/networking_floatingip_v2.html
cc: @edshea4

**Comment by siddharthist** [comment]
Thanks for the clarification @rohitagarwalla, the issue linked above tracks that suggestion.
