### ISSUE TITLE
Use openstack_networking_floatingip_v2 instead of openstack_compute_floatingip_v2

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1606]
quoting from @rohitagarwalla on #1604:
> The Mantl Floating IP module [1] is using Nova Compute Floating IP [2] resource for instances. This assumes that Nova-Network is running as part of the OpenStack deployment and the floating IP requests are hence sent to the Nova service. Nova-Network is legacy networking and Neutron (OpenStack Networking service), which is a core OpenStack service handles network resources including Floating IP's. So, IMO Mantl Floating IP module should be using Networking Floating IP resource [3] from Terraform.
[1] https://github.com/CiscoCloud/mantl/blob/master/terraform/openstack/floating-ip/main.tf
[2] https://www.terraform.io/docs/providers/openstack/r/compute_floatingip_v2.html
[3] https://www.terraform.io/docs/providers/openstack/r/networking_floatingip_v2.html
cc: @edshea4  

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: openstack
- Terraform version (`terraform version`): 0.7.0

**Comment by edshea4** [comment]
Bump. Can someone confirm if this is a bug?  If this is a bug I can push a fix.

**Comment by stevendborrelli** [comment]
@edshea4 if you have a newer openstack cluster to test, we'd love a PR to fix it.

**Comment by stevendborrelli** [comment]
The one issue we have to be aware of is any effects of changing the terraform resources might do to an existing cluster.

**Comment by edshea4** [comment]
This is applicable if you are using an openstack network using neutron over nova network which is going to get deprecated. This is what I am committing, I am looking into the build failures https://github.com/CiscoCloud/mantl/pull/1759/commits/48e0cd2175824dfb60532ee38bb7116aa192b1ba THANK YOU VERY MUCH

**Comment by siddharthist** [comment]
Closed in #1759
