### ISSUE TITLE
Investigate using OpenVPN/easy-rsa instead of generate-certificate

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1609]
We have [an awesome script for generating SSL certs](https://github.com/asteris-llc/mantl-packaging/tree/3fc4488a9bdd3b5e30dadbb91cd9d40c25348950/packages/generate-certificate), but we might not have to maintain that code if we look into using [OpenVPN/easy-rsa](https://github.com/OpenVPN/easy-rsa). 

Advantages:
 * Developed by experienced security folks at OpenVPN
 * Used upstream in [CiscoCloud/kubernetes-ansible](https://github.com/CiscoCloud/kubernetes-ansible/blob/2e5221a30adc8aa2fbbdfa26a28e5842faf259fc/roles/kubernetes/files/make-ca-cert.sh)
 * Used upstream in kubernetes/contrib/ansible
 * Actively developed (contributions <1 month old)
 * Cross-platform support (even windows)
 * Widely used (the arch linux wiki [has a section on it](https://wiki.archlinux.org/index.php/Easy-rsa))

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

**Comment by krish7919** [comment]
@siddharthist : Can you elaborate the use case here? I am late to the party but maybe I can help. :)

**Comment by siddharthist** [comment]
@krish7919 Sure! In [our certificate generation role](https://github.com/CiscoCloud/mantl/tree/master/roles/certificates), we:
 1. [Install the generate-certificate package](https://github.com/CiscoCloud/mantl/blob/0581400b1f5b06084bcd7036e5a4d21062fcdb3a/roles/certificates/tasks/main.yml#L27)
 2. [Use it to generate tls certificates](https://github.com/CiscoCloud/mantl/blob/0581400b1f5b06084bcd7036e5a4d21062fcdb3a/roles/certificates/tasks/main.yml#L42) 

It looks like this has very similar functionality to Openssl/easy-rsa, so with some different command-line options, it might be a drop-in replacement. The certificates would have to be valid for all the same IPs and DNS names.

**Comment by krish7919** [comment]
Alright, I have done some easy-rsa work with openvpn, so I can hit the
ground running on that aspect. But I have never run this project at all; I
just stumbled on to this. Is there a vagrant image and a quick walk through
on the setup?

Before I commit to this, I would like to get a feel for the project;
especially the certificate generation part.


On Tuesday 28 June 2016, Langston Barrett <notifications@github.com> wrote:

> @krish7919 <https://github.com/krish7919> Sure! In our certificate
> generation role
> <https://github.com/CiscoCloud/mantl/tree/master/roles/certificates>, we:
>
>    1. Install the generate-certificate package
>    <https://github.com/CiscoCloud/mantl/blob/0581400b1f5b06084bcd7036e5a4d21062fcdb3a/roles/certificates/tasks/main.yml#L27>
>    2. Use it to generate tls certificates
>    <https://github.com/CiscoCloud/mantl/blob/0581400b1f5b06084bcd7036e5a4d21062fcdb3a/roles/certificates/tasks/main.yml#L42>
>
> It looks like this has very similar functionality to Openssl/easy-rsa, so
> with some different command-line options, it might be a drop-in
> replacement. The certificates would have to be valid for all the same IPs
> and DNS names.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CiscoCloud/mantl/issues/1609#issuecomment-229130699>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE1QqnqWddLe7Hi7FUHRZKbJ9X3w8ki9ks5qQWEfgaJpZM4JAL9a>
> .
>


-- 

Thumb typed mail

**Comment by siddharthist** [comment]
@krish7919 Yes, there is a working Vagrant image, just clone the repo and run `vagrant up`. Check out [our getting started guide](http://docs.mantl.io/en/latest/getting_started/index.html) for more information.

**Comment by krish7919** [comment]
Perfect. I will play with it and update progress here on what's my
understanding and how we can leverage easy-rsa here.


On Tuesday 28 June 2016, Langston Barrett <notifications@github.com> wrote:

> @krish7919 <https://github.com/krish7919> Yes, there is a working Vagrant
> image, just clone the repo and run vagrant up. Check out our getting
> started guide <http://docs.mantl.io/en/latest/getting_started/index.html>
> for more information.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CiscoCloud/mantl/issues/1609#issuecomment-229133731>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE1Qqid9eR4jhH6slf7wudq8sQIHyQR7ks5qQWN_gaJpZM4JAL9a>
> .
>


-- 

Thumb typed mail

**Comment by siddharthist** [comment]
Ultimately, we need to make the changes I just outlined in #1551.
