### ISSUE TITLE
Enable Consul Template SSL

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1619]
[Our Consul Template config file](https://github.com/CiscoCloud/mantl/blob/master/roles/consul-template/templates/consul.cfg.j2) should include the following snippet:
```conf
ssl {
  enabled = true
  verify = true
  cert = "{{ host_cert }}"
  key = "{{ host_key }}"
  ca_cert = "/etc/pki/CA/ca.cert"
}
```
I have an untested branch at https://github.com/CiscoCloud/mantl/tree/feature/consul-template-ssl

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

**Comment by ChrisAubuchon** [comment]
consul-template is connecting to `127.0.0.1:8500` which is not SSL. This is not needed.

**Comment by siddharthist** [comment]
It will enable #1618, since consul-template runs on all nodes but Vault doesn't.

**Comment by ChrisAubuchon** [comment]
There is an `ssl` block inside of the consul-template vault config for communicating with vault:
From https://github.com/hashicorp/consul-template
```
// This denotes the start of the configuration section for Vault. All values
// contained in this section pertain to Vault.
vault {
...
  // This section details the SSL options for connecting to the Vault server.
  // Please see the SSL options below for more information (they are the same).
  ssl {
    // ...
  }
}
```

**Comment by siddharthist** [comment]
Ah, great! Thanks for pointing that out.
