### ISSUE TITLE
vagrant up -- ansible fail: Group tls does not exist

### ISSUE THREAD

**Issue by tomsherrod** [CiscoCloud/mantl#1628]
VirtualBox: 5.0.24 r108355
Vagrant: 1.8.1
git hash: 0581400b1f5b06084bcd7036e5a4d21062fcdb3a

failed: [control-01] => {"failed": true}
msg: Group tls does not exist
failed: [worker-001] => {"failed": true}
msg: Group tls does not exist
failed: [edge-001] => {"failed": true}
msg: Group tls does not exist
failed: [kubeworker-001] => {"failed": true}
msg: Group tls does not exist

**Comment by siddharthist** [comment]
@tomsherrod What task is this failing on?

**Comment by tomsherrod** [comment]
I tried vagrant again on another mac, difference - vagrant 1.8.4, same result.
TASK: [certificates | create tls group] *************************************** 
skipping: [worker-001]
skipping: [kubeworker-001]
skipping: [control-01]
skipping: [edge-001]

(some other tasks scroll by)

TASK: [consul | add consul user to tls group] ********************************* 
failed: [control-01] => {"failed": true}
msg: Group tls does not exist
failed: [worker-001] => {"failed": true}
msg: Group tls does not exist
failed: [kubeworker-001] => {"failed": true}
msg: Group tls does not exist
failed: [edge-001] => {"failed": true}
msg: Group tls does not exist

FATAL: all hosts have already failed -- aborting

**Comment by tomsherrod** [comment]
I did a fresh pull:  git rev-parse HEAD = 1fd4bc67cff7f9023454b8de325351f46abc3ee5

**Comment by siddharthist** [comment]
Huh, I don't know why it would skip that task, [there's no `when:` clause or anything](https://github.com/CiscoCloud/mantl/blob/1fd4bc67cff7f9023454b8de325351f46abc3ee5/roles/certificates/tasks/main.yml#L59-63). I assume it's probably not running any of the tasks in that role. 

A temporary workaround would be to disable security (specifically disable consul ssl).

**Comment by siddharthist** [comment]
Oh, it might be skipping the certificates role because `do_consul_ssl` is disabled. Are you running without security enabled? If so, give it a shot with security enabled.

**Comment by tomsherrod** [comment]
Enabled security by editing provision.sh, ./security-setup --enable=true.
Certificates role is still skipped.
Fails:

TASK: [docker | setup private docker registry credentials]
********************

fatal: [control-01] => {'msg': "AnsibleUndefinedVariable: One or more
undefined variables: 'docker_registries' is undefined", 'failed': True}

fatal: [control-01] => {'msg': "AnsibleUndefinedVariable: One or more
undefined variables: 'docker_registries' is undefined", 'failed': True}

fatal: [worker-001] => {'msg': "AnsibleUndefinedVariable: One or more
undefined variables: 'docker_registries' is undefined", 'failed': True}

fatal: [worker-001] => {'msg': "AnsibleUndefinedVariable: One or more
undefined variables: 'docker_registries' is undefined", 'failed': True}

fatal: [kubeworker-001] => {'msg': "AnsibleUndefinedVariable: One or more
undefined variables: 'docker_registries' is undefined", 'failed': True}

fatal: [kubeworker-001] => {'msg': "AnsibleUndefinedVariable: One or more
undefined variables: 'docker_registries' is undefined", 'failed': True}

fatal: [edge-001] => {'msg': "AnsibleUndefinedVariable: One or more
undefined variables: 'docker_registries' is undefined", 'failed': True}

fatal: [edge-001] => {'msg': "AnsibleUndefinedVariable: One or more
undefined variables: 'docker_registries' is undefined", 'failed': True}


FATAL: all hosts have already failed -- aborting

**Comment by siddharthist** [comment]
@tomsherrod That looks like a very different error.

**Comment by tomsherrod** [comment]
@siddharthist Note certificates are still skipped and doesn't make it to the consul task. Yes, very different error. Did I enable security correctly by modifying the parameter to security-setup in provision.sh?

I'm stumped by why ansible is skipping certificates. If the ansible parameters were written to the control machine, debugging may be easier. I plan to crack that later today, as in assembling the parameters and running it by hand, unless you have a better recommendation?

**Comment by siddharthist** [comment]
@tomsherrod Yeah, I don't know why it would still skip generating certificates. Have you fully destroyed and recreated the VM? sometimes there can be some weirdness from doing multiple ansible runs on the same VM. Your solution should enable security. You might also try running security-setup on your host first.

**Comment by RaunoVV** [comment]
1) Probably your using old mantl.yml and certificates role is missing from runlist in it (check sample.yml)
2) Disable docker_private_registry from security.yml if your not using one. Otherwise define docker_registries variable in it.
