### ISSUE TITLE
Add documentation for vagrant configuration?

### ISSUE THREAD

**Issue by sehqlr** [CiscoCloud/mantl#1647]
There is an option to use a file to configure the multi-VM deployment for vagrant, and there are a set of defaults defined in the Vagrantfile. However, the only documentation for this is within the Vagrantfile itself. Would it be useful for us to have a section on readthedocs where we explain the config? Or is the assumption that people working with vagrant will know how to read the config directly?

**Comment by siddharthist** [comment]
http://docs.mantl.io/en/latest/getting_started/vagrant.html

**Comment by siddharthist** [comment]
In fact, we have too much documentation for Vagrant: https://github.com/CiscoCloud/mantl/tree/master/vagrant

**Comment by sehqlr** [comment]
Why didn’t I check with you first? :eye-roll-at-myself:

**Comment by siddharthist** [comment]
No problem :) it might be confusing that they're in getting started? Although a quick search for Vagrant turns stuff up.
