### ISSUE TITLE
Self generated certificate in mantl

### ISSUE THREAD

**Issue by distributorofpain** [CiscoCloud/mantl#1657]
Can the length be changed from 1 year to 20?

Unless there is an easy way to regen it on every host and apply...

**Comment by siddharthist** [comment]
@distributorofpain Excellent question! Please see (and test if you can :smile:) my PR #1646 which gives the root CA a 10 year lifespan and #1645 which allows the user to rotate their certificates using vault!

**Comment by distributorofpain** [comment]
oh, i will make sure to search PRs next time as well!  Thanks!  Are they going to merge it soon?

**Comment by siddharthist** [comment]
@distributorofpain I'm not sure, but extra testing always ensures that our PRs get merged faster!
