### ISSUE TITLE
repository failure when updating mantl nodes using ansible

### ISSUE THREAD

**Issue by ACluelessOne** [CiscoCloud/mantl#1697]
Whern running
ansible-playbook playbooks/upgrade-packages.yml
the following error occurs and only 2 nodes are successful

TASK: [refresh yum cache] *****************************************************
failed: [mantl-control-01] => {"changed": true, "cmd": ["yum", "makecache"], "delta": "0:00:00.560416", "end": "2009-10-01 11:08:47.928627", "rc": 1, "start": "2009-10-01 11:08:47.368211", "warnings": ["Consider using yum module rather than running yum"]}
stderr:

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again
stdout: Loaded plugins: fastestmirror, langpacks
failed: [mantl-worker-002] => {"changed": true, "cmd": ["yum", "makecache"], "delta": "0:00:00.584094", "end": "2009-10-01 11:08:47.952997", "rc": 1, "start": "2009-10-01 11:08:47.368903", "warnings": ["Consider using yum module rather than running yum"]}
stderr:

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again
stdout: Loaded plugins: fastestmirror, langpacks
failed: [mantl-worker-003] => {"changed": true, "cmd": ["yum", "makecache"], "delta": "0:00:00.674464", "end": "2009-10-01 12:10:42.225450", "rc": 1, "start": "2009-10-01 12:10:41.550986", "warnings": ["Consider using yum module rather than running yum"]}
stderr:

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

mantl-control-01           : ok=1    changed=1    unreachable=0    failed=1
mantl-control-02           : ok=1    changed=1    unreachable=0    failed=1
mantl-control-03           : ok=1    changed=1    unreachable=0    failed=1
mantl-edge-01              : ok=4    changed=2    unreachable=0    failed=0
mantl-edge-02              : ok=1    changed=1    unreachable=0    failed=1
mantl-worker-001           : ok=4    changed=2    unreachable=0    failed=0
mantl-worker-002           : ok=1    changed=1    unreachable=0    failed=1
mantl-worker-003           : ok=1    changed=1    unreachable=0    failed=1

- Ansible version (`ansible --version`):  1.9.6 
- Python version (`python --version`): 2.7.5
- Git commit hash or branch: 
- Cloud Environment: CentOS 7 with vsphere/vcenter
- Terraform version (`terraform version`): 0.6.16

**Comment by siddharthist** [comment]
@ACluelessOne Looks like your machines can't connect to the Centos repo. Are you sure they're connected to the internet? Have you tried running the playbook again?

**Comment by ACluelessOne** [comment]
They are connected to the internet, i can ping websites

**Comment by siddharthist** [comment]
@ACluelessOne Can you try manually running `yum makecache` on your machines?

You might also try removing that task from the playbook and running `ansible-playbook` again.

**Comment by ACluelessOne** [comment]
One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail.
Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again

I got this error when running makecache

**Comment by siddharthist** [comment]
@ACluelessOne What's the output of 
```
yum info epel-release
```

**Comment by ACluelessOne** [comment]
same error

**Comment by siddharthist** [comment]
@ACluelessOne I'm just searching on DuckDuckGo now, but you can try:
```
yum --disablerepo=epel -y update  ca-certificates
```

**Comment by siddharthist** [comment]
And 
```
yum --disablerepo=epel info epel-release
```

**Comment by ACluelessOne** [comment]
Installed Packages
Name        : epel-release
Arch        : noarch
Version     : 7
Release     : 7
Size        : 24 k
Repo        : installed
From repo   : epel
Summary     : Extra Packages for Enterprise Linux repository configuration
URL         : http://download.fedoraproject.org/pub/epel
License     : GPLv2
Description : This package contains the Extra Packages for Enterprise Linux
            : (EPEL) repository GPG key as well as configuration for yum.

no packages marked for updates when i try to update ca-certificates

**Comment by siddharthist** [comment]
@ACluelessOne What's the output of `date`?

**Comment by ACluelessOne** [comment]
Fri Oct  2 02:59:40 UTC 2009

**Comment by ACluelessOne** [comment]
isit due to wrong date?

**Comment by siddharthist** [comment]
@ACluelessOne See anything wrong? :wink: That needs to be set correctly.

**Comment by siddharthist** [comment]
@ACluelessOne See #1696. TLS certificates can't be verified unless the date is set correctly.

**Comment by siddharthist** [comment]
@ACluelessOne Please reopen if your issue isn't solved after setting the proper date. I've made a new issue for getting a more intuitive error message. Thanks for bringing this to our attention!

**Comment by ACluelessOne** [comment]
thanks a lot!!!
