### ISSUE TITLE
rotate logs in nginx-consul

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#1709]
Reference: https://github.com/CiscoCloud/nginx-consul/issues/11

- Git commit hash or branch: 1.2
- Cloud Environment: GCE 
- Terraform version 0.6.15

The nginx-consul container does not rotate logs

**Comment by siddharthist** [comment]
This is fixed in CiscoCloud/nginx-consul#12. Now we just need to do a new release and incorporate it into mantl.
