### ISSUE TITLE
Broken link on mantl.io

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1729]
At http://mantl.io/resources, under "mantl and microservices webinar", there is a broken link. Who can fix this @stevendborrelli?

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

**Comment by stevendborrelli** [comment]
@matjohn2, can you take a look at this?

**Comment by matjohn2** [comment]
@stevendborrelli @siddharthist Sure.

**Comment by matjohn2** [comment]
Tracking down content.

**Comment by matjohn2** [comment]
Removed offending link (content no longer available). 
Also fixed docs link to readthedocs in same push. New version live.

**Comment by siddharthist** [comment]
@matjohn2 Thanks!
