### ISSUE TITLE
MarathonUI failed to capture stdout log for Helloworld example

### ISSUE THREAD

**Issue by Dacode45** [CiscoCloud/mantl#1737]
I was able to launch the hello world example `examples/hello-world/launch.sh`. In the Marathon UI, I get an error whenever I try to access the error our output logs. 

Image below.
[Imgur](http://i.imgur.com/rWwaXuz.png)

- Ansible version (`ansible --version`): 1.9.6
- Python version (`python --version`): 2.7.11+
- Git commit hash or branch: 5cb8df5c373e0533324ef87f6e5db187d6bf6455
- Cloud Environment: gce
- Terraform version (`terraform version`):0.6.16

**Comment by ryane** [comment]
@Dacode45 unfortunately, this is a known issue and not something we can easily fix (requires changes to marathon). see #1530. the workaround is to view the logs from the mesos UI.
