### ISSUE TITLE
CI build doesn't respect requirements.txt

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1754]
See #1753 and #1742 for motivation.

Currently, the CI build doesn't actually use the libraries installed when running
```
pip install -r requirements.txt
```
- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

**Comment by ryane** [comment]
@sehqlr @siddharthist any update on this? #1753 looks to be ready to merge but, if I am understanding correctly, all future ci builds (that are based off of master) will break.

**Comment by ryane** [comment]
ah, I see this might be fixed in #1758 but looks like there are some remaining issues before that can be merged

**Comment by siddharthist** [comment]
@ryane Exactly. I think we should merge those in that order.

**Comment by siddharthist** [comment]
Closed in #1758
