### ISSUE TITLE
Question: How to deploy a docker container in mantl?

### ISSUE THREAD

**Issue by ACluelessOne** [CiscoCloud/mantl#1755]
Hi, I'm new and I would like to know is there any guide as to how to deploy a docker app/image in mantl?

**Comment by sehqlr** [comment]
Hey, there @ACluelessOne. Currently, mantl supports two container scheduler systems: Kubernetes and Marathon. Once you have a mantl cluster running, you can use either of them to deploy docker containers. 
Here is the getting started guide for [Kubernetes](http://kubernetes.io/docs/hellonode/)
Here is the getting started guide for [Marathon](https://mesosphere.github.io/marathon/docs/application-basics.html)

And, if you'd like, we have a [gitter channel](https://gitter.im/CiscoCloud/mantl) available for asking questions, if IM is more your speed.

**Comment by siddharthist** [comment]
@ACluelessOne Also, check out the examples/ directory for some example containers :-) please reopen this if you have more questions!
