### ISSUE TITLE
Calico Profile Creation Fails with "Error Accesing etcd"..

### ISSUE THREAD

**Issue by kamlesh333** [CiscoCloud/mantl#1756]
```
cloud-user@mantl-worker-001 ~]$ ansible --version
-bash: ansible: command not found
[cloud-user@mantl-worker-001 ~]$ exit
logout
Connection to 10.0.0.21 closed.
cloud-user@mantl-jump:~$ ansible --version
ansible 1.9.6
  configured module search path = /usr/share/ansible
cloud-user@mantl-jump:~$ python --version
Python 2.7.6
cloud-user@mantl-jump:~$ terraform --version
Terraform v0.6.16
```

Cloud is Cisco Intercloud Services (Openstack, believe Liberty based largely).

Here are the errors:
```
TASK: [calico | create calico profile] ****************************************
failed: [mantl-worker-001] => {"changed": true, "cmd": "calicoctl profile add \"dev\"", "delta": "0:00:06.350827", "end": "2016-07-22 15:11:45.802806", "rc": 1, "start": "2016-07-22 15:11:39.451979", "warnings": []}
stdout: create_profile: Error accessing etcd (Internal Server Error : None).  Is etcd
running?

FATAL: all hosts have already failed -- aborting



Here is the output from etcd log -->
ul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member 1311
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member 8972
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member 8972
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member a609
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member a609
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member d904
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member d904
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member c61f
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member c61f
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member 365b
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member 365b
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member 1311
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member 1311
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member 8972
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member 8972
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22 09:25:32 rafthttp: failed to find member a609
Jul 22 09:25:32 mantl-worker-001 etcd-service-start.sh[16596]: 2016/07/22
```

**Comment by sehqlr** [comment]
Hey, @kamlesh333, we've been having difficulties with `etcd` stability, so there may be a PR in the works that will address this issue and the others.

**Comment by kamlesh333** [comment]
Thanks @sehqlr ! I am still wondering if there is a way to get this going without the calico, as I still believe that calico is not required component? (ref a chat with @hpreston ).

**Comment by stevendborrelli** [comment]
We may just have to remove your etcd data and re-apply that role. 

Are the other etcd nodes seeing this same issue?  Try running `etcdctl cluster-health` on all the nodes of the cluster.

**Comment by kamlesh333** [comment]
I am a newbie to ansible so this may be because of my lack of expertise but here is what I am getting when I try to run etcdctl ..I ran both ways with and without --module-path option, same errors
cloud-user@mantl-jump:~/mantl$ ansible all -m "/usr/bin/etcdctl cluster-health" --module-path /usr/bin/etcdctl
mantl-control-01 | FAILED => module /usr/bin/etcdctl cluster-health not found in configured module paths
mantl-kubeworker-001 | FAILED => module /usr/bin/etcdctl cluster-health not found in configured module paths
mantl-worker-001 | FAILED => module /usr/bin/etcdctl cluster-health not found in configured module paths
mantl-worker-002 | FAILED => module /usr/bin/etcdctl cluster-health not found in configured module paths
mantl-edge-01 | FAILED => module /usr/bin/etcdctl cluster-health not found in configured module paths
mantl-kubeworker-002 | FAILED => module /usr/bin/etcdctl cluster-health not found in configured module paths
mantl-control-02 | FAILED => module /usr/bin/etcdctl cluster-health not found in configured module paths
mantl-edge-02 | FAILED => module /usr/bin/etcdctl cluster-health not found in configured module paths

**Comment by stevendborrelli** [comment]
It almost feels like the etcd role did not get applied. Is it in your sample.yaml file for the hosts?

**Comment by kamlesh333** [comment]
Yep! 

    consul_servers_group: role=control
  roles:
    - common
    - lvm
    - docker
    - logrotate
    - consul-template
    - nginx
    - consul
    - etcd
    - dnsmasq

**Comment by kamlesh333** [comment]
@stevendborrelli  let me know if you want to look at my install? May be able to expedite the resolution.

**Comment by siddharthist** [comment]
@kamlesh333 Please remember to wrap all logs and source code in triple backticks: \`\`\`. See [Github's documentation on code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for more details.

**Comment by kamlesh333** [comment]
Hi @siddharthist , thanks for that tip.

**Comment by kamlesh333** [comment]
So I am no longer seeing this issue after I pulled the latest code base and did a reinstall. But I am still seeing the Consul issues seen by others, so would chase that one now. I do think the latest code block may have address this issue.
