### ISSUE TITLE
kubectl exec doesn't work when running in vagrant

### ISSUE THREAD

**Issue by TimWSpence** [CiscoCloud/mantl#1806]
The expected way to run kubectl locally is to point it to https://{control vm ip}/kubeapi

However, this does not work when running kubectl exec. 

```
➜  kubectl exec -ti prometheus-rc-mrw87 bash
Error from server: Upgrade request required
```
You have to point it to https://{control vm ip}:6443 instead.

I haven't debugged too much further but I believe it may be that kubectl exec requires spdy and I'm guessing that the mantlui doesn't support it when proxying to the kubernetes api server. Hence you have to go direct to the apiserver on https://{control vm ip}:6443 instead.

**Comment by ryane** [comment]
@TimWSpence see #1801. The problem affects all of our platforms right now. I agree that it is likely due to lack of SPDY. Going to close this one as a duplicate though.

**Comment by TimWSpence** [comment]
Thanks for the swift response @ryane!
