### ISSUE TITLE
Distributed health checks start failing

### ISSUE THREAD

**Issue by jeroenjacobs1205** [CiscoCloud/mantl#1824]
I noticed the following errors suddenly started to show up under "Distributive dnsmasq Health Checks":

time="2016-08-18T10:39:39Z" level=info msg="Report from checklist" checklist="dnsmasq health check" report="↴\nTotal: 8\nPassed: 7\nFailed: 1\nOther: 0\nIs not a file: /etc/resolv.conf" 

it seems this is a symlink now. We use an older version of Mantl (1.0.3). We also run the upgrade-packages playbook regularly. Is it possible this leads to receiving upgraded packages that are not compatible with our version of Mantl?

**Comment by siddharthist** [comment]
@jeroenjacobs1205 It is possible that there's a new version that doesn't match. We just switched to using different repos for different versions of Mantl, but that change happened in 1.2. What version of `distributive-dnsmasq-checks` do you have?

**Comment by siddharthist** [comment]
Actually, looks like in 1.0.3 we didn't have the distributive role. You may have upgraded to a different version of distributive. It should be 0.2.4-1: https://github.com/CiscoCloud/mantl/blob/74fcc9ddcf58ea83ca5613def6403fc5720ae809/roles/common/defaults/main.yml#L2

**Comment by jeroenjacobs1205** [comment]
Solved by upgrading to Mantl 1.2
