### ISSUE TITLE
Integrate with VMware

### ISSUE THREAD

**Issue by davidbuchanan** [CiscoCloud/mantl#587]
Integration with vSphere and vCentre.

**Comment by stevendborrelli** [comment]
@davidbuchanan, we have support for deploying to vSphere: http://microservices-infrastructure.readthedocs.org/en/latest/getting_started/vsphere.html. 

What other support were you thinking of?

**Comment by chrislovecnm** [comment]
@davidbuchanan just following up with your question.  One of the main things that I have researched is that vSphere does not have a terraform supported terraform provider.  I am trying to work out which provider we are going to document and more testing with.

**Comment by cdmitri** [comment]
Hi Chris - we have vSphere working in a private branch, not integrated to
mantl os yet, but we can help your use case. Send me an email note:
dchtchou@cisco.com

**Comment by chrislovecnm** [comment]
@cdmitri included you on a thread that I had started with a few Cisco folks.  Thanks!

**Comment by siddharthist** [comment]
We have a documented solution, with the community supported vSphere provider. Can we close this issue? @davidbuchanan @chrislovecnm

**Comment by chrislovecnm** [comment]
@siddharthist I am working with the terraform provider to get terraform vSphere provider to suppport mantl's requirements.  So you can close this and I can open another to track that, or we can keep this open. We are missing a couple of features in the terraform provider before it will work with mantl.  Your call.

**Comment by chrislovecnm** [comment]
https://github.com/hashicorp/terraform/pull/3867 is in.  Terraform will need to cut a release as well.  I am working on a pull to push in changes for our:

* documentation
* python scripts
* tf examples

**Comment by siddharthist** [comment]
Specifically, we're waiting for a release after v0.6.8.

**Comment by siddharthist** [comment]
Looks like Terraform v0.6.9 is out!

**Comment by chrislovecnm** [comment]
It is ;) Had a conversation with @stevendborrelli about testing. Will merge in with a note that this is community supported, until we can work out integration testing.

**Comment by stevendborrelli** [comment]
I'm going to close this, please reopen new issues for specific vSphere issues.
