### ISSUE TITLE
collectd role : add /usr/sbin to path for running semodule

### ISSUE THREAD

**Issue by avthart** [CiscoCloud/mantl#650]
```
failed: [apps6.enovation.dev] => {"changed": true, "cmd": "semodule -i /tmp/collectd_docker_plugin.pp", "delta": "0:00:00.005088", "end": "2015-08-18 08:18:15.798984", "rc": 127, "start": "2015-08-18 08:18:15.793896", "warnings": []}
stderr: /bin/sh: semodule: command not found
```

Fix:
You just need to add /usr/sbin to your path.

e.g.
shell: /usr/sbin/semodule -l

**Comment by siddharthist** [comment]
@avthart Are you still experiencing this issue?

**Comment by siddharthist** [comment]
A few questions:
 1. To whose path? 
 2. How would you suggest we add it to the path? 
 3. What if the shell used isn't bash?

**Comment by siddharthist** [comment]
Since we need to make a few assumptions that might not necessarily hold water in order to implement this, I'm going to close it for now. If anybody comes up with answers to the above questions, please reopen this issue!
