### ISSUE TITLE
Multi-tenancy

### ISSUE THREAD

**Issue by gnawux** [CiscoCloud/mantl#660]
I'm Xu, one of the maintainers of [Hyper](hyper.sh).

Is there a plan to support multi-tenancy in Mantl? If yes, would like to join force. We have a similiar project [HyperStack](https://launchpad.net/hyperstack).

**Comment by stevendborrelli** [comment]
@gnawux I think the hyper.sh project is incredibly interesting. Where do you think we could collaborate? 

I'm not sure where it would fit in, as some of our cloud providers don't have the ability to run hypervisors.

**Comment by siddharthist** [comment]
I'm going to close this since there hasn't been any further discussion in a while. @gnawux We'd love to more from you about collaboration! Please reopen this issue if you're still interested.
