### ISSUE TITLE
Remove default values for variables

### ISSUE THREAD

**Issue by eirslett** [CiscoCloud/mantl#729]
It can be confusing to have default values scattered around the terraform files. A better way (in my opinion) would be to remove all default settings, and move them to a "openstack.settings.tfvars" file (with "openstack.settings.sample.tfvars") where default values are explicitly defined, but with added `# comment` to the the right of the values, describing what they do and how variables could be overridden. Optional variables can be commented out by default.

**Comment by siddharthist** [comment]
I think it's actually good practice to put default values in our Terraform modules. I don't think it's necessarily confusing, Terraform has a clear hierarchy of variable precedence. Anyone else have thoughts?

**Comment by siddharthist** [comment]
Please reopen if anyone thinks this would be good!
