### ISSUE TITLE
Installing behind enterprise proxy

### ISSUE THREAD

**Issue by jtfogarty** [CiscoCloud/mantl#731]
Installing MI behind a proxy is difficult to say the least.  
What would be very helpful is to create a check to test connectivity to all URLs the playbook pulls from for each server in the inventory and then display a result of this check.

**Comment by siddharthist** [comment]
@jtfogarty I worry about the maintenance of a list of all the URLs we pull from. Seems like it could get out of date really easily, and a significant portion of our changes to Mantl would have to change/reference that list.

**Comment by BrianHicks** [comment]
We're also working on a way to package the resources so that we won't require an external network connection to install Mantl. Would that solve your problem, @jtfogarty?

**Comment by vallard** [comment]
I'm in the middle of an installation now and noticed that ansible failed.  My yum doesn't work because it needs a proxy to get outside the network.  I added the following:
```
- name: insert yum proxy
  sudo: yes 
  lineinfile: dest=/etc/yum.conf state=present regexp="http://myproxy.example.com:80" insertafter=EOF line="proxy=http://myproxy.example.com:80"
  ignore_errors: yes 
```
to the ```microservices-infrastructure/roles/common/tasks/main.yml``` file after the configure host files task around line 20.  This seemed to do the trick.  

Obviously this isn't something that should go into the main code but I'm wondering how I can help with these things.  Should I just wait for the external network connection requirement to go away @BrianHicks ?  

Thx!

**Comment by ipolyzos** [comment]
we have several installations behind proxy, in order to do so you need to augment environmental variables with http/s/no_proxy and there is only a handful on role to slightly modify. Applying env variables in the playbook level will cover most of it.

**Comment by siddharthist** [comment]
Maybe we could add a playbook to `addons/` that configures yum to use an external proxy? Is there anything else that blocks installs behind proxies?

**Comment by siddharthist** [comment]
I'm going to close this because we don't have a clear list of things that need to be changed. Whenever you run into anything that doesn't work when behind a proxy, please open a new issue and let us know, we'd love to fully support that use case.

**Comment by clijockey** [comment]
Guys, if you have internal access have a look at https://cisco.jiveon.com/docs/DOC-1385263 - this is how we got it working in the UK&I lab on Openstack with proxy configurations.

**Comment by siddharthist** [comment]
@clijockey If you have documentation on how to use Mantl behind a proxy, we'd love to have it be made public! Could you make a PR?
