### ISSUE TITLE
mesos logrotation issues

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/mantl#764]
Post-rotation, new logs are being written to the archive directory `/var/log/mesos/archive`. We need to review our configuration - there does appear to be some issues with using logrotate and mesos: https://issues.apache.org/jira/browse/MESOS-1375

**Comment by siddharthist** [comment]
What is the problem with writing to that directory? How could we fix it?

**Comment by ryane** [comment]
mesos expects them to be in /var/log/mesos. so when this happens, all of the logs are blank in the UI.
