### ISSUE TITLE
Move zookeeper to exhibitor

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#765]
Using consul-template to manage zookeeper is adding complexity. Investigate using exhibitor instead.

**Comment by emdem** [comment]
There are a few options... Netflix has an example with zookeeper/exhibitor running in the same container. Exhibitor just needs access to the zookeeper data directory and the zookeeper install directory.

Could be run in a separate container on the mesos masters and mount the volume container into an exhibitor container.

It also looks like there is a CiscoCloud project :dancer: 
https://github.com/CiscoCloud/exhibitor-mesos-framework

**Comment by eirslett** [comment]
From an operations point of view, it would be best if Exhibitor runs outside of Docker -  that means you're not dependent on the Docker daemon to be up and running for ZooKeeper to work. I suppose we could justify using consul k/v as a shared backend for Exhibitor, if it supports some form of degraded availability mode when consul isn't working.

**Comment by stevendborrelli** [comment]
What do we think of just trying zookeeper 3.5.1 and using dynamic reconfiguration? https://zookeeper.apache.org/doc/trunk/zookeeperReconfig.html

**Comment by stevendborrelli** [comment]
More ideas about this. Should we write a custom client (like exhibitor) that supports dynamic reconfiguration and is service discovery aware? Looking at  https://github.com/Netflix/exhibitor/issues/262 seems that exhibitor doesn't have support for 3.5. features. 

Also see https://groups.google.com/forum/#!topic/exhibitor-users/wfyn0e-faJk, as there may be some work here in Exhibitor.

**Comment by eirslett** [comment]
One option is to simply move ZooKeeper out of docker and run it right on the control nodes, and move dynamic configuration from consul-template to ansible. (Making the setup slightly less dynamic, but still acceptable in my opinion)

**Comment by siddharthist** [comment]
Is this issue still relevant now that we run ZK outside of Docker?

**Comment by siddharthist** [comment]
Closing because I think this is solved. Please reopen if it isn't!
