### ISSUE TITLE
Support docker 1.9 overlay networking

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#781]
http://www.container42.com/2015/10/30/docker-networking-reborn/

Docker 1.9 includes a new overlay network that uses consul as a storage backend. Since we already run consul on all nodes, we can hook docker into it.

**Comment by navinSing** [comment]
this would be very useful if someone just wants to use docker, without any other overheads.
thanks

**Comment by navinSing** [comment]
I guess then Calico will also be NOT needed for routing.

**Comment by stevendborrelli** [comment]
@navinSing We'll probably still need calico or another networking driver. Maybe we can have a chat later this week about the overall architecture and out plans. 

Also, docker 1.9 has not been released by redhat's, so we're going to have to wait a bit.

**Comment by kha0S** [comment]
Any ETA?

**Comment by stevendborrelli** [comment]
@kha0S with #1239 (merging this week), we'll be moving to Docker 1.10.x which will allow docker's networking. Once that is in we can look at the calico/docker integration.

**Comment by kha0S** [comment]
@stevendborrelli :+1:
