### ISSUE TITLE
Move chronos to running in Mesos

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#792]
Instead of installing Chronos via ansible, we can launch it as a Marathon task. 
- [ ] migrate to ansible task
- [ ] update mantl ui to correctly connect to Chronos UI

**Comment by ludovicc** [comment]
Check my Ansible module to control Marathon: https://github.com/ansible/ansible-modules-extras/pull/1258

**Comment by stevendborrelli** [comment]
@ludovicc thanks!
