### ISSUE TITLE
Include docker-cleanup rpm package by default, with appropriate settings. 

### ISSUE THREAD

**Issue by sehqlr** [CiscoCloud/mantl#831]
As of right now, we have a rpm package for docker-cleanup, but it is not installed by default. We need to include the install as well as appropriate exclusion settings. For example, zookeeper keeps data in a volume that could be collected, and break things. (Thanks for pointing this out, @ryane). Testing needs to be done to make sure that this doesn't happen. 

@stevendborrelli, is this something that we need to include in 0.5? What do you think?

**Comment by stevendborrelli** [comment]
Yes, it should be part of the docker role.

**Comment by eirslett** [comment]
The zookeeper case could probably be solved by moving zookeeper out of docker? #765

**Comment by stevendborrelli** [comment]
@eirslett we're planning on refactoring zk, but it won't make it for the 0.5 release.

**Comment by sehqlr** [comment]
I've tested my changes for excluding the zookeeper data volume from cleanup, and it works as expected. Are there other volumes that need to be excluded, or is this a go for a PR?

**Comment by stevendborrelli** [comment]
Yes. Update this ticket with the PR.

**Comment by sehqlr** [comment]
PR #861 is ready for testing

**Comment by stevendborrelli** [comment]
Closing this due to docker-gc installation.
