### ISSUE TITLE
Rename repository to ciscocloud/mantl

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#833]
I think we should update the `Readme.md` to announce the date we are renaming the git repo. 
cc @matjohn2 

We could try for December 8, 2015, and include the rename timeline in the 0.5 release docs
Let's put the tasks here: 
- [x] update front page readme to announce the repo name change
- [ ] update mantl.io (Dec 8)
- [ ] update documentation site (Dec 8)
- [ ] rename repo in github (Dec 8)

**Comment by benschumacher** [comment]
I'd like to talk about this a bit more w/you and @matjohn2. Just make sure we're on the same page re: plans/goals.
