### ISSUE TITLE
Consul Kubernetes integration

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/mantl#836]
It should be possible to run Kubernetes alongside Mesos on the same cluster.

**Comment by aronchick** [comment]
@ryane We'd love to help here - was there any particular scenario you were looking to tackle?

**Comment by ryane** [comment]
thanks! we just merged our first kubernetes support in #794. Right now, it runs separately from our default Mesos clusters. First, we want to make sure we can run Kubernetes alongside Mesos on the same cluster. Ultimately, we'd like to integrate k8s with consul and calico.

**Comment by aronchick** [comment]
That's terrific news!

I should say that getting Consul integrated has been one of the most
requested issues we've ever had -

https://github.com/kubernetes/kubernetes/issues/1957

Any chance you and/or the team want to pick it up?

**Comment by stevendborrelli** [comment]
@aronchick Yes, we've been thinking along those lines. The easiest step (and what we are working on), is to feed consul service discovery with a tool similar to kube2skdns. 

Once we get that going, we'll see if the k/v store can be migrated without too much trouble.

**Comment by eirslett** [comment]
Wouldn't the resource estimator from Mesos conflict with the one from Kubernetes? So they could potentially allocate resources that aren't available, maybe in a race conditoin?

**Comment by stevendborrelli** [comment]
@eirslett that is a great point. We're keeping the bare metal clusters apart for now as we figure out lower-level integration points (calico, consul, vault, traefik, ui). 

Some ideas of future running modes:

- separate roles in terraform metadata to keep nodes isolated (i.e., role=k8s-node)
- Kubernetes-mesos via mantl-api: https://docs.mesosphere.com/services/kubernetes/

**Comment by aronchick** [comment]
Please let me know if you'd like me to connect you with the folks on our
side doing the Mesos integration - there are quite a few :)

In addition to that, there's been some thinking in regards to what needs to
happen with Consul (and others) to get them integrated. Would you like me
to connect you with the right folks over here? (at Google?)

**Comment by Zogg** [comment]
@aronchick I'm writing this https://github.com/asteris-llc/kube2pyconsul to bridge Kube->consul services discovery. Mainly using kube's api watches.

As to completely switch Kube away from etcd into consul - I'm not sure about it's validity, when flanneld and calico both use etcd too are being used more and more with kubernetes.

**Comment by thockin** [comment]
Given that kubernetes' use of etcd is basically an implementation detail, changing to consul should be pretty easy.  That said, it sounds like the way most people want to use Consul is in a shared environment, so they are not too excited about our philosophy of "it's a detail".

Having a small bridge program between systems is a great pattern, though.

**Comment by eirslett** [comment]
Calico should also be easy to port to consul.

**Comment by Zogg** [comment]
For 0.6 we'll go with separate worker nodes dedicated to kube. 

And in a long term having kube and calico running on top of consul would be really great.

**Comment by siddharthist** [comment]
For reference, here's the Calico issue that tracks Consul integration: https://github.com/projectcalico/calico/issues/782

**Comment by siddharthist** [comment]
Closing because we do run k8s and mesos in the same cluster :)
