### ISSUE TITLE
Calico support in Kubernetes

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/mantl#837]
Currently calico cannot assign IP to container/pod which has been launched from manifest file. See #794

**Comment by Zogg** [comment]
The calico bug has been fixed. https://github.com/projectcalico/calico-kubernetes/issues/55

Kubernetes 1.1.3 should have the fix in the release.

**Comment by siddharthist** [comment]
[We now use K8s v1.2](https://github.com/CiscoCloud/mantl/blob/bf4327eb7e3dcc7fe107b6c3132d621335f6d1ae/group_vars/all/kubernetes_vars.yml#L14). Is this fixed, is this part of #1133, or something else entirely?

**Comment by Zogg** [comment]
It has been fixed (at least in the mesos-calico-kube PR that is waiting to be merged in).
