### ISSUE TITLE
On-premise installation support

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#847]
We are seeing increased requests for on-premise installations.Let's improve the bare-metal installation experience. 

Please list features here, we'll break these out into feature issues: 

- [ ] Support for corporate proxies
- [x] Example Ansible inventory files (we can take from 0.2)
- [ ] ISO/Kickstart support

**Comment by benschumacher** [comment]
cc @pinireznik

**Comment by mongrelion** [comment]
There has been some progress for on-premise installation on the Terraform providers for UCS and Cobbler.
Is this somehow related to what you're talking about, @stevendborrelli?

**Comment by stevendborrelli** [comment]
@mongrelion yes, we'd love to have UCS support. 

We're also looking at plain ansible for deploying files onto a group of regular servers.

**Comment by navinSing** [comment]
so we are expecting microservice installation on bare-metal .. which means no need for openstack etc right.. i don't want to maintain openstack locally .. i don't see any benefit out of it.. 

+1 if that's the case ..

**Comment by muthumayan** [comment]
Openstack would still be needed for other infrastructure pieces like network segments and storage access for tenant micro-services.
- Muthu

**Comment by stevendborrelli** [comment]
On bare metal, you won't need any of the networking parts for most of the functionality. The load balancers work best if you can set up a wildcard dns.

**Comment by muthumayan** [comment]
Perhaps i haven't conveyed my requirements correctly. Let me have a meeting with Neelesh and respond back.

**Comment by navinSing** [comment]
would definitely love to see the bare metal without openstack in 0.6.0
Thanks

**Comment by larry-svds** [comment]
I am looking for bare metal (set of Intel NUCs) in the offices,  AWS for QA and Customer Prod.   Just getting involved in Mantl. Been reading the Gitter from end of September.   Amazing work.  Ive looked at Paasta, Singularity, Panteras, etc and you folks are hard core.  I'm learning a lot!

**Comment by navinSing** [comment]
any updates on this or its timeline

**Comment by larry-svds** [comment]
Looks like I have this working.  I have a few questions for the experts and then I'll make my notes public for folks that want to do bare metal.  There are just a few gotchas but relatively smooth. I did this on 8 Intel NUCs.

**Comment by navinSing** [comment]
awesome .. please share ==) the same

**Comment by tonybecker** [comment]
I have a bare metal deployment scenario as well. I have some servers I could test this on when available.

**Comment by larry-svds** [comment]
Hey @tonybecker would love to have someone test my instructions on an updated source before doing a pull request.  There are a few gotchas.  I am on the gitter app for this group.  You can look at my instructions at https://github.com/larry-svds/microservices-infrastructure/blob/feature/bare-metal/bare-metal/README.md  there are a few gotchas.  But another person got through this in a very short time.

**Comment by siddharthist** [comment]
We have a bare-metal README now, is there anything else we need?

**Comment by larry-svds** [comment]
The few gotchas are part of that README and the one change to sample.yml that was just merged in #1147   I think this issue is covered.  My 2 cents.

**Comment by vanthome** [comment]
@siddharthist can you give a pointer, I cannot seem to find it in the docs.

**Comment by larry-svds** [comment]
@vanthome is this what you are looking for?  https://github.com/CiscoCloud/mantl/tree/master/docs/bare-metal

**Comment by vanthome** [comment]
@larry-svds right, thaks!
