### ISSUE TITLE
Vault Support

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#859]
Collect vault support here. We'll be refactoring vault.

- [x] Vault 0.4 support. 
- [ ] Docker secret support
- [ ] Use vault to distribute configuration secrets
- [ ] Vault secret sharing using tmpfs and bind mounts

**Comment by Zogg** [comment]
Are we thinking along the lines of consul-template, but for vault?

**Comment by siddharthist** [comment]
I would also add 
 - [ ] enable TLS verification
 - [ ] enable [audit logs](https://www.vaultproject.io/docs/audit/index.html)

**Comment by siddharthist** [comment]
I'm going to close this. Let's open separate, granular issues for integrations we'd like to see!
