### ISSUE TITLE
Distributive health checks should not check collectd plugins

### ISSUE THREAD

**Issue by tymofii-polekhin** [CiscoCloud/mantl#913]
Today, i decided that i don't need `marathon` metrics at all, and deleted `marathon.py` and `marathon.conf` - plugin and configuration for collectd-marathon-plugin.

After that distributive health check went WARN and MantlU can't redirect to Marathon UI anymore.

Service health should not rely on collectd plugin status, or any other additional support stuff.

**Comment by stevendborrelli** [comment]
If we are not monitoring it or monitoring configuration is broken for a service, shouldn't it report as being unhealthy? 

Or should we make collectd itself unhealthy? I do think we need to know if something we expect to be there is not working correctly.

**Comment by stevendborrelli** [comment]
@tymofii-polekhin we're refactoring many of the packages starting next week. The checks on the logging of a service will be separated from the service itself.

**Comment by siddharthist** [comment]
We've refactored these, this probably happened here: https://github.com/CiscoCloud/mantl/pull/1268/files#diff-fc83d25ba569c79a5d6213e1915ad4abR10
