### ISSUE TITLE
monitoring: Check disk usage and inodes

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#935]
With https://github.com/CiscoCloud/distributive/pull/117 we can now check to see if filesystems are nearing critical levels for inode usage. Inode checks are important because multiple failing mesos jobs have the risk of filling the filesystem up with many small files. 

- [x] merge pull https://github.com/CiscoCloud/distributive/pull/117 into distributive
- [ ] create new distributive rpm
- [ ] add disk and inode checks rpms
- [ ] add consul checks for distributive inode and disk checks, create rpm 

Tagging @siddharthist, @sehqlr, @TanyaCouture to move this forward.

**Comment by siddharthist** [comment]
I'm planning on fixing https://github.com/CiscoCloud/distributive/issues/115, releasing a new distributive version, and then we can make new checklists/rpms. It would be nice to fix #740, #717, #633 at the same time we release a new version, and none of those should be too difficult to knock out.

**Comment by stevendborrelli** [comment]
@siddharthist will we be able to tag this for 0.6?

**Comment by siddharthist** [comment]
@stevendborelli I'm having difficulty with the inode checks, but I've been working on the disk usage one, and should be done in the next few days.
