### ISSUE TITLE
glusterfs health checks fail on default centos-release-7-1.1503

### ISSUE THREAD

**Issue by larry-svds** [CiscoCloud/mantl#953]
On a first run through mantl.io 0.51.  Running the gluster addon is run and consul health checks are created.  These give the Error:

        sudo: sorry, you must have a tty to run sudo

http://unix.stackexchange.com/questions/122616/why-do-i-need-a-tty-to-run-sudo-if-i-can-sudo-without-a-password

Checking the /etc/sudoers file there is the following comment.

        # Disable "ssh hostname sudo <cmd>", because it will show the password in clear.
        #         You have to run "ssh -t hostname sudo <cmd>".
        #
        Defaults    requiretty

Commenting this line and rebooting does get you past the health check problem.

Should we uncomment this in sudoers or add the -t in the right place?

Where is the right place?

    - name: let consul use glusterfs commands for health checking
      sudo: yes
      template:
        src: consul-gluster-healthchecks.j2
        dest: /etc/sudoers.d/consul-gluster-healthchecks
      tags:
        - glusterfs

Fully spelled out in a control node the contents are:

    consul	ALL=(ALL)	NOPASSWD:	/usr/sbin/gluster pool list
    consul	ALL=(ALL)	NOPASSWD:	/usr/sbin/gluster volume info container-volumes

how do you add -t to that?

I have fixed this problem by running the following ansible accross the affected nodes. 

       - name: remove default requiretty in sudoers so that consul healthchecks don't fail 1. add document line.
         sudo: yes
         lineinfile: dest=/etc/sudoers insertafter='^Defaults    requiretty' line="#Defaults    requiretty" state=present

       - name: remove default requiretty in sudoers so that consul healthchecks don't fail 2. remove default
         sudo: yes
         lineinfile: dest=/etc/sudoers regexp='^Defaults    requiretty'  state=absent

I'd be happy to do a pull request against mantl.io if we feel that is ok. Should it be done in 
Common or Glusterfs?

**Comment by siddharthist** [comment]
@larry-svds Anything gluster-specific should be part of the Gluster addon. Thanks for the great debugging!

**Comment by stevendborrelli** [comment]
Going to close this. Please reopen if it is still an issue.
