### ISSUE TITLE
Error while installing or configuring the Mantle with AWS.

### ISSUE THREAD

**Issue by kumaranjv061990** [CiscoCloud/mantl#981]
Hi 

ERROR: /home/ubuntu/microservices-infrastructure/terraform/aws.sample.tf:1: Invalid ini entry: { - need more than 1 value to unpack

provider "aws" {
  access_key = "******************"
  secret_key = "**********************"
  region = "Asia Pacific (Singapore)"
}

module "aws-dc" {
  source = "./terraform/aws"
  availability_zone = "us-east-1e"
  ssh_username = "centos"
  source_ami = "ami-96a818fe"

  control_count = 3
  worker_count = 3
  edge_count = 2
}

**Comment by kumaranjv061990** [comment]
If mantle can provide the installation video or clear steps to install . That would help.

**Comment by ryane** [comment]
what command are you running when you get that error? I haven't seen that exact error before but there are a couple of problems that I see:

1. For `region`, you need to use the AWS identifier. In your case, I think you want `ap-southeast-1`.

    if you have the aws cli installed and configured, you can get the region identifiers by running `aws ec2 describe-regions`

2. The `availability_zone` and `source_ami` variables should be valid for the `region` you selected. It looks like you would want to use either `ap-southeast-1a` or `ap-southeast-1b` for `availability_zone` and `ami-2a7b6b78` for `source_ami`.

    You can get the azs for a region by running `aws ec2 describe-availability-zones --region ap-southeast-1` and the correct amis are at https://aws.amazon.com/marketplace/ordering?productId=b7ee8a69-ee97-4a49-9e68-afaee216db2e&ref_=dtl_psb_continue&region=us-east-1 (see manual launch tab).

**Comment by kumaranjv061990** [comment]
ansible-playbook -i /home/ubuntu/microservices-infrastructure/terraform/aws.sample.tf  -e @security.yml terraform.yml

This is the command i am executing.

**Comment by ryane** [comment]
Ah, yes, you are missing a few steps Please follow the steps in this guide to get your AWS environment provisioned: https://microservices-infrastructure.readthedocs.org/en/latest/getting_started/aws.html

Then, you can continue on with the Ansible steps - see https://microservices-infrastructure.readthedocs.org/en/latest/getting_started/index.html#deploying-software-via-ansible.

**Comment by stevendborrelli** [comment]
I'm closing this issue. Please reopen a new issue if you are having installation issues.
