### ISSUE TITLE
Logstash image is pulled for too long

### ISSUE THREAD

**Issue by loshkovskyi** [CiscoCloud/mantl#987]
I noticed that it takes too much time to pull Logstash images when deploying Mantl. It appeared the image was updated from `0.2` to `1.5.3` with a significant difference in size:
```
docker images|grep logstash
docker.io/ciscocloud/logstash 1.5.3 630.5 MB
docker.io/ciscocloud/logstash 0.2   296.4 MB
```
The description on Docker Hub doesn't explain what changes have been made: https://hub.docker.com/r/ciscocloud/logstash

It's not obvious where to find Dockerfile for the latest Logstash image.

**Comment by siddharthist** [comment]
I believe it's the one available here: https://github.com/CiscoCloud/docker-logstash. Related: #983.

**Comment by loshkovskyi** [comment]
You are right, but it's never been updated with any changes related to the `1.5.3` tag.

**Comment by siddharthist** [comment]
We're exploring using another logging driver (#646), which should fix this issue.

**Comment by stevendborrelli** [comment]
@loshkovskyi this was updated in PR #782.

**Comment by loshkovskyi** [comment]
@stevendborrelli, That PR doesn't help to understand why the extra 330 MB were added to the image. My point is that we need to update documentation each time we make changes to the code.

**Comment by stevendborrelli** [comment]
@loshkovskyi the image was updated in that PR, but it doesn't look like the Dockerfile for the 1.5.3 image came from the ciscocloud/docker-logstash repo. So I think we need to query the developer to review the changes they made to their local Dockerfile.

**Comment by tymofii-polekhin** [comment]
hi all, the `ciscocloud/docker-logstash:1.5.3` image is actually official logstash docker image with one fix - run as root, to been able to read docker container logs from host system.
We need to use this image anyway because it has `logstash-output-elasticsearch` and `logstash-output-kafka` plugins installed

**Comment by stevendborrelli** [comment]
@tymofii-polekhin @loshkovskyi I'm ok with that, I just want to make sure we are on the same page. We have a docker image in our hub that doesn't match the source code. 

Our standards for any containers that are part of mantl are:
- image Dockerfile should be on Github
- Docker images should be built automatically by the docker hub or another CI system

**Comment by siddharthist** [comment]
Since Logstash isn't part of the default installation anymore, can we close this? It takes about 10-15min for the ELK stack to fully initialize anyway.
